### ISSUE TITLE
Update native apps menu bar section

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1360]
https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates

> The native apps are not restricted by the Chrome standards for the menu bar. With the native apps, you can create collections, switch to history requests, and more.

you can no longer create collections or switch history via menu bar. Replace these with 'Check for Updates, create Postman Windows, etc'

**Comment by ArifPMan** [comment]
I need more information on this issue. Will discuss once you come back...

**Comment by ArifPMan** [comment]
Fixed the issue, pending review:

https://github.com/postmanlabs/postman-docs/pull/1430
