### ISSUE TITLE
Improve Postman Console link

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1362]
https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
> The latest version of the native app also has a built-in _console_, which allows you to view the network request details for API calls.

_console_ should deep link to https://www.getpostman.com/docs/v6/postman/sending_api_requests/debugging_and_logs#network-calls-with-postman-console

**Comment by ArifPMan** [comment]
fixed and pushed it to the docs git. Needs to be approved and merged.
