### ISSUE TITLE
The local and data variable scopes are inverted in the variable scopes

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1366]
In the list of variable scopes and the illustration, the local variables are lower in the hierarchy then data variables. The local variables have the highest precedence among all the variable scopes.

The list should be 
Global
Collection
Environment
Data
Local

and same in illustration

Also the local variables are set using `pm.variables.set`. This is not documented anywhere. Maybe we could just mention it as to what local variables are somewhere in this doc.

**Comment by ArifPMan** [comment]
This issue is fixed and pushed to Git. Pls review and approve

**Comment by ArifPMan** [comment]
Validated the issue in Prod.
