### ISSUE TITLE
Include collection sidebar screenshot in collection sidebar

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1375]
https://www.getpostman.com/docs/v6/postman/launching_postman/creating_the_first_collection

> Congratulations! You can see all of your collections under the Collections tab of the sidebar on the left.

It would be good if we introduce a screenshot of the collection sidebar.

**Comment by ArifPMan** [comment]
Fixed, pending review...

**Comment by ArifPMan** [comment]
Don't see the updates in prod yet

**Comment by numaanashraf** [comment]
@ArifPMan is the fix already merged via any PRs yet?
