### ISSUE TITLE
Fix broken link references in "Running Collections"

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1396]
https://www.getpostman.com/docs/v6/postman/collection_runs/starting_a_collection_run

"To learn how to run multiple iterations, see Running multiple iterations" incorrectly points to https://www.getpostman.com/docs/v6/postman/collection_runs/using_environments_in_collection_runs.

It should point to https://www.getpostman.com/docs/v6/postman/collection_runs/running_multiple_iterations

**Comment by ArifPMan** [comment]
Fixed, pending review

**Comment by ArifPMan** [comment]
https://github.com/postmanlabs/postman-docs/pull/1401
