### ISSUE TITLE
Issues In New Button docs

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1402]
https://www.getpostman.com/docs/v6/postman/launching_postman/newbutton

1. In the first paragraph of Create New section, the first two lines just explain what is in the UI. Let's expand this with a one line summary of these blocks and then link to the relevant sections below for each
> In BUILDING BLOCKS, create a new request, collection, or environment.
In ADVANCED, create new documentation, a mock server, or a monitor.

2. Blocks are incorrectly mentioned as features.
> You can also directly create a new feature when you click the down arrow at the right side of the New button.

3. Highlight or draw attention to the New dropdown in the screenshot below.
https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/WS-new-button-menu-blk.png

4. Update environment screenshot at https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/WS-manage-environments-newButton.png

**Comment by ArifPMan** [comment]
Fixed, pending review..

**Comment by ArifPMan** [comment]
Fixed, pending review:

https://github.com/postmanlabs/postman-docs/issues/1402
