### ISSUE TITLE
URLs for Mock Server articles on Learning Center return 404

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1403]
The following URLs for articles on the Learning Center regarding Mock Server usage return 404:

https://learning.getpostman.com/docs/v6/postman/mock_servers/intro_to_mock_servers
https://learning.getpostman.com/docs/v6/postman/mock_servers/mocking_with_examples
https://learning.getpostman.com/docs/v6/postman/mock_servers/mock_with_api
https://learning.getpostman.com/docs/v6/postman/mock_servers/matching_algorithm

There may or may not be others, this is just what I noticed initially.

**Comment by JP-from-Postman** [comment]
Another dead Learning Center link:
https://learning.getpostman.com/docs/v6/postman/api_documentation/intro_to_api_documentation

Same issue (/v6), just posting for visibility.

**Comment by captchadex** [comment]
Issue fixed.
