### ISSUE TITLE
Changes in Linux installation doc

### ISSUE THREAD

**Issue by SamvelRaja** [postmanlabs/postman-docs#1404]
Page: https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
1. Linux installation is not different for different distributions, creating postman.desktop file is common for all supported distributions for us. so specify that it as an extra step to link the app executable.

2. Desktop entry file needs to specify executable path instead of just the name.
```
cat  > ~/.local/share/applications/postman.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=<Your_Install_Dir>/Postman/app/Postman
Icon=<Your_Install_Dir>/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```

**Comment by SamvelRaja** [comment]
@ArifPMan  thanks for making the changes.
I had done a quick installation of postman on a new Linux machine. Faced few problems and I believe those can be explained via docs.

1.  I want to know that unzipping to be more clear(bold or newline) it is unclear inside the paragraph.
2.  The desktop file creation, since we don't have code mode in doc yet, I believe we can ask them to create using an explanation.

Like,

Create `Postman.desktop` in `~/.local/share/applications/Postman.desktop` with the content below

```
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=<Your_Install_Dir>/Postman/app/Postman %U
Icon=<Your_Install_Dir>/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```
Once the Desktop.file is created, the postman app can be opened via application launchers.

another way to open the app via terminal is `./<Your_Install_Dir>/Postman/Postman`

Note: 
1. Avoid starting postman using `sudo` command, this will mess up the permissions on the files created by postman.
2. Make sure you have read/write permission for `~/.config` folder where Postman stores the information
3. Ubuntu 18 users, you must additionally install `libgconf-2-4 package` to ensure a smooth Postman run. This package, shipped by default until Ubuntu version 18, has been dropped, and is mandatory for Postman run. Use the following command to install libgconf-2-4
`apt-get install libgconf-2-4`

**Comment by ArifPMan** [comment]
Addressed the issues. https://github.com/postmanlabs/postman-docs/pull/1409
