### ISSUE TITLE
Outdated behavior of duplicate GET requests in history

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1410]
https://www.getpostman.com/docs/v6/postman/sending_api_requests/history

> Postman avoids duplicating GET requests with the same URL in the history.

This behavior is not longer present in our stable apps. We create a new history for every request you send in Postman. We can remove this line from the documentation.

**Comment by ArifPMan** [comment]
Fixed the issue. The link to the PR is:

https://github.com/postmanlabs/postman-docs/pull/1415

**Comment by ArifPMan** [comment]
Is this how you wanted me to put the link Numaan? Please confirm.

**Comment by numaanashraf** [comment]
This is perfect. Thanks @ArifPMan
