### ISSUE TITLE
Dead links on Managing Your Billing learning center article

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1412]
Article is here:
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_billing/

Dead Links:

> Change your plan (Pro Monthly)
> Add user slots to your plan (Pro Annual)
> Set instructions for next billing cycle
> Set the monitoring block count
> Manage your invoices
> Cancel your plan

Dead links contain: docs/pro/...
`/docs/pro/managing_pro/changing_your_plan`

Correct URL is: docs/postman_pro/...
`/docs/postman_pro/managing_postman_pro/changing_your_plan`

**Comment by wsfuller** [comment]
Have resolved the URLs. 

- Billing Overview > Billing and Pricing
- "How to get a copy of an existing invoice" links correspond to correct anchors on Changing your plan
