### ISSUE TITLE
Postman collections document generation error

### ISSUE THREAD

**Issue by AlphaWong** [postmanlabs/postman-docs#1413]
If the first response is 200 and empty body
All the following example response will gone.

# Video
https://youtu.be/6CjFMiZ5Tmo

# Possible reason
All the response example is in the same `html DOM ` if the first one do not have response. The response DOM will not be created. Therefore, all the following response will not shown.

**Comment by numaanashraf** [comment]
@AlphaWong Thanks for reporting. This repo contains the source code for Postman's product documentation. I've created an issue at our public tracker - https://github.com/postmanlabs/postman-app-support/issues/5224
