### ISSUE TITLE
Folders are not added in alphabetical order anymore

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1417]
https://www.getpostman.com/docs/v6/postman/collections/managing_collections#adding-folders

> Folders are initially ordered alphabetically by name and folder name. 

This info is outdated. New folders are created at the end. Please remove this sentence.

**Comment by ArifPMan** [comment]
Fixed the issue. Look at here:

https://github.com/postmanlabs/postman-docs/pull/1427
