### ISSUE TITLE
Remove {:target="_blank"}

### ISSUE THREAD

**Issue by captchadex** [postmanlabs/postman-docs#1422]
`{:target="_blank"}` is seen in some of the files due to how the old docs site worked. These aren't needed anymore and are improperly rendered on the Learning Center.

I have started to remove these as I get around to them but if anyone else has the time, please also remove these while working on docs.

Thanks!

**Comment by ArifPMan** [comment]
Fixed, pending review.

https://github.com/postmanlabs/postman-docs/pull/1433
