### ISSUE TITLE
Recommend using env/global/collection variables than path variables

### ISSUE THREAD

**Issue by harryi3t** [postmanlabs/postman-docs#1428]
We should not recommend people to use path variables, instead, they should be using environment, collection or global variables. I don't see a use case where new users should be using path variables.

But, in our docs, even the core concepts like [sending a request](https://www.getpostman.com/docs/v6/postman/sending_api_requests/requests) is teaching people how they can use path variables.

We can talk about briefly variables in general there and link to the variables docs. In the variables docs we can talk about path variables and then recommend to use other variables also explaining the reasons.

Here's a link to a issue on our community where a new user started using path variables after checking the docs. 
https://community.getpostman.com/t/advantage-of-path-variables-over-environment-or-global-variables/2697/3

Some past issues with path variables
 - https://github.com/postmanlabs/postman-app-support/issues/4423
 - https://github.com/postmanlabs/postman-app-support/issues/2427

**Comment by timdmackey** [comment]
Can you explain further why this has been proposed as the solution to problems with using path variables? There are perfectly legitimate reasons to use path variables that do not fit under the umbrellas of collection, environment, or global variable. Situations I'm thinking of are where data stored in a path variable is being used like a url parameter, but is part of the path instead.

There are many examples of this in the Shopify API – for example, to get the tags for a specific product, you would use a url like this:

/admin/products/_**:product_id**_.json?_**fields=tags**_

or expanded:

/admin/products/_**486748932092**_.json?_**fields=tags**_

Both _**fields**_ and _**product_id**_ are dynamic data that are tied only to the current request, and as such they should to be accessible and defined within the current request. At the moment, the solution is to just embed the data into the URL, which is far from ideal.

**Comment by ArifPMan** [comment]
@harryi3t - Can you please resolve this with the right stakeholders if we have to take this up or close the issue because some of the community members feel otherwise?

**Comment by kaustavdm** [comment]
Closing this since our current docs talk about both path variables along with other types of variables.
