### ISSUE TITLE
Outdated Screenshots

### ISSUE THREAD

**Issue by sivcan** [postmanlabs/postman-docs#1431]
(Screenshots are of a version previous than v6.0)

URL: https://www.getpostman.com/docs/v6/postman/collection_runs/using_environments_in_collection_runs

![image](https://user-images.githubusercontent.com/12631777/46075262-91865800-c1a7-11e8-80f9-998f729b10c5.png)

![image](https://user-images.githubusercontent.com/12631777/46075263-92b78500-c1a7-11e8-98ae-0badae4db02a.png)

**Comment by sivcan** [comment]
URL: https://www.getpostman.com/docs/v6/postman/collection_runs/integration_with_jenkins

![image](https://user-images.githubusercontent.com/12631777/46075875-7e748780-c1a9-11e8-96a6-276d7f95bc90.png)

**Comment by sivcan** [comment]
Postman app screenshots are outdated
URL: https://www.getpostman.com/docs/v5/postman_for_public_apis/run_button

![image](https://user-images.githubusercontent.com/12631777/46075951-be3b6f00-c1a9-11e8-94b7-c3a58bc7939e.png)

**Comment by sivcan** [comment]
Postman App screenshots are outdated:
https://www.getpostman.com/docs/v6/postman_for_public_apis/run_button

![image](https://user-images.githubusercontent.com/12631777/46076010-f2169480-c1a9-11e8-8ee2-a70e635e2cb8.png)

**Comment by ArifPMan** [comment]
Addressed the issue.
