### ISSUE TITLE
Navigating Postman doc

### ISSUE THREAD

**Issue by harshachelle** [postmanlabs/postman-docs#1435]
Given that there are constant updates to the app- keeping a check on this particular doc page will help. Especially because it is very often shared with users also.

https://www.getpostman.com/docs/v6/postman/launching_postman/navigating_postman

To start with it'd be great if the documentation includes the below items that are mentioned in the screenshot. ie, the Team button along with the drop down and options.

<img width="1440" alt="monitoring usage overview screenshot" src="https://user-images.githubusercontent.com/12132423/46198238-970bab80-c329-11e8-8ef0-cc352934b58e.png">

**Comment by ArifPMan** [comment]
Fixed this issue:

https://github.com/postmanlabs/postman-docs/pull/1436
