### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1437]
OP: @loopDelicious https://github.com/postmanlabs/postman-app-support/issues/5271

Customer is reporting a number of 404s throughout the Postman docs, throughout monitoring pages, documentation pages, and probably throughout the rest of the docs

- 404s
- also some variables (like email) are not resolving in the new learning center docs - see screenshot
- also consider running Link Checker collection template to monitor for broken links

<img width="833" alt="screen shot 2018-09-27 at 12 37 17 pm" src="https://user-images.githubusercontent.com/17693714/46170325-4d9c5d00-c252-11e8-8e5b-3631cf691453.png">

**Comment by tristandenyer** [comment]
Closing, this has been fixed: https://learning.getpostman.com/docs/postman/monitors/intro_monitors/#monitoring-resources-in-multiple-regions
