### ISSUE TITLE
We didn't mention that private mock servers are available for free users too

### ISSUE THREAD

**Issue by anudeepmedicharla** [postmanlabs/postman-docs#1440]
We mentioned that Pro and Enterprise users can make their mock servers private. We should also mention that this feature is available to free users as well.
 
https://www.getpostman.com/docs/v6/postman/mock_servers/intro_to_mock_servers

**Comment by anudeepmedicharla** [comment]
I'm referring to the content under "Types of mock servers"

**Comment by anudeepmedicharla** [comment]
@ArifPMan

**Comment by ArifPMan** [comment]
Fixed, pending review...

https://github.com/postmanlabs/postman-docs/pull/1444

**Comment by ArifPMan** [comment]
Addressed the issue - https://github.com/postmanlabs/postman-docs/pull/1444
