### ISSUE TITLE
Optimize search experience in Postman docs

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/postman-docs#1452]
OP: https://github.com/postmanlabs/postman-app-support/issues/5338 by @loopDelicious 

Currently there are commonly searched topics that either aren't covered in the Postman docs OR they aren't indexed properly in the search.

Example
When someone searches for jwt in the Postman docs, they see zero results. However, we can add a JSON Web Token (JWT) example under the Bearer Token Auth helper section of the Authorization page, or link to our YouTube video on JWT authorization. Alternatively, just add the text "JWT" in this section, and the section will be indexed in the search. This will point them in the right direction, when they do this search, instead of showing zero results.

We know some of these metrics:

    Most popular searches
    Search results that return zero results

I gave Arif access to our Algolia team account, so he has access to these search metrics. We can also compare with Google Analytics to see search bounces for when a person lands on a page they weren't expecting.

**Comment by ch264** [comment]
Algolia has been implemented in Learning Center v2 and only indexes v6 docs. This issue is out of date and will therefore be closed.
