### ISSUE TITLE
Clarify documentation and collaboration features as paid vs. free

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1463]
Clarify documentation and collaboration features as paid vs free:

Custom domains are for Pro and Enterprise only: https://www.getpostman.com/docs/v6/postman/api_documentation/adding_and_verifying_custom_domains

Publishing docs is for free users (not just Pro):
https://www.getpostman.com/docs/v6/postman_for_publishers/public_api_docs

Publishing docs is for free users, but using a custom domain is for Pro and Enterprise:
https://www.getpostman.com/docs/v6/pro/what_is_pro
https://www.getpostman.com/docs/v6/enterprise/intro_to_enterprise

**Comment by ArifPMan** [comment]
Addressed, so closing the issue.
