### ISSUE TITLE
Re-index or automate search indexing

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1466]
When new content is added to the docs, the new content is not indexed by search. New content does not display in search results.

I gave @ArifPMan and @wsfuller access to the Algolia account.

**Comment by tristandenyer** [comment]
@loopDelicious can you give @wsfuller and I access to Algolia account as well?

**Comment by tristandenyer** [comment]
Suggesting we close this. I tested the latest 9 docs added to LC and they are in the Algolia search results. Let me know if any are still missing and will reopen.
