### ISSUE TITLE
Add docs re: mocks, monitors, integrations with workspaces

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1471]
There's currently no documentation related to how mocks, monitors, or integrations are not shared across workspaces.

Clarify the difference between sharing collections and environments across multiple workspaces, vs how other elements associated with a collection are not shared across workspaces, especially as it relates to team collaboration. 

This question comes up during training, product demos, and occasionally online (https://community.getpostman.com/t/created-mock-server-not-visible-in-team-workspace/3480).

**Comment by SueSmith** [comment]
Commenting to keep open

**Comment by claireriley** [comment]
Closing this as we've updated this documentation more recently and introduced workspace as a container.
