### ISSUE TITLE
Remove algolia-branded search logo

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1480]
We have a paid version for search, so don't need to display search provider attribution in the search form. In the search component, should be `poweredBy: false`.

<img width="1521" alt="screen shot 2018-12-18 at 10 14 31 am" src="https://user-images.githubusercontent.com/17693714/50174031-eff63a80-02ad-11e9-9e22-5a005742fbb3.png">

**Comment by tristandenyer** [comment]
Created and prioritized this as WEBSITE-743.

**Comment by tristandenyer** [comment]
Still looking into this. I uncommented out the line and the logo still shows. My access to Algolia does not show this app/project, so unable to verify that we do in fact have a paid version.

**Comment by tristandenyer** [comment]
Since this is an app issue and in a Jira ticket, I am closing this ticket. All work will be tracked there.
