### ISSUE TITLE
Update old references to integrations page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1486]
References to the previous integrations page in the web dashboard should be updated to accommodate Workspaces UX flow in the web dashboard.

An example here with reference links to the Integrations page and Integrations dashboard:

https://learning.getpostman.com/docs/postman/postman_api/intro_api/

**Comment by SueSmith** [comment]
@loopDelicious currently the integrations links on this page are redirecting to workspaces - is that expected behavior?

**Comment by loopDelicious** [comment]
@SueSmith no, we previously had an integrations page. However, with the introduction of workspaces, you can access integrations within a workspace. Therefore in docs, you can only link to all workspaces, then select a single workspace, and then navigate to the integrations page within that workspace. The docs copy needs to be updated accordingly in several places.
