### ISSUE TITLE
pm.test(), pm.expect(), are under pm.cookies section header

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1493]
Looks like there may be a missing section header for the `pm.test` and `pm.expect` references on the Sandbox API reference site.

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmcookies

`pm.test` and `pm.expect` look like they’re under the `pm.cookies` section (don’t think this is right):

<img width="1680" alt="screen shot 2019-01-08 at 11 26 38 am" src="https://user-images.githubusercontent.com/43283131/50859833-456fb580-1349-11e9-9bcb-b2e3b0d5be68.png">

**Comment by kaustavdm** [comment]
This seems to be fixed. Closing this for now.
