### ISSUE TITLE
Clarify version difference of Team Library and Workspaces

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1495]
Clearly differentiate between the v5 and earlier Team Library and the newer Workspaces. Perhaps include a link to Workspaces on the Team Library page if people are interested in updating their version.

Based on user feedback:
https://community.getpostman.com/t/sharing-page-content-is-significantly-out-of-date/3729

**Comment by ArifPMan** [comment]
We are not supporting v5 Postman documentation so I don't find a way out to address this request. Let me consult with the product team and get back.

**Comment by kaustavdm** [comment]
This looks fixed now. I will close this issue for now. But let us not shoot down community feedback as invalid.
