### ISSUE TITLE
Monitoring FAQ page returning 404

### ISSUE THREAD

**Issue by harshachelle** [postmanlabs/postman-docs#1496]
**_Describe the bug:_**
Monitoring FAQ page returning 404

**_To Reproduce:_**
Go to - https://learning.getpostman.com/docs/postman/monitors/faqs_monitors

**_Screenshot:_**
![screen shot 2019-01-10 at 11 02 14 am](https://user-images.githubusercontent.com/12132423/50948169-7970e500-14c7-11e9-8557-dbe485c5ab98.png)

**Comment by wsfuller** [comment]
Page is up, had to manually add to Contentful
