### ISSUE TITLE
Clarify how to use an environment with a mock server

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1498]
Feedback from user: 

> When creating a Mock server, there is an option to select an existing Environment. However I can't figure out the purpose of this and can't see any effects either. A new environment is always created for the Mock. 

You can use an environment when you create a mock if you plan to use any environment variables in your mock (response, headers, url, etc). If not, then there's no need to use an environment. The default flow when you create a mock from the New+ button is to also create an environment - it's not really necessary, but you can see that an environment variable called `url` is used.

**Comment by SueSmith** [comment]
Commenting to keep open
