### ISSUE TITLE
Learning Center, Troubleshooting Monitors: monitor.getpostman.com redirects to workspaces

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1505]
**Article:**
https://learning.getpostman.com/docs/postman/monitors/troubleshooting_monitors#viewing-failed-monitors

**Issue:**
Link to **Monitors web view** in _Troubleshooting Monitors_ article points to: https://monitor.getpostman.com/

This URL redirects to https://go.postman.co/workspaces.

<img width="843" alt="screen shot 2019-01-15 at 10 25 28 am" src="https://user-images.githubusercontent.com/43283131/51201061-f4fbd900-18af-11e9-81e9-7af51daf4039.png">

**Comment by ArifPMan** [comment]
There is no way we could take the user directly to the monitors' view in the dashboard. The link takes the user to the dashboard view from where he must navigate to the monitor's tab to debug. I will provide a note in the doc so user can take steps explicitly to navigate to the monitors view.

**Comment by ArifPMan** [comment]
Hi, JP Storm,

If you agree with the viewpoint, I will close the GitHub issue.

thanks,
~Arif

**Comment by JP-from-Postman** [comment]
Hi Arif,

Makes sense to me, since we can't provide a direct link. Thank you!

**Comment by tristandenyer** [comment]
Closing based on comments above.
