### ISSUE TITLE
Last subtitle at the bottom of the page displays as markdown 

### ISSUE THREAD

**Issue by carolin-getpostman** [postmanlabs/postman-docs#1511]
https://learning.getpostman.com/docs/postman/monitors/monitoring_apis_websites/
<img width="707" alt="screen shot 2019-02-08 at 3 56 17 pm" src="https://user-images.githubusercontent.com/44679818/52512539-24092000-2bba-11e9-9d03-817e14def10b.png">

**Comment by ArifPMan** [comment]
Fixed the issue, will be merged soon
