### ISSUE TITLE
Outdated Document and Broken HTML: Activating Pro Trial Document 

### ISSUE THREAD

**Issue by labifrancis** [postmanlabs/postman-docs#1518]
The links in this documentation are broken and the documentation is outdated:
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/activating_trial/

**Comment by ArifPMan** [comment]
Assigned it to myself. Currently vetting through the tickets.

**Comment by tristandenyer** [comment]
Agree, this doc still talks about upgrading from a trial. https://github.com/postmanlabs/postman-docs/blob/master/v6/pro/managing_pro/upgrading_to_postman_pro_from_a_trial_team.md

**Comment by SueSmith** [comment]
Commenting to keep open
