### ISSUE TITLE
Misprint on pricing page 

### ISSUE THREAD

**Issue by I312andon** [postmanlabs/postman-docs#1519]
https://learning.getpostman.com/docs/postman_enterprise/purchasing_enterprise/

Small misprint when exploring the pricing page- ($2,520 compared to $11,340)

Thank you,

B

**Comment by ArifPMan** [comment]
It's confusing to me. Can you explain clearly what's the issue here?

**Comment by tristandenyer** [comment]
The only place on this page we mention "$2,520" is in the image at the bottom (for 10 users on Enterprise) : https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/purchasingenterprise4.png

By my math, ($18 x 12 months)(10) = $2,160 (which is the same price shown in image above it.)

@ArifPMan We may want to rethink showing prices in images.

**Comment by ArifPMan** [comment]
The whole purchase flow is documented which I believe is not necessary.
