### ISSUE TITLE
Detail how to delete a monitor

### ISSUE THREAD

**Issue by carolin-postman** [postmanlabs/postman-docs#1521]
While I understand that we can delete a monitor, is it possible to detail in the doc on how to delete a monitor?

I was trying to search for "delete a monitor" in the docs and found half of my answer. Is it possible to add more details _how to delete_ in the same response (or point me to a doc that directly answers my query? 

> Can I delete a Monitor?
You can delete a monitor at any time. Once deleted, all run history for the monitor is deleted too. If you want to retain the history, then you should pause the monitor instead of deleting it.

https://learning.getpostman.com/docs/postman/monitors/faqs_monitors/#can-i-delete-a-monitor

Thanks!

**Comment by carolin-getpostman** [comment]
I did find the direct link in google when searching "where to delete monitors postman". Led me to the community page where godfrzero posted the direct link (https://the.postman.co/team/elements?type=monitor )

<img width="766" alt="screen shot 2019-02-22 at 2 39 45 pm" src="https://user-images.githubusercontent.com/44679818/53275807-5aae6280-36b1-11e9-8a31-2194b59d89c4.png">

**Comment by ArifPMan** [comment]
Will look into this issue. I'm currently vetting through all the Github issues.

**Comment by SueSmith** [comment]
@claireriley wondering if this has been superseded by the monitoring updates you've been working through?

**Comment by claireriley** [comment]
@SueSmith nope—haven't redone the FAQs page yet and I think it makes sense to keep this one there. I'll self-assign and make sure it's included when I get to that page.

**Comment by SueSmith** [comment]
lol it was wishful thinking 🙃

**Comment by mark-anthony-postman** [comment]
See also: https://github.com/postmanlabs/postman-docs/issues/1784
