### ISSUE TITLE
Outdated redirect links for team monitoring page and markdown table is displayed awkwardly

### ISSUE THREAD

**Issue by carolin-getpostman** [postmanlabs/postman-docs#1522]
2 items - 

1. a. I intended on finding the page where I can view all of my monitors and the status but was led my workspace page (https://go.postman.co/workspaces?type=personal) from the embedded link:

> The **Monitors** page lists all your monitors (both team and private). 

https://learning.getpostman.com/docs/postman/monitors/viewing_monitor_results/
<img width="766" alt="screen shot 2019-02-22 at 2 39 45 pm" src="https://user-images.githubusercontent.com/44679818/53275378-be379080-36af-11e9-8251-f0fc8bfdcce1.png">

1. b. The same result appears in the bottom of the monitoring notification emails. 

2. In the image above, should the text underneath the image display in a table? 

-Carolin

**Comment by ArifPMan** [comment]
I assigned it to myself. Will address this shortly in the docs.

**Comment by ArifPMan** [comment]
Addressed the issue.
