### ISSUE TITLE
Clicking on a search result in the docs 404s

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1524]
<img width="1470" alt="screen shot 2019-02-25 at 4 44 19 pm" src="https://user-images.githubusercontent.com/17693714/53379096-07404c80-391d-11e9-9d06-482414501030.png">

Clicking on a search result directs to a page where the correct URL is repeated twice, resulting in 404.

<img width="1470" alt="screen shot 2019-02-25 at 4 46 12 pm" src="https://user-images.githubusercontent.com/17693714/53379153-42428000-391d-11e9-8d28-09e57bff0b48.png">

Deleting the first half of the URL allows the user to land on the correct page.

This used to only happen when the search was performed on the Home page of the Learning Center. Now it happens when the search is performed from any page.

**Comment by wsfuller** [comment]
One thing to note is that this is a functionality issue not a docs issue therefore an internal Jira ticket needs to be submitted and will not be followed up using the GitHub issue tracker. 

I've tested on Chrome 72, Firefox 65, Safari 12, Opera 58, Edge, Chrome on iOS, Safari on iOS and each browser is working as expected rendering results. My suggestion would be to run this site in an Incognito window and verify the issue persists. My assumption is there is a browser extension creating a problem rendering the URL which will need to be taken under advisement if that is the case. Assuming this is an extension issue I see several are installed and we'd need to determine which is the culprit to even begin an investigation and see if this is a wider spread issue

![github-issue-1524](https://user-images.githubusercontent.com/3144419/53422972-4f02ba80-3995-11e9-8895-82c3a53db96a.gif)
