### ISSUE TITLE
Interceptor extension -- make opening Note text more visible

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1532]
Seems to be some confusion that the Interceptor Extension is currently usable with the Native app:
https://github.com/postmanlabs/postman-app-support/issues/1667#issuecomment-459728614

This was also brought to light in a support ticket.

Low priority, but maybe we could make the opening disclaimer bolder/more visible:
`
Note: Interceptor feature is supported only in our Postman Chrome Apps and is not available in Postman Desktop Apps at the moment. Please let us know here if you'd like this feature to be made available in our Desktop Apps.
`
https://learning.getpostman.com/docs/postman/sending_api_requests/interceptor_extension/#___gatsby

**Comment by ArifPMan** [comment]
I assigned it to myself and will look into the issue.

**Comment by SueSmith** [comment]
Assuming this is no longer valid.
