### ISSUE TITLE
Learning Center - Managing your team: need updated screenshots/instructions for new invite UI

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1536]
Article:
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_team/#invites

**Issue:** the web dashboard has a new dialogue for inviting users, and selecting their roles (as shown below).
The Managing your team article on the Learning Center references the old dialog, which had separate sections for inviting Users and Support Accounts.

The current UI allows role selection within a single view:
<img width="543" alt="Screen Shot 2019-03-11 at 10 16 35 AM" src="https://user-images.githubusercontent.com/43283131/54145267-e54dcc00-43ea-11e9-80a6-e9ca12e42436.png">

**Comment by ArifPMan** [comment]
I assigned it to myself and will address it shortly.

**Comment by ArifPMan** [comment]
Addressed the issue. Review awaiting
