### ISSUE TITLE
Learning Center - Managing Your Team: Admin can't grant Billing role

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1537]
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_team/#member-roles

The above article contains an out-of-date description of the admin role and billing role, in that (even pre-RBAC) admins can only grant the `admin` or `user` role, and `billing` accounts are the only ones that can grant the `billing` role to others.

I'm guessing updated team management documentation based RBAC will negate the need for this specific article, so just flagging it here in case we keep this doc around for legacy coverage.

**Comment by ArifPMan** [comment]
I've assigned it to myself and looking into it.

**Comment by ArifPMan** [comment]
Updated the content, but I can't assign this to you for review in GitHub

**Comment by ArifPMan** [comment]
Addressed the issue. So, closing it.
