### ISSUE TITLE
Doc for custom domains doesn't include anything about CAA records.

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/postman-docs#1541]
https://learning.getpostman.com/docs/postman/api_documentation/adding_and_verifying_custom_domains/.

There's also a restriction on the CAA record - it should be a wildcard or allow LetsEncrypt. More details here - https://support.getpostman.com/hc/en-us/articles/360009030413-I-m-not-able-to-access-documentation-via-my-configured-custom-domain

**Comment by ArifPMan** [comment]
I assigned it to myself. Am looking into this.

**Comment by ArifPMan** [comment]
Addressed and closed.
