### ISSUE TITLE
Markdown Table skewed

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1543]
In this link, the table markdown formatting is skewed - https://learning.getpostman.com/docs/postman/collections/data_formats/#exporting-and-importing-postman-data

**Comment by ArifPMan** [comment]
Will fix this shortly

**Comment by loopDelicious** [comment]
Related to #1438

**Comment by tristandenyer** [comment]
While the data is now in a table structure, this could benefit from some additional styling. Considering issue closed but will make new issue for styling.
