### ISSUE TITLE
Leaving a team as the last member disables that team

### ISSUE THREAD

**Issue by labifrancis** [postmanlabs/postman-docs#1550]
Users should know that once they leave a team as the last member of that team, the team becomes disabled and can't be accessed again. 

The last user should transfer the collections of the team to a personal workspace or invite another member before leaving the team in order to preserve the collections.

**Comment by ArifPMan** [comment]
A user can't be in two teams today and this is a limitation. This limitation will be resolved. In this backdrop, we are not documenting this limitation. We don't want to discuss that in user guide. It may be fair to handle this the way it's done until the feature is enhanced.

**Comment by ArifPMan** [comment]
Let me know if I can close the issue.

**Comment by SueSmith** [comment]
@labifrancis can I check if this issue is still valid? 😬

**Comment by labifrancis** [comment]
Considering Arif's reply, I don't think it's valid @SueSmith 😄

**Comment by SueSmith** [comment]
@labifrancis great thanks I will just go ahead and close it.. 🙏
