### ISSUE TITLE
Update Templates documentation

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1552]
Update the content in the Templates section or screenshot to reference more than just the Dev and DevOps categories.

This is in preparation for the May Mashup promotion for templates.

**Comment by ArifPMan** [comment]
I need more information on this issue to scope out the work and plan the delivery.

**Comment by loopDelicious** [comment]
The template documentation currently references two categories (Dev and DevOps). Since the time this documentation was originally published, more categories have been added.  

https://learning.getpostman.com/docs/postman/launching_postman/newbutton/#templates

Update the screenshot and copy so that we can see all the categories instead of just "Dev" and "DevOps". 

<img width="1004" alt="Screen Shot 2019-04-08 at 7 56 49 AM" src="https://user-images.githubusercontent.com/17693714/55736066-765a9780-59d7-11e9-889d-26e4a2b93708.png">

**Comment by ArifPMan** [comment]
Updated the doc and assigned the PR to Joyce for review.

**Comment by ArifPMan** [comment]
Done and merged. Closing the issue.
