### ISSUE TITLE
Dead link in New button page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1553]
This in-page link doesn't work. Might be hardcoded to direct to v6. Consider doing a find all for instances of `v6`. `https://learning.getpostman.com/docs/v6/postman/launching_postman/newbutton#templates`<img width="1541" alt="Screen Shot 2019-04-02 at 4 55 06 PM" src="https://user-images.githubusercontent.com/17693714/55443629-425f1c80-5568-11e9-9f92-461b86fddaed.png">

**Comment by ArifPMan** [comment]
This falls in my bucket so I'm assigning it to self. Let me know if anyone has concerns over this.

**Comment by ArifPMan** [comment]
I started looking into this. A global find and replace for v6 is not the solution. There are plenty of links with v6 hardcoded in the path and still work fine. I replaced many of them already as per your request and suddenly realized to test it. Many links with v6 hardcoded in it actually work.  Now, I'm reverting to the old links. 

https://learning.getpostman.com/docs/postman/collection_runs/integration_with_jenkins/

**Comment by ArifPMan** [comment]
Updated the docs and submitted the PR for merge but still don't see the fix due to contentful issue I guess. Once someone manually pushes these changes, it may reflect in the prod docs.

**Comment by tristandenyer** [comment]
The issue now is a missing trailing slash.
Current link is `https://learning.getpostman.com/docs/postman/launching_postman/newbutton#templates`

Working link should be `https://learning.getpostman.com/docs/postman/launching_postman/newbutton/#templates`

**Comment by tristandenyer** [comment]
PR is merged and changes verified in Production. Closing.
