### ISSUE TITLE
No page for leaving a team

### ISSUE THREAD

**Issue by anudeepmedicharla** [postmanlabs/postman-docs#1554]
There's no doc right now that explains how to leave a team.

**Comment by ArifPMan** [comment]
I assigned it to self. Will be looking into this.

**Comment by ArifPMan** [comment]
I suggest to not document this at all. It's a limitation today that a user can't be part of two teams. Now, if I have to document how to leave a team, then I have to talk about this limitation. IMHO, it's better to keep the docs status quo. Let me know if you have a difference of opinion.

**Comment by anudeepmedicharla** [comment]
Your call 😄. I guess @preethammavin is on the same page.

**Comment by ArifPMan** [comment]
I will discuss this with @preethammavin. @preethammavin please let me know if you agree with this approach.

**Comment by ArifPMan** [comment]
Closing this issue as we don't want to document limitations in user guide.

**Comment by stcalica** [comment]
This may want to be reopened and describe some of the limitations because we get a lot of support tickets asking about what happened to their collections.
