### ISSUE TITLE
Creating a new page with sidebar elements

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1565]
When you're creating a new page, there's a sidebar on the right-side of the page that lists pre-requisites, additional resources, and next steps.

An example is this page here: 
<img width="1532" alt="Screen Shot 2019-04-11 at 10 20 16 AM" src="https://user-images.githubusercontent.com/17693714/55977470-bd4cc500-5c43-11e9-9f0c-a95de56e8f72.png">

https://learning.getpostman.com/docs/postman/environments_and_globals/variables

The following page was created without that associated information. So if someone was to deep link to that page, they may not see what the pre-requisite concepts are for this page. They will not see additional resources that clarify this content. And they would not see next steps to follow once they master this content.

<img width="1532" alt="Screen Shot 2019-04-11 at 10 21 27 AM" src="https://user-images.githubusercontent.com/17693714/55977497-d2c1ef00-5c43-11e9-8eff-5c7b72f1fddd.png">

https://learning.getpostman.com/docs/postman/environments_and_globals/sessions

You can go into Contentful to set up the related pages for this sidebar

**Comment by ArifPMan** [comment]
I think this should be assigned to the right person as I don't work on 'Contentful'.

**Comment by ArifPMan** [comment]
I think @tristandenyer knows whom to assign this.

**Comment by ArifPMan** [comment]
There are several chapters like this that need related pages to be associated in the sidebar. New chapter 'Design and Develop APIs' would need this. So does 'Notifications', 'Find and Replace', 'Customizing Postman', 'Commenting on Collections', 'Working with Tabs', 'Collaboration' and etc.

**Comment by tristandenyer** [comment]
The right sidebar is added and edited by Marketing team in Contentful.

**Comment by tristandenyer** [comment]
Fixed in PR #1957 1957
