### ISSUE TITLE
Add descriptions and missing methods for pm.globals, .environment, .variables

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1566]
https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmglobals
Missing description of behavior for methods.
Example: pm.globals.clear() wipes all global variables in workspace.
Example. pm.globals.unset() removes a specific global variable by name

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmenvironment
Example: pm.environment.clear() wipes all variables in the active environment.
Example. pm.environment.unset() removes a specific variable in current environment by name

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmvariables
Examples of missing methods:
pm.variables.set()
pm.variables.has()

There are others. Methods in pm.variables also have different behavior than .environment and .globals, which isn't explained on this page.

Example. pm.variables.set() sets a variable in the local scope, but pm.variables.get() returns a variable value by name in the _nearest_ scope (according to our variable scopes hierarchy).

**Comment by kaustavdm** [comment]
This should be addressed by #1801 once it goes to production.
