### ISSUE TITLE
Update webhooks coming soon page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1568]
Consider removing the `coming soon` tag on this page, and linking to the Custom Webhooks page under Integrations.

https://learning.getpostman.com/docs/postman/monitors/integrations_for_alerts/#webhooks-coming-soon

**Comment by tristandenyer** [comment]
Custom Webhooks URL is https://learning.getpostman.com/docs/postman_pro/integrations/custom_webhooks/

Will be adding link to Custom Webhooks in left nav (Postman Pro > Integrations > Custom Webhooks) this release.

**Comment by preethammavin** [comment]
@loopDelicious @tristandenyer The coming soon would stay for now, till we address all the required feature mentioned there, will close the issue for now. As the custom webhook currently created is for outgoing webhooks from Postman, though which users can pipe in events from the elements in Postman to their own platform.
