### ISSUE TITLE
New params button location

### ISSUE THREAD

**Issue by labifrancis** [postmanlabs/postman-docs#1570]
In this [doc ](https://learning.getpostman.com/docs/postman/sending_api_requests/requests/)on request, the screenshot shows that the params button is next to the send button but in the latest version, the params button is next to the authorization header. 
Old:
![image](https://user-images.githubusercontent.com/10200603/56349263-15457780-61c0-11e9-80c6-272d8c3300c2.png)

New:

![image](https://user-images.githubusercontent.com/10200603/56349173-e8916000-61bf-11e9-89fd-4e4124371d6e.png)

**Comment by ArifPMan** [comment]
Closing the issue.
