### ISSUE TITLE
Inconsistent image on documentation

### ISSUE THREAD

**Issue by labifrancis** [postmanlabs/postman-docs#1575]
When you click on the image under "Variable Scopes"  in this [documentation](https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#variable-scopes), It opens a different image on another tab. The positions for "Data" and "Local" are not consistent. 

Original Image:
![image](https://user-images.githubusercontent.com/10200603/56808529-a2747600-6829-11e9-9d3c-78757af58a10.png)

After clicking on the above image:
![image](https://user-images.githubusercontent.com/10200603/56808625-d64f9b80-6829-11e9-9e09-1c59d9142e87.png)

**Comment by ArifPMan** [comment]
Addressed the issue, so closing it.
