### ISSUE TITLE
Clarify commenting

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1576]
https://learning.getpostman.com/docs/postman/collections/commenting_on_collections

> Note: If someone comments on a private collection that you don’t have access for, Postman sends a notification to you. However, you can’t read the comment until the collection or the request is shared with you.

Consider updating this by adding the bolded clarification: "If someone comments on a private collection **and tags you**, Postman sends you a notification...."

**Comment by tristandenyer** [comment]
merged and in verified in prod.
