### ISSUE TITLE
Support-only accounts doc not present

### ISSUE THREAD

**Issue by harshachelle** [postmanlabs/postman-docs#1582]
The invite users option on the web dashboard gives the messaging to add both paid slots and support-only accounts. 
But the link there- `Learn more about support roles` redirects to https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_team/ which does not has any content about Support-only account.
![Support-only docs github issue](https://user-images.githubusercontent.com/12132423/57121988-7c565500-6d98-11e9-8b6c-dc01cd414025.png)

Need to add a learning center doc for support-only accounts or link them to this blog post that talks about it (https://blog.getpostman.com/2018/03/31/support-only-accounts-for-postman-pro-teams/)

**Comment by arlemi** [comment]
There is now some information about support roles on that page:
> Note that teams may have two support accounts at no additional cost. Support accounts are defined as members with only admin and/or billing roles.
