### ISSUE TITLE
Modify GitHub integration doc 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#1583]
_Filed by Product Support_

We are seeing many issues around the GitHub integration feature - https://github.com/postmanlabs/postman-app-support/issues/6105 

We managed to identify potential causes that need to be verified and actions to take whenever the integration doesn't sync the content to the GitHub repository.

- The GitHub integration is added to the same workspace as the content that needs to be pushed to the GitHub repo.
- The right option has been chosen between Backup your Postman Collections to GitHub and Backup your Postman Collections to GitHub on a custom domain when setting up the integration.
- Initialize the repo with a Readme.md. Check the box Initialize this repository with a README and then configure a new integration on it.
- The scopes user and repo are selected when creating the access token on GitHub.
- The branch specified in the setup is existing on Github. Note: the integration doesn't create one if the branch doesn't exist.
- The enterprise version of GitHub is on-prem / self-hosted > can be a firewall issue (GitHub issue #5741)
- The user has enough permissions to push to that branch.
- Reinstall the integration.

The above troubleshooting list should be added to the GitHub integration doc - https://learning.getpostman.com/docs/postman-pro/integrations/github/

**Comment by SueSmith** [comment]
Commenting to keep open
