### ISSUE TITLE
There is no "Sample Use case" section on this page

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1587]
On https://learning.getpostman.com/docs/postman/working_with_apis/introduction_to_apis/ there is a link at the top for Sample Use Case, but links to section that is not there on the page.

<img width="882" alt="Screen Shot 2019-05-15 at 1 13 02 PM" src="https://user-images.githubusercontent.com/4358288/57806099-4d829c00-7713-11e9-9fbc-4e5c884b7a9d.png">

**Comment by a85** [comment]
Also, "APIs" instead of "apis"

**Comment by a85** [comment]
PR here: https://github.com/postmanlabs/postman-docs/pull/1589
