### ISSUE TITLE
"Installation and updates" page screenshots are out of date

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1588]
On this page https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/ the first screenshot is out of date, and the second screenshot is using a "beta" screenshot. Recommend updating both to use the current Production vies for both of these.

**** Rest of screenshots may need updating as well!

First link to "apps page" needs updating as well:
— change to "downloads page"
— use updated link: https://www.getpostman.com/downloads/

<img width="1042" alt="Screen Shot 2019-05-15 at 1 14 30 PM" src="https://user-images.githubusercontent.com/4358288/57806280-a5b99e00-7713-11e9-8147-af5ffaca03ee.png">

**Comment by ArifPMan** [comment]
Done
