### ISSUE TITLE
Docs in master branch not reflecting in production

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1597]
ajv doc updates made in January - this is the PR https://github.com/postmanlabs/postman-docs/pull/1487 do not reflect in production. Get this fixed.

**Comment by tristandenyer** [comment]
This is fixed. 

I checked all the changes in the PR and noticed only one of the 4 files changed did not have its edits reflected in Production. Looking to the pipeline, I noticed Contentful had the doc in 'draft' mode AND complaining it was a duplicate. I found there were 9 other records for the same page, all in draft mode except one. This is what was keeping this page from updating.

I deleted all drafts and updated the content in Contentful to match GitHub and redeployed the site. Page has been updated, please verify: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/

<img width="457" alt="Screen Shot 2019-05-17 at 12 53 36 PM" src="https://user-images.githubusercontent.com/4358288/57952830-2f4ba600-78a3-11e9-8c0f-a4835bad37d8.png">

**Comment by ArifPMan** [comment]
Great work @tristandenyer
