### ISSUE TITLE
404 Link to Managing API from Managing APIs to Managing API Workflow

### ISSUE THREAD

**Issue by CWHamilton** [postmanlabs/postman-docs#1598]
1. Access [Managing APIs](https://learning.getpostman.com/docs/postman/design_and_develop_apis/managing_apis/) documentation
2. Scroll to the bottom
3. Select 'Managing API Workflow' link
- It will bring you to _/design_and_develop_apis/managing-api-workflow_
-  It should bring you to _/design_and_develop_apis/the_api_workflow_

Same goes for
Versioning an API
Introduction to APIs

**Comment by a85** [comment]
@tristandenyer @ArifPMan This slipped through. Can you please fix it asap?
@CWHamilton Thanks for reporting!

**Comment by ArifPMan** [comment]
After the Design and Develop APIs renaming, the directory structure for links changed. The new directory was updated along with the following chapter name too. For instance, Managing API workflow. The chapter 'the-api-workflow' had an underscore originally, but got replaced with a hyphen. I updated all the links. They should be working now. Currently, most of the external links don't work.

@a85 - Fixed the issue. @CWHamilton - Please validate this after the PR is pushed by @tristandenyer and then comment here so I can close the issue.
