### ISSUE TITLE
Create an Accounts-related FAQ

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1606]
Sanjeev: we're getting a ton of account purchasing/adding/removing questions lately. what's the best way to address this? success and support can collate all the recent tickets around this as data points - but what after that. my feeling is this needs a step back and a look at overall flows - addressing the tickets individually won't get us there.

**Comment by arlemi** [comment]
We now have a whole section dedicated to SSO: https://learning.postman.com/docs/administration/sso/intro-sso/

**Comment by jkonrath-postman** [comment]
This has been moved internally (TW-4) and is being addressed there.
