### ISSUE TITLE
Resolve Markdown Cramdown Table Inconsistencies

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1611]

**Comment by tristandenyer** [comment]
@ArifPMan This Issue needs more details: where are you seeing inconsistencies? And what is your acceptance criteria?

**Comment by ArifPMan** [comment]
@tristandenyer. This table is inconsistent. In Markdown preview this shows fine but does not render properly on LC. Here's the link - https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/#___gatsby...

**Comment by SueSmith** [comment]
Assuming this is no longer valid since LC migration, closing for now.
