### ISSUE TITLE
The Postman Docs ToC is Disorganised

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1614]
The sequence of the ToC for Postman docs on LC is not structured properly. It looks haphazard. After the chapter 'Launching Postman', the ToC currently has 'Customizing Postman', and 'Find and Replace' and so on. This entire sequence must be discussed, revised, restructured to reflect the workflow of the tool.

**Comment by SueSmith** [comment]
This will be addressed by upcoming changes to the docs IA so closing for now.
