### ISSUE TITLE
Publishing to API Network link points to wrong page

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1616]
Article: https://learning.getpostman.com/docs/postman/launching_postman/newbutton/#api-network

Text with link (**bolded**):
> If you're an API publisher, you can share your API documentation with your users and the rest of the Postman community by **publishing your documentation to the Postman API Network**.

Current link: https://learning.getpostman.com/docs/postman/launching_postman/newbutton/

Not 100% sure what the correct link should be, but maybe it's:
https://learning.getpostman.com/docs/postman/api_documentation/publishing_public_docs/#add-to-api-network

**Comment by ArifPMan** [comment]
@JP-from-Postman Could you please review this? The fix has been deployed. If you are okay with the fix, please close the issue.

**Comment by JP-from-Postman** [comment]
@ArifPMan LGTM. Closing.
