### ISSUE TITLE
"Activity" feed has changed to "Changelog"

### ISSUE THREAD

**Issue by labifrancis** [postmanlabs/postman-docs#1620]
In this [documentation](https://learning.getpostman.com/docs/postman/workspaces/activity_feed_and_restoring_collections/) on restoring collections, the "Activity" has changed to "Changelogs"

**Former:**
![Annotation on 2019-4-4 (1)](https://user-images.githubusercontent.com/10200603/58247361-6281af80-7d51-11e9-8d16-f93e0e4a8f8c.png)

**Current**
![Annotation on 2019-4-4](https://user-images.githubusercontent.com/10200603/58247032-94464680-7d50-11e9-805a-504407b8dd90.png)

**Comment by SueSmith** [comment]
Adding a screengrab for updated doc...
<img width="1439" alt="collection-changelog" src="https://user-images.githubusercontent.com/6666370/68310435-ea613900-00a7-11ea-8ceb-af601ec5d502.png">

**Comment by SueSmith** [comment]
transferring imgs to s3, will update the pr
