### ISSUE TITLE
The learn more link for debug redirects to Postman installation & update guide. 

### ISSUE THREAD

**Issue by aliasgarlabs** [postmanlabs/postman-docs#1637]
Information about Postman products is shown on this [page](https://www.getpostman.com/tools#debug) with links to more detail documentation of these products to learn more.

However, the learn more link for **debug** redirects to this [page](https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/) which is a guide for Postman installation & updates. 

Suggested link for redirection: https://learning.getpostman.com/docs/postman/scripts/intro_to_scripts.

**Comment by ArifPMan** [comment]
@tristandenyer I think this should go to the website folks. Can you please assign this issue to them?

**Comment by tristandenyer** [comment]
This page is already scheduled for redesign and updating. Can close when complete and deployed.

**Comment by DannyDainton** [comment]
@aliasgarlabs / @tristandenyer 

I know this was a while ago but it looks like that page is going to @aliasgarlabs suggested link now - Do you think we can close this issue?

**Comment by tristandenyer** [comment]
This appears to be fixed. Closing.
