### ISSUE TITLE
Hyperlink to documentation of changelog is wrong

### ISSUE THREAD

**Issue by harshachelle** [postmanlabs/postman-docs#1641]
**Issue description:**
The hyperlink to the documentation page of _changelog_ currently is pointing to the restoring collections page (https://learning.getpostman.com/docs/postman/workspaces/activity_feed_and_restoring_collections/) which is wrong.

**Screenshot for reference:**
<img width="1146" alt="Screenshot 2019-05-31 at 3 14 41 PM" src="https://user-images.githubusercontent.com/12132423/58699095-55506a80-83ba-11e9-9aca-7d60b6a34e6a.png">

**Ideal behaviour:**
It should ideally point to this- https://learning.getpostman.com/docs/postman/design_and_develop_apis/versioning_an_api/#adding-version-tag-to-a-collection

**Comment by tristandenyer** [comment]
This is an issue with the app. Recommending it be moved to https://github.com/postmanlabs/postman-app-support/issues

**Comment by SueSmith** [comment]
Closing because this appears to have been fixed - app link goes to changelog/activity page now.
