### ISSUE TITLE
Broken link in Postman pro page

### ISSUE THREAD

**Issue by Kurmavathar** [postmanlabs/postman-docs#1642]
The link for Postman API within: https://learning.getpostman.com/docs/postman_pro/what_is_pro/ is broken.
![Postman API](https://user-images.githubusercontent.com/47771757/58700337-5d5dd980-83bd-11e9-99e1-ff0a5732d51f.png)

Additional context: https://github.com/postmanlabs/postman-docs/issues/1636#issue-449094744

**Comment by tristandenyer** [comment]
This has been fixed in #1644
