### ISSUE TITLE
Broken Link on Capturing HTTP requests Page

### ISSUE THREAD

**Issue by taylorjdawson** [postmanlabs/postman-docs#1646]
**Describe the bug**
There is a broken link on the [Capturing HTTP requests](https://learning.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests/) page.

**To Reproduce**
1. Go to [Capturing HTTP requests](https://learning.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests/#connect-to-proxy-for-target-devices) page.
2. Scroll down to the bottom of the page.
3. Under the **Connect to proxy for target devices** section click **macOS** link.
4. See 404

**Expected behavior**
You click macOS link and it goes to proxy config tutorial by Apple.

**Fix**
Use this link instead!
https://support.apple.com/en-gb/guide/mac-help/mchlp2591/mac

**Comment by tristandenyer** [comment]
PR made.

Thank you @taylorjdawson for catching this!

**Comment by tristandenyer** [comment]
This has been fixed in #1647
