### ISSUE TITLE
Newman with Docker needs correction

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1652]
A user suggested a correction: 

https://community.getpostman.com/t/newman-with-docker-needs-correction/4027

**Comment by tristandenyer** [comment]
Let's make sure we circle back to the original poster on the forum when this is merged.

**Comment by SueSmith** [comment]
Commenting to keep open

**Comment by DannyDainton** [comment]
@SueSmith The Docker command on this page runs fine, that edit isn't actually needed - not sure if you wanted to close this or not :) 

<img width="830" alt="Screenshot 2020-02-27 at 21 42 36" src="https://user-images.githubusercontent.com/17089546/75489441-20556080-59aa-11ea-88b3-1680b1dd6092.png">
