### ISSUE TITLE
Postman API & Mocks – Add documentation on rate limiting

### ISSUE THREAD

**Issue by chrisdeso** [postmanlabs/postman-docs#1655]
There's a rate limit of **60 requests per minute** but that isn't documented outside of the Postman API documentation linked below.

- https://docs.api.getpostman.com/?version=latest#rate-limits

The lack of documentation around rate limiting (and how it extends to mocks) can cause confusion when the error message that's seen is the same as the usage limit error messaging – `429`.

**Comment by chrisdeso** [comment]
This can be closed if the official API documentation is the right place for information around rate limiting

**Comment by SueSmith** [comment]
Commenting to keep open - we should add this elsewhere if it's causing confusion..

**Comment by arlemi** [comment]
There is now a Rate Limits section on the LC for the Postman API: https://learning.postman.com/docs/postman/postman-api/intro-api/#rate-limits

@chrisdeso Can you explain what you meant by "and how it extends to mocks"?

**Comment by loopDelicious** [comment]
@chrisdeso anything else we should add to the new rate limits section? Or should we close this issue?

**Comment by chrisdeso** [comment]
@loopDelicious @arlemi The new rate limits section is beautiful! Closing this out, thanks folks!
