### ISSUE TITLE
Wrong example image on a page.

### ISSUE THREAD

**Issue by abhanshgiri21** [postmanlabs/postman-docs#1656]
The example image on [this](https://learning.getpostman.com/docs/postman/scripts/pre_request_scripts/) is wrong. Please see the image below to get an idea of what is wrong. The example for pre-request script setting a timeStampHeader is wrong, just a misplaces round bracket.
![Screenshot 2019-06-20 at 4 26 00 PM](https://user-images.githubusercontent.com/20536298/59845090-20608380-937a-11e9-83d8-9043b2dd0b7c.png)

**Comment by ArifPMan** [comment]
Addressed the issue, closing the ticket
