### ISSUE TITLE
Update links in the docs that talk about creating and consuming templates and api network 

### ISSUE THREAD

**Issue by ArifPMan** [postmanlabs/postman-docs#1662]

**Comment by tristandenyer** [comment]
@ArifPMan can you provide URLs to these pages that need updating?

**Comment by ArifPMan** [comment]
@tristandenyer - These are the ones that you published on #docs recently for API Network and Template submission guidelines under `Postman for Publishers` section.

**Comment by SueSmith** [comment]
Can I check what urls are wrong here so we can fix?

**Comment by SueSmith** [comment]
Not seeing any links that don't work here so will just close for now and we'll catch anything else during redrafts.
