### ISSUE TITLE
Encompass APIs in RBAC doc 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#1668]
The documentation [Roles and Permissions](https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/) describes permissions and roles for Workspaces and Collections but doesn't encompass APIs. 

Support situation - A user didn't understand why he couldn't delete an API and so didn't know that he had the `Viewer` role on the API while he needs the `Editor` one to be able to delete it.

**Comment by SueSmith** [comment]
I think this is fixed as of #2217 but please re-open if not!
