### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Swapnil-getpostman** [postmanlabs/postman-docs#1670]
After clicking on the "Support Center" link on the below page, gives 404 error.
[https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs ](https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs )
 
Screenshot:
<img width="547" alt="Screenshot 2019-06-28 at 2 51 46 PM" src="https://user-images.githubusercontent.com/52168965/60332389-5aeaa180-99b4-11e9-8ce5-36fcc059fd62.png">

Additional context: https://github.com/postmanlabs/postman-docs/issues/1636#issue-449094744

**Comment by tristandenyer** [comment]
Fixed with PR #1673
