### ISSUE TITLE
Broken link in Requests page

### ISSUE THREAD

**Issue by Kurmavathar** [postmanlabs/postman-docs#1671]
The link to "[GraphQL](https://learning.getpostman.com/docs/postman/sending_api_requests/graphql/)" within: https://learning.getpostman.com/docs/postman/sending_api_requests/requests/#graphql 
is broken.

<img width="548" alt="Screen Shot 2019-06-28 at 4 20 53 PM" src="https://user-images.githubusercontent.com/47771757/60337453-bb7fdb80-99c0-11e9-8782-1941a5bd7c80.png">

Additional context: https://github.com/postmanlabs/postman-docs/issues/1636#issue-449094744

**Comment by tristandenyer** [comment]
Fixed in PR #1672
