### ISSUE TITLE
Activating your Pro trial page needs to be deleted

### ISSUE THREAD

**Issue by harshachelle** [postmanlabs/postman-docs#1675]
**Describe the bug**
The below link needs to be removed as there's no concept of activating a trial anymore.
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/activating_trial/

**To Reproduce**
Visit- https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/activating_trial/

**Expected behavior**
We should either
1) create new documentation explaining that there's no trial concept anymore and link them to pricing page
2) redirect the user to a pricing page

**Comment by tristandenyer** [comment]
Yes, a few things:
— this page is still accessible from a direct link
— there are no docs in LC that link to this page
— external sites may still link here
— this page is no longer linked to from the left nav (basically orphaned)

TODOS for this issue:
1) remove page from GitHub and Contentful
2) add redirect to https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/purchasing_postman_pro/
3) delete 2 image assets from S3

**Comment by tristandenyer** [comment]
Related: this page needs to be updated/removed too. Still says 'trial'https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/upgrading_to_pro/

**Comment by ch264** [comment]
@kaustavdm it looks like the file 'activating_trial'  https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/activating_trial/ is in the v5 folder and was probably not affected by the doc cleansing effort. This file is not linked in the left nav bar.

The file 'upgrading_to_pro' https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/upgrading_to_pro/
is in v6 and linked in the left nav bar. 

What is the content plan for each of these files?

**Comment by tristandenyer** [comment]
@kaustavdm What would you like to do about this?

**Comment by kaustavdm** [comment]
It is possibly safest to add a message near the top of the page saying this is outdated docs. Else, we can remove the file and add a redirect to https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/upgrading_to_pro/.
