### ISSUE TITLE
Need to create a new learning center article for bootcamp

### ISSUE THREAD

**Issue by harsh-reality** [postmanlabs/postman-docs#1676]
We currently don't have any documentation about bootcamp except for the blog post that I'm linking below: https://blog.getpostman.com/2019/01/11/in-app-postman-lessons/

We should create a detailed documentation page for bootcamp as this is one of the very frequently used feature by users

**Comment by loopDelicious** [comment]
Related to #2620

**Comment by jkonrath-postman** [comment]
Closing this, and we'll address it in #2620
