### ISSUE TITLE
Request to add Browse <> Build mode into documentation

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#1677]
The documentation for toggling modes between Build and Browse in the app. It can be added on the Status bar on Navigating Postman page: https://learning.getpostman.com/docs/postman/launching_postman/navigating_postman/#status-bar

Screenshot:
![ToggleToBuild](https://user-images.githubusercontent.com/47771757/60577348-ce1d5a80-9d9c-11e9-85c2-b73d766d88c9.png)

Additional context:
https://community.getpostman.com/t/apis-now-missing-in-your-beta-version-and-collections-now-open-in-chrome-not-in-postman-app/6197

**Comment by loopDelicious** [comment]
@Raj-postman this content has been added to this page: https://learning.postman.com/docs/getting-started/navigating-postman/

Feel free to reopen if you have more to add.

**Comment by Raj-postman** [comment]
Thank you @loopDelicious 💯
