### ISSUE TITLE
Either file is is wrong folder, or doc is mis-categorized on site

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1678]
When publishing this doc: https://github.com/postmanlabs/postman-docs/blob/master/v6/pro/pro_api/intro_api.md I noticed that it lives under the `/pro/pro_api/` folder in GitHub, but on the site is at https://learning.getpostman.com/docs/postman/postman_api/intro_api

Where should this doc live on the site? `/postman/postman_api/` OR `/postman_pro/postman_api/`?

The file should live in the same place in gitHub. So, one of these (file or page) needs to move.

<img width="545" alt="Screen Shot 2019-07-04 at 2 25 54 AM" src="https://user-images.githubusercontent.com/4358288/60656017-95fd3280-9e03-11e9-8197-39c765a27461.png">

**Comment by SueSmith** [comment]
Assuming this is fixed by learning center migration and we can close..? @tristandenyer
