### ISSUE TITLE
Add callback URL to OAuth 2 instructions on Learning Center

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1679]
Doc: https://learning.getpostman.com/docs/postman/sending_api_requests/authorization/#oauth-20

Leaving the callback URL empty may not be appropriate for all use-cases. The following URL can be used where required: `https://www.getpostman.com/oauth2/callback`

Would be good to enumerate some examples of where this may be required (e.g. Azure Directory Services).

**Comment by SueSmith** [comment]
I've added this url to PR #1962 but haven't mentioned any specific services yet, if there are known examples other than Azure Directory Services I can add them whenever..
