### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by Swapnil-getpostman** [postmanlabs/postman-docs#1680]
After clicking on [Postman API](https://learning.getpostman.com/docs/postman/monitors/intro_monitors#variables), (Postman Learning Centre -> Monitors -> Intro to monitors) It gives a 404 Error.
[Here is the broken link](https://learning.getpostman.com/docs/postman_pro/pro_api/intro_api)
Below is the attached screenshot.

<img width="610" alt="Screenshot 2019-07-07 at 4 21 43 PM" src="https://user-images.githubusercontent.com/52168965/60767313-ff1ac980-a0d3-11e9-806b-b2020630717a.png">

**Additional comment:** https://github.com/postmanlabs/postman-docs/issues/1636#issue-449094744

**Comment by ArifPMan** [comment]
Closing the issue as it's addressed by tristan.

**Comment by tristandenyer** [comment]
Thanks for closing!
