### ISSUE TITLE
Request to remove environment templates from docs

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#1697]
As environment templates have been disabled and are no longer present, used to exist before workspaces as a feature called "Team Library". Please remove this particular section from the following document:

https://learning.getpostman.com/docs/postman/team_library/sharing/#sharing-environments

Screenshot:

<img width="717" alt="Screen Shot 2019-07-16 at 12 26 47 PM" src="https://user-images.githubusercontent.com/47771757/61272558-10935e00-a7c5-11e9-9625-2fba3edb7d3f.png">

**Comment by claireriley** [comment]
@kaustavdm how do we treat issues like this, where a feature did exist but was removed? The page is still accessible when you search "Sharing" and is the first suggestion, so I assume a number of people continue to navigate here.
