### ISSUE TITLE
Screenshots need to be edited

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1700]
On the "Setting up custom SAML in Okta" page ( https://learning.getpostman.com/docs/postman_enterprise/sso/saml_okta/ ) the screenshots are full desktop screenshots. We should not be showing anythign in a screenshot that is not pertinent to the topic. And—based on our documentation and product—we likely will never need to show the dock, browser tabs and download bar, as is seen in these screenshots.

Please edit out all content that is not just the webpage. You can see proper examples near the middle and bottom of page (step 9).

Also, strongly recommend all screenshots be optimized for web via ImageOptim (https://imageoptim.com/mac) before being uploaded to S3.

**Comment by ArifPMan** [comment]
Done.
