### ISSUE TITLE
GitHub/GitLab/APIMatic: branch must already exist

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1705]
Docs:
https://learning.getpostman.com/docs/postman_pro/integrations/apimatic/#___gatsby
https://learning.getpostman.com/docs/postman_pro/integrations/gitlab
https://learning.getpostman.com/docs/postman_pro/integrations/github

Request:
Add a note that the GitHub branch specified must already exist, or the integration will not sync.

**Comment by JP-from-Postman** [comment]
Bumping to keep this open, since it looks like it's been set to stale and will close soon.

**Comment by SueSmith** [comment]
Commenting to keep open
