### ISSUE TITLE
Broken Link - 404 error

### ISSUE THREAD

**Issue by Swapnil-getpostman** [postmanlabs/postman-docs#1706]
After clicking on the support center for the below image, it throws 404 error.
[Here](https://learning.getpostman.com/docs/postman/sending_api_requests/troubleshooting_api_requests/#invalid-responses) is the link to navigate below screenshot.

<img width="691" alt="Screenshot 2019-07-19 at 11 36 40 AM" src="https://user-images.githubusercontent.com/52168965/61513246-22ba0a00-aa1a-11e9-8c05-3e74be5d6a79.png">

And [Here](https://learning.getpostman.com/docs/postman/sending_api_requests/troubleshooting_api_requests/%7B%7Bhttps://support.getpostman.com/hc%7D%7D) is the broken link.

Additional context: #1636 (comment)

**Comment by ch264** [comment]
Link is fixed and PR is merged
