### ISSUE TITLE
Add contribution documentation for this repository

### ISSUE THREAD

**Issue by kaustavdm** [postmanlabs/postman-docs#1712]
Add clear instructions in a `CONTRIBUTING.md` file highlighting how any contributor should contribute to this repository. See [`newman`'s CONTRIBUTING.md](https://github.com/postmanlabs/newman/blob/develop/.github/CONTRIBUTING.md) for inspiration.

**Comment by SueSmith** [comment]
Think we're good to close this for now? Am sure we can continue to enhance but thinking we have the basics covered in the current contrib guide..
