### ISSUE TITLE
Broken Link - Dynamic Variables

### ISSUE THREAD

**Issue by kevin-postman** [postmanlabs/postman-docs#1718]
https://learning.getpostman.com/docs/postman/environments_and_globals/variables_list should show list of dynamic variables. Currently 404.  Linked from here: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/

**Comment by kaustavdm** [comment]
We probably should link to the section on Sandbox API Reference instead. #1717 will add all of the variables.
