### ISSUE TITLE
Changes to Postman Sandbox page are not reflected in production

### ISSUE THREAD

**Issue by kaustavdm** [postmanlabs/postman-docs#1722]
The [Postman Sandbox](https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/) page is still outdated from its [corresponding content](https://github.com/postmanlabs/postman-docs/blob/master/v6/postman/scripts/postman_sandbox.md) in the `master` branch. There were changes introduced in #1717 and #1715.

**Comment by ch264** [comment]
#1717 has been fixed and in production: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference

**Comment by ch264** [comment]
#1715  is in production: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/
(hard reload page to verify)

**Comment by tristandenyer** [comment]
All issues fixed, closing.
