### ISSUE TITLE
SSO Docs - Add Flow for 1st time Login using iDP credentials

### ISSUE THREAD

**Issue by aamir-ahmed** [postmanlabs/postman-docs#1724]
@ArifPMan, My response on July 22nd for: https://postman.zendesk.com/agent/tickets/35236 as reference.

**Comment by ArifPMan** [comment]
@aamir-ahmed Please review the updated docs

**Comment by SueSmith** [comment]
If this issue is still valid could someone provide specifics here so that we can see the detail without access to zendesk..? 🙏

**Comment by SueSmith** [comment]
Sue to refer to slack convo for more context.
