### ISSUE TITLE
scan .md file for linter issues

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1738]
Ticket for training session.

https://github.com/postmanlabs/postman-docs/blob/master/v6/postman/workspaces/sharing_collections_in_workspaces_for_version_5.md

**Comment by stcalica** [comment]
Haha, so my linter reports no problems on this page. 
@tristandenyer do you want me to just close this? Or do you want to check against your linter?

**Comment by tristandenyer** [comment]
@stcalica  Markdownlint in VSCode found 6 issues with this doc. We might want to find a more compatible linter for you, otherwise when we add in the linter in Travis you will be plagued with issues.
<img width="964" alt="Screen Shot 2019-08-09 at 3 10 03 PM" src="https://user-images.githubusercontent.com/4358288/62811801-f2650900-bab7-11e9-9b0b-eea57103d4ba.png">

**Comment by stcalica** [comment]
yeah, I can just start using VC, that's fine. It'd be much easier and in-sync with everyone else's.

**Comment by tristandenyer** [comment]
Mostly trailing whitespaces, but Line 15 should be an h2 (##).

**Comment by tristandenyer** [comment]
If you can import linter settings, we could just create a file for that and share around.
