### ISSUE TITLE
RBAC Docs Header Alignment

### ISSUE THREAD

**Issue by lashcrafty** [postmanlabs/postman-docs#1744]
**Describe the bug**
This is a super useful document but the headers for each of the roles overlaps the columns creating friction in quickly consuming permission context. 

**To Reproduce**
1. Go to 'https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/'
2. Scroll down to 'List of Permissions and Roles'
4. See 'ViewerEditor' or 'CollaboratorAdmin'

**Expected behavior**
The role names for each section (Viewer, Editor, Collaborator, Admin, etc) should have a space between them and they should nicely align over the check boxes in each column. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/53920068/62745174-9d18f100-b9fe-11e9-9851-e8c9e84f9fae.png)
![image](https://user-images.githubusercontent.com/53920068/62745200-ad30d080-b9fe-11e9-897e-8f6b2f48b4ce.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
This document is used often to explain to Postman users the collaboration and control capabilities of Postman.

**Comment by tristandenyer** [comment]
Investigated the level of effort for this. Found:
— we use Bootstrap 4
— therefore we can simply add `class="table"` to the table tags.
— the `gatsby-remark-classes` plugin does just that...
— BUT it doesn't work in our app. 😞
— I tried updating the `gatsby-transformer-remark` package, but still doesn't work (in fact, it errors out on build.)

Recommending we add the table style to the table tag, instead of the table classname, for now until we update this app to Gatsby v2.

**Comment by tristandenyer** [comment]
<img width="615" alt="Screen Shot 2019-08-09 at 3 28 30 PM" src="https://user-images.githubusercontent.com/4358288/62812398-67d1d900-baba-11e9-899b-0758b82c6963.png">

**Comment by lashcrafty** [comment]
Do you need anything more from me to progress?

**Comment by tristandenyer** [comment]
@lashcrafty No, thanks for the reminder. I am going to have @ch264 work on this (add the Bootstrap table style to our table tag as a stop gap until LC 2.0 comes out.)

**Comment by ch264** [comment]
padding in table and a bottom border on the rows was added to make the table more readable. 

See following examples: 
https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/

https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_team/
