### ISSUE TITLE
Roles and Permissions doc in GitHub does not match URL learning center path

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#1768]
Roles and Permissions doc can be found under URL: 'https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/'

Problem:
The doc location on GitHub is: postman-docs/v6/postman/roles_and_permissions.md

The file location on GitHub does not match the url location. 

Notes: 
- @tristandenyer believes this is part of a larger issue and that more docs are affected.
- Caveat: I am not sure if Contenful only looks at the slug or the doc location. We can test this  by adding a fake doc and then moving it to see if the URL breaks. We need to look into if Algolia search, manual links within the doc, possibly links in the left nav could be affected by moving the doc.

**Comment by SueSmith** [comment]
Thinking this is superseded by migrating to new version of learning center and we can close..? @ch264

**Comment by ch264** [comment]
@SueSmith yes indeed. Thanks for cleaning up. I will close the ticket.
