### ISSUE TITLE
cookies - cookies management

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#1770]
We are experiencing issues with the file "cookies" getting published. Cookies is a common word and we suggest renaming it the title, slug, URL and redirect to a non-unique term such as managing_cookies or cookies_management.

This is also a test to see if a singular, non-unique term is the issue of prohibiting this doc going into production.

**Comment by arlemi** [comment]
@ch264 Is that still an issue?

**Comment by ch264** [comment]
@arlemi We have changed our tech stack so this ticket can be closed. Thank you for reminding. I will close it.
