### ISSUE TITLE
LC Environments and globals > Variables | Error in URL in the page

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#1781]
There is an extra slash symbol in the URL inserted on the Learning Center Article `Variables` 
Environments and globals > Variables > [Dynamic variables](https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#dynamic-variables) > "Dynamic Variables List"

<img width="920" alt="Screen Shot 2019-09-06 at 16 15 11" src="https://user-images.githubusercontent.com/47351631/64434833-baa2ae80-d0c1-11e9-8413-1f6a616d71c5.png">

The URL is now: https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/**/**#dynamic-variables 

It lands on a 404.

It should be:
https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#dynamic-variables

**Comment by cyrielle-hada** [comment]
@ch264

**Comment by ch264** [comment]
broken link has been updated
