### ISSUE TITLE
Visualizer's status needs to be updated 

### ISSUE THREAD

**Issue by anudeepmedicharla** [postmanlabs/postman-docs#1797]
Visualizer is up on prod but the learning center doc still mentions that it is in canary

![Screenshot 2019-09-23 at 10 05 02 AM](https://user-images.githubusercontent.com/16399370/65402881-cfd04a80-ddee-11e9-8a80-c73b798f4c1f.png)

**Comment by kaustavdm** [comment]
This was fixed by #1798 :-)
