### ISSUE TITLE
Clicking on Add tests in monitoring test results redirects to page with 404 response

### ISSUE THREAD

**Issue by shivam-postman** [postmanlabs/postman-docs#1802]
When viewing the test results for a monitor, selecting the failed tests tab shows a message with a link to Add tests, if no tests failed. The link redirects to a page returning 404. Similar behaviour is seen when no tests are present in the monitor's collection and we click Add tests. 

**To Reproduce:**  

1. Go to the monitor's page.
2. Select a run for which all the tests passed.
3. Go to the test results and select the failed tests tab (red square).
4. Click on Add tests. The page opens with 404.

**Expected behaviour:** A 'how to add tests' page should open up.

**Screenshots:**

![image](https://user-images.githubusercontent.com/53427068/65445900-d7284000-de50-11e9-8a45-ec9116264ce5.png)

![image](https://user-images.githubusercontent.com/53427068/65445920-df807b00-de50-11e9-9958-0302c0de2d92.png)

**Comment by shivam-postman** [comment]
https://learning.getpostman.com/docs/api_testing_and_collection_runner/writing_tests
This is the link returning 404.

**Comment by SueSmith** [comment]
Commenting to keep open
