### ISSUE TITLE
"Working with data files" collection download does not match screenshot

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/postman-docs#1803]
As reported [here](https://community.getpostman.com/t/looping-through-data-files-discrepancy-in-the-sample-code/7945), [this screenshot](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/working_with_datafiles/using_the_data_variable.png) does not match the collection download found [here](https://learning.getpostman.com/docs/postman/collection_runs/working_with_data_files/#getting-started). The screenshot uses our pm syntax, while the download uses our [deprecated syntax](https://learning.getpostman.com/docs/postman/scripts/test_examples/#older-style-of-writing-postman-tests-deprecated) and does not work as is with csv files.

Here is the updated collection to replace the existing file:
[Using data files.postman_collection.json.zip](https://github.com/postmanlabs/postman-docs/files/3643615/Using.data.files.postman_collection.json.zip)

@kaustavdm as this file is in S3, assigning to you.

**Comment by jkonrath-postman** [comment]
Looks like this got fixed a while ago.
