### ISSUE TITLE
"Integration with Jenkins" sample command does not match the image

### ISSUE THREAD

**Issue by liangjihua** [postmanlabs/postman-docs#1809]
![image](https://user-images.githubusercontent.com/35123083/65736766-cad10b00-e10e-11e9-9480-b409793271d5.png)
And the example command seems to be wrong?

**Comment by jkonrath-postman** [comment]
The command was corrected a while ago, but the image was still wrong. I updated that, and freshened up a few other images with some minor edits - see the linked PR.
