### ISSUE TITLE
List of Roles and Permissions is wrong and misleading

### ISSUE THREAD

**Issue by sankalp0o** [postmanlabs/postman-docs#1813]
The page https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/#list-of-roles-and-permissions has incorrect representation of what the permissions for team roles are.
#1573 is related to this.

**Comment by harshachelle** [comment]
The link mentioned in the issue is returning a 404.

This is the correct link of the page- https://learning.getpostman.com/docs/postman-pro/managing-pro/roles-and-permissions/

**Comment by arlemi** [comment]
This was fixed in #1961
