### ISSUE TITLE
Missing pages in repo

### ISSUE THREAD

**Issue by sankalp0o** [postmanlabs/postman-docs#1814]
The page for Roles and Permissions (https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions) is missing from the repo.

**Comment by kaustavdm** [comment]
Another file reported missing by @harryi3t: https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/

Looks like some things got missed in the migration. I will bring back the files with matching content from contentful.
