### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1822]
We need to delete unused branches after merging.
Please verify which branches we need open and delete the rest.
<img width="346" alt="Screen Shot 2019-09-30 at 1 21 39 PM" src="https://user-images.githubusercontent.com/4358288/65913845-653a8400-e385-11e9-95b3-6ff250df5e78.png">

**Comment by kaustavdm** [comment]
Anyone who merges a PR should also delete the branch, if applicable. I don't see that many branches though,.

**Comment by SueSmith** [comment]
Thinking we can close this and just keep an eye on branches going forward..? @Ryan-McBride
