### ISSUE TITLE
`pm.collectionVariables` is not documented

### ISSUE THREAD

**Issue by jrop** [postmanlabs/postman-docs#1856]
Ideally, `pm.collectionVariables` should be documented on this page:

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/

**Comment by arnitkun** [comment]
Thank you for letting us know. Yes, collectionVariables will be documented soon. Will update once it is done.

**Comment by arnitkun** [comment]
The changes have been merged. Closing this issue.
