### ISSUE TITLE
Contribution guidelines mention npm run lint instead of nom run test:mdlint 

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/postman-docs#1924]
When trying to run `npm run lint` against the repository the following error is shown:
```
npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/****/.npm/_logs/2019-11-04T11_13_33_174Z-debug.log
```

It should be `npm run test:mdlint`

**Comment by ch264** [comment]
I changed the line in the contribution doc and also changed the reference from 'V6' to 'doc'
