### ISSUE TITLE
Change navigation button from "Login" to "Sign In"

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1929]
**This is a great 'first issue!** If you are new to GitHub or would like ot make your first contribution to an open source project, this ticket is great for that.

The current button CTA for logged out users on getpostman.com is "Sign In".

<img width="752" alt="Screen Shot 2019-11-04 at 1 09 11 PM" src="https://user-images.githubusercontent.com/4358288/68158385-5d31af00-ff04-11e9-9550-9990c3605366.png">

We need to update the Learning Center to follow the same copy as above:
<img width="743" alt="Screen Shot 2019-11-04 at 1 08 46 PM" src="https://user-images.githubusercontent.com/4358288/68158416-6ae73480-ff04-11e9-8611-387aaa15ef68.png">

Acceptance criteria:
— Logged out users should see an orange button with "Sign In" text in it.

**Comment by ch264** [comment]
This PR is already in.
