### ISSUE TITLE
Folder name changed—redirects not working

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1943]
The folder `/postman_pro/managing_postman_pro/` has changed to `/postman-pro/managing-pro/` which seems to break the underscores redirects for a URL such as:

https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/roles_and_permissions/ (which used to work.)

**Comment by ch264** [comment]
@tristandenyer is this an external link? We are editing internal links and setting up redirect for external links.

**Comment by ch264** [comment]
PR #1948
