### ISSUE TITLE
send user an email/notification when Github Actions fails

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#1947]
User should be notified if the Github Actions run have thrown an error/warning. 

Maybe we could use something like this? 
https://github.com/marketplace/actions/sendgrid-action

**Comment by evlnyng** [comment]
I would like to give this one a shot!

**Comment by ch264** [comment]
Awesome @evlnyng. Thank you

**Comment by tristandenyer** [comment]
Yay @evlnyng ! Thanks for helping out! 🦄

**Comment by ch264** [comment]
@evlnyng Github actions is sending out default emails. You are welcome to work on another ticket 😄
