### ISSUE TITLE
Add space at the bottom of the docs

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1950]
**This is a great 'first issue!** If you are new to GitHub or would like to make your first contribution to an open source project, this ticket is great for that.

We need to add some space at the end of the documentation to give it some space above the footer.

Current:
<img width="948" alt="Screen Shot 2019-11-06 at 7 26 14 PM" src="https://user-images.githubusercontent.com/4358288/68357910-b6980a80-00cb-11ea-9698-a27682000853.png">

Proposed, using `margin-bottom: 40px;` on the .doc-page:
<img width="934" alt="Screen Shot 2019-11-06 at 7 26 49 PM" src="https://user-images.githubusercontent.com/4358288/68357951-d62f3300-00cb-11ea-938d-fb951715c5d1.png">

**Comment by ch264** [comment]
Thanks @mclausaudio for contributing. PR has been accepted
