### ISSUE TITLE
Blockquote support

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#1951]
Markdown blockquotes are not supported in new version of learning center css.

___Note from @tristandenyer - look up waybackmachine for design.___

**Comment by ch264** [comment]
@SueSmith I cannot reproduce the error. Blockquotes work fine for me. Can you plase send me an example? 

This is an image of my code, which works according to the docs: https://www.gatsbyjs.org/docs/mdx/markdown-syntax/#blockquote

<img width="1135" alt="Screen Shot 2019-11-07 at 12 01 13 PM" src="https://user-images.githubusercontent.com/36343528/68423129-5d28ed80-0156-11ea-99a5-2f1d662e464e.png">

**Comment by SueSmith** [comment]
It works for me like that in an editor but not in the site when I test it locally in the browser:
<img width="206" alt="Screenshot 2019-11-07 at 20 14 41" src="https://user-images.githubusercontent.com/6666370/68424225-72743b00-019b-11ea-97fe-4be78cfa5c80.png">
<img width="302" alt="Screenshot 2019-11-07 at 20 14 52" src="https://user-images.githubusercontent.com/6666370/68424230-74d69500-019b-11ea-8824-8c3c6b79d9e2.png">

**Comment by ch264** [comment]
@SueSmith Thank you for the example. I have included a fix in PR #1952
