### ISSUE TITLE
/sharing-collections page: add copying this json and importing it into postman

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#1959]
(Ported over from Jira ticket WEBSITE-101) The section about sharing a link to a collection should also talk about copying this json and importing it into postman.

<img width="1268" alt="Screen Shot 2017-07-04 at 4 45 27 PM" src="https://user-images.githubusercontent.com/4358288/68556276-57e1d200-03e6-11ea-8331-aecbd2b795f4.png">

**Comment by SueSmith** [comment]
This is actually covered by one of the tasks in our gap analysis - referenced this issue in there to follow up when we get there (it's partway down the list so will be a while..)

**Comment by arlemi** [comment]
There is now a "sharing as a file" section in the LC: https://learning.postman.com/docs/postman/collections/sharing-collections/#sharing-as-a-file
