### ISSUE TITLE
Provide information regarding APIs usage limit 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#1966]
_Filed by Product Support_

Some users have been surprised to see the below error message and find out after purchasing a plan that there is a limited number of APIs they can create. 

<img width="340" alt="Screen Shot 2019-11-12 at 15 56 20" src="https://user-images.githubusercontent.com/47351631/68756332-debec680-0601-11ea-883f-4094354c4302.png">

For now, neither our [pricing page](https://www.getpostman.com/pricing) or the Learning center states **the number of APIs a team can create according to their plan**.

The only place where users can retrieve this information is on the dashboard (but only once they have created/purchased a team) - https://app.postman.co/usage. 

However, the usage page doesn't provide any insight into the number of APIs they can create in the event that they would upgrade the plan. 

For example for the [Mock Server documentation](https://learning.getpostman.com/docs/postman/mock-servers/setting-up-mock/) - we don't provide the limitation in the Learning Center either. We're saying the following
`Note: The number of calls made to mock servers may be limited by your Postman account. Check your usage limits.`

Would it be possible to document this in the [Managing APIs](https://learning.getpostman.com/docs/postman/design-and-develop-apis/managing-apis/) section and add a sub-section called **Usage limit**: 

Free teams - 3 APIs
Pro teams - 10 APIs
Enterprise teams - 100 APIS

**Comment by SueSmith** [comment]
Great thanks for the additional info, have referenced this in our doc gap work so will follow up from there!

**Comment by SueSmith** [comment]
Commenting to keep this open

**Comment by arlemi** [comment]
We now have updated the pricing page and the documentation with the limit + a link to this blog post: 
https://blog.postman.com/2020/01/24/what-does-max-of-apis-mean-in-postman/
