### ISSUE TITLE
Image not displaying on script page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1973]
Image not displaying on [script page](https://learning.getpostman.com/docs/postman/scripts/test-scripts/#viewing-results)

<img width="1536" alt="image-no" src="https://user-images.githubusercontent.com/17693714/68705502-0ef36000-0543-11ea-9ac1-32b4cadfc5ab.png">

**Comment by SueSmith** [comment]
@ch264 is this maybe another one that was missed during migration?

**Comment by ch264** [comment]
@loopDelicious thanks for finding this. I will look into it

**Comment by ch264** [comment]
@loopDelicious fixed it and PR is in.
