### ISSUE TITLE
API limit

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#1981]
API limit

**Comment by sankalp0o** [comment]
Transferred this issue from postman-app-support to postman-docs. cc @cyrielle-hada

**Comment by sankalp0o** [comment]
We have a brief mention for API limits on this page https://learning.getpostman.com/docs/postman/design-and-develop-apis/managing-apis/ 

> Note: Free users can create up to three APIs, Pro users up to 10, and Enterprise users up to 100.

**Comment by SueSmith** [comment]
Is this different from #1966 ? If not can we have a bit more detail?

**Comment by cyrielle-hada** [comment]
This issue can be closed - I have mistakenly created this issue for postman-app-support directly from the ticket and recreated #1966.
