### ISSUE TITLE
Update Newman docs to v4

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#1985]
Update syntax in code samples and screenshots to Newman v4 on Jenkins integration page. There might be other places in the docs that need to be updated as well. 

For example, some syntax on [this page](https://learning.getpostman.com/docs/postman/collection-runs/integration-with-jenkins/) reflects discontinued API. 
1) With v4, `--exit-code` flag is no longer a valid option, but can use `-x` or `--suppress-exit-code` to override the default exit code.
2) There's also a typo in this screenshot - missing the `run` part of the command
<img width="1097" alt="Screen Shot 2019-11-12 at 1 43 05 PM" src="https://user-images.githubusercontent.com/17693714/68779914-479a4480-05ea-11ea-80ce-0c0f7e34c7a0.png">

Helpful resources:
* https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#v2-to-v3-migration-guide
* @codenirvana

**Comment by SueSmith** [comment]
Commenting to keep open

**Comment by someshkoli** [comment]
working on it
