### ISSUE TITLE
Sandbox API Reference doesn't include pm.request.body

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#1994]
Docs:
https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/
https://learning.getpostman.com/docs/postman/scripts/postman-sandbox/

`pm.request.body` is a valid property of `pm.request`, but this isn't reflected on either the **Postman Sandbox** or **Postman Sandbox API Reference** pages.

It may be worth auditing this to see if there are other methods/properties missing.

**Comment by JP-from-Postman** [comment]
This is a pretty new issue. Seems like the bot is jumping the gun a bit?

**Comment by SueSmith** [comment]
@JP-from-Postman agreed, have requested that it not close anything and that the timeframe be extended.

**Comment by SueSmith** [comment]
@JP-from-Postman think we can close this on account of @DannyDainton's recent pr? https://github.com/postmanlabs/postman-docs/pull/2200

**Comment by JP-from-Postman** [comment]
@SueSmith LGTM
