### ISSUE TITLE
Address the question `how to Recover a folder?` in LC 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#2007]
_Filed by Product Support_ 

For now, our public-facing documentation doesn't explain **how to recover a folder**, if being accidentally deleted. 

The changelog documentation says we can rollback a collection and restore it to any previous point in time but it _should_ tell explicitly that the changelog enables a user to recover a folder. 

Also, a user who has accidentally deleted a folder and will search on the Learning center for the keyword `Folder` won't land on this documentation page. 

**Suggested solution**

Modify the section **Restoring collections** and a sub-section called "how to Recover a folder?" with the steps below.

1 - Click the arrow next to the collection for which you want to recover the folder
2 - Select the changelog tab. 
3 - Click on `Restore`. 

<img width="412" alt="Screen Shot 2019-05-07 at 10 31 43" src="https://user-images.githubusercontent.com/47351631/69258851-35557300-0bb5-11ea-97ff-233e4308c84c.png">

**Comment by SueSmith** [comment]
@cyrielle-hada Thank you for the detail! 😸

**Comment by SueSmith** [comment]
@cyrielle-hada am not seeing this option in the product now - wondering if it was removed..?

**Comment by cyrielle-hada** [comment]
@SueSmith this is a feature only available for paid teams. Are you testing on either a Team, Business, or Enterprise account?

**Comment by SueSmith** [comment]
@cyrielle-hada ahh got it thanks - will get a pr opened for this 👍
