### ISSUE TITLE
Request for New Feature

### ISSUE THREAD

**Issue by nebnhoj** [postmanlabs/postman-docs#2024]
**Add Data Faker Functionalities**

**Comment by SueSmith** [comment]
Hi, are you asking for more detail in the docs on using faker data?

**Comment by nebnhoj** [comment]
yes does postman has library of fake data that the tester can use?

**Comment by SueSmith** [comment]
Yes this is our current reference: https://learning.getpostman.com/docs/postman/environments-and-globals/variables-list/

Does that solve your issue?

**Comment by nebnhoj** [comment]
Thanks

**Comment by SueSmith** [comment]
No problem! Am I good to close this issue?

**Comment by nebnhoj** [comment]
Yes, thank you again
