### ISSUE TITLE
404 error on example link

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2030]
on Page https://learning.getpostman.com/docs/postman/api-documentation/publishing-public-docs/ the the 'example' link https://documenter.getpostman.com/view/583/coopers-meal-plan/4u2 at the very end results in a 404 page. 

<img width="1024" alt="Screen Shot 2019-12-03 at 4 25 22 PM" src="https://user-images.githubusercontent.com/36343528/70101371-8881e980-15e9-11ea-9804-93dc66cc5178.png">

**Comment by SueSmith** [comment]
this will be fixed in pr #2020

**Comment by ch264** [comment]
👍
