### ISSUE TITLE
Index related resources for search

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2034]
Index related resources for search.

For example, if I'm searching for how to do something related to LoopBack, we have a relevant blog available and listed in the sidebar. However we don't explicitly talk about it in the docs since it's a specific user scenario. Therefore I won't discover this resource through search.

<img width="1338" alt="loopback" src="https://user-images.githubusercontent.com/17693714/70378696-b8035f80-1923-11ea-99ba-f61e5b9a04d5.png">

**Comment by jkonrath-postman** [comment]
Not sure when this changed, but I think it works now.

The loopback blog posts are long gone, but I tested by searching on DRY, which isn't in the docs, but a blog post appears on three pages:

<img width="869" alt="Screen Shot 2021-06-11 at 9 31 38 AM" src="https://user-images.githubusercontent.com/80709817/121720478-043edb00-ca98-11eb-95d9-dd93680d5ec1.png">
