### ISSUE TITLE
Documentation search result contains broken link

### ISSUE THREAD

**Issue by jsooter** [postmanlabs/postman-docs#2035]
Searching for "documentation" and clicking the "Authoring Documentation" result takes you to this page which displays 404: https://learning.getpostman.com/docs/postman/api-documentation/authoring-your-documentation/

**Comment by SueSmith** [comment]
@ch264 this looks like it's indexed a new page that is on develop branch but not pushed to prod yet, not sure if there's any way to avoid this? This one can be pushed to prod anytime, just wondering for future reference..

**Comment by SueSmith** [comment]
I believe this is fixed following recent push to prod but let's keep this issue open to figure out how we avoid it in future.

**Comment by ch264** [comment]
@SueSmith I agree. I will look into the Algolia docs to investigate. Let's indeed keep this open until further clarification.

**Comment by jkonrath-postman** [comment]
Not happening now.
