### ISSUE TITLE
The Difference between Remove Collection and the Delete Collection

### ISSUE THREAD

**Issue by asi-postman** [postmanlabs/postman-docs#2040]
It would be great to have the following as a Learning Center doc, as we have a few support tickets that are related to the subject matter. 

*The Difference between Remove Collection and the Delete Collection*

**Comment by asi-postman** [comment]
Product Support will host the doc on the Help Center via Zendesk

**Comment by SueSmith** [comment]
Reopening because if this is coming up in tickets we should def cover it in docs too, even if it's just a note or whatever.
