### ISSUE TITLE
Bootcamp Link Directs to 404

### ISSUE THREAD

**Issue by heathmills** [postmanlabs/postman-docs#2046]
On the final step of Debugging and manual testing > Global variables, there is a Learn More link that is broken and returns a 404 error.

![image](https://user-images.githubusercontent.com/4287072/70811877-7f84db00-1d94-11ea-84b5-ab6944aa24d5.png)

**Comment by heathmills** [comment]
Same issue for the Learn More link on:

- Debugging and manual testing > Environmental variables
- Debugging and manual testing > Collection variables

**Comment by SueSmith** [comment]
@heathmills thanks so much for reporting this and apologies for the hassle. I'll sort the links / redirects asap but in the meantime our new variables doc is here: https://learning.getpostman.com/docs/postman/variables-and-environments/variables/

**Comment by SueSmith** [comment]
ok pushing a fix for this 🙈 

thanks again @heathmills 🙌
