### ISSUE TITLE
Suggestion: Github Action for first time contributors

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2048]
Would it be a nice touch to set up a Github Action that sends a message for contributors who open issues for the first time? 
@tristandenyer @SueSmith @nicktran

**Comment by SueSmith** [comment]
I think this is a nice automated acknowledgement, will do my best to follow up with people manually as well, but this of course scales better.

**Comment by jkonrath-postman** [comment]
@tristandenyer this is low priority, but any thoughts on how to do this? I was looking at https://github.com/marketplace/actions/first-issue-greeter but it looks like it might not be maintained anymore. Any other ideas?

CC @chrisdeso - you doing anything similar in support?

**Comment by KushGabani** [comment]
I'd like to contribute to this issue by setting up a workflow. I am a beginner at GitHub Actions but this seems fairly simple. Can you assign me to it?

**Comment by jkonrath-postman** [comment]
@KushGabani I need to research this before we do anything. I don't think we can use the above linked action, and I need to talk to someone else about what we say in the greeter.

**Comment by KushGabani** [comment]
yes, okay. Actually, I'm creating my own GitHub action for a task like this. Extending this idea, I was also going to extend these feature to first time contributors as well.

**Comment by jkonrath-postman** [comment]
I think we're going to not do this.
