### ISSUE TITLE
internationalization (i18n) with Gatsby

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2057]
@nicktran @SueSmith @tristandenyer 

It was suggested to add internationalization to the Learning Center. Gatsby has a plugin: https://www.gatsbyjs.org/docs/localization-i18n/

Is this something that we want?

doopoll.co works with Applinga: https://applingua.com/ for their translations. Here is an example for implementation with [react-i18next](https://react.i18next.com/) https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/

**Comment by SueSmith** [comment]
This would be a great way to better support our community.. 🌍 🌎 🌏 👍

**Comment by arlemi** [comment]
That would be awesome! 🙌

Two issues that I've seen happening with this are:
- having only certain parts of a page translated and therefore showing a page with different languages on
- forcing a language on a user 

Both of these are easy to avoid but we need to take that into account from the beginning (ie. give an option to override the default language).

**Comment by ch264** [comment]
@arlemi very valid points. IMO English should always be an option to switch to.

Relying completely on open source for translations indeed has the risk of incomplete/inaccurate translations. I suggested Applingua for an initial start. Do you know any other translation providers that could be good for us?

**Comment by arlemi** [comment]
I think any language that we'll eventually have available should be an option to switch to.  :) 

I've heard of gengo (https://gengo.com/) but have never used it. Probably worth asking Marketing for some recommendations here.

**Comment by ch264** [comment]
@arlemi awesome thanks for sharing. 

@nicktran how would you like us to proceed with localization for the Learning Center?

**Comment by arlemi** [comment]
Just saw https://localizejs.com/ suggested on another issue, probably worth adding to the list too.

**Comment by ch264** [comment]
@arlemi thank you for referencing the other ticket. 

@nicktran how would you like us to proceed with localization for the Learning Center?

**Comment by nicktran** [comment]
Yes, I want localization but I would like to see a macro proposal inclusive
of all web properties.

**Comment by DanielPalafox** [comment]
Any news on this?

**Comment by tristandenyer** [comment]
No additional news at this time @DanielPalafox. Will reprioritize for upcoming sprint.

**Comment by jkonrath-postman** [comment]
Closing this as it's an internal issue. Search Confluence for RFC-110 and there's a page on it.

**Comment by falcucci** [comment]
news?

**Comment by cantaylancapraz** [comment]
Any news?

**Comment by deefactorial** [comment]
Any Update?
