### ISSUE TITLE
Add Intro to API video to additional resources sidebar

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2063]
Video series re: Intro to APIs - https://www.youtube.com/playlist?list=PLM-7VG-sgbtBBnWb2Jc5kufgtWYEmiMAw

This new video series could be added to `Pre-requisites` or `Additional Resources` in the secondary sidebar for introductory docs pages. It could be listed on the Learning Center landing page as well.

**Comment by SueSmith** [comment]
Oh magic, I'll add that to various places in docs. Paging @tristandenyer re landing page listing.
