### ISSUE TITLE
Extend test examples

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#2065]
Re community feedback https://community.getpostman.com/t/what-would-make-the-postman-learning-center-more-useful-to-you/9660/3 

Use this great post started by @madebysid for inspiration https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990 via @DannyDainton

**Comment by jkonrath-postman** [comment]
Moving this internally - see tw-213
