### ISSUE TITLE
Authorization type API Key not working

### ISSUE THREAD

**Issue by crowcoder** [postmanlabs/postman-docs#2071]
When I choose "API Key" for Authorization TYPE I can fill in "Key", "Value" and "Add to" but it has no effect on the request. Additionally, there is no Preview Request button.

When I went to the documentation I noticed there is a link for API Key but there is no such section or content:

https://learning.getpostman.com/docs/postman/sending-api-requests/authorization/#api-key

My version is Windows 7.14.0

![image](https://user-images.githubusercontent.com/4210624/71364153-5cfb7a80-2569-11ea-986f-708886ef607d.png)

**Comment by SueSmith** [comment]
Hi there, apologies for the missing docs section, I will get that sorted. When I add a key and value with query params selected in the dropdown and send a request, the values are successfully sent as part of the url - could you try sending your request with the console open to verify what Postman is sending?

**Comment by crowcoder** [comment]
Yes, it does send the values in the query string but the builder shows no indication that it is set.

**Comment by SueSmith** [comment]
Do you mean the query string in the request tab url in Postman doesn't update to show the values?

**Comment by crowcoder** [comment]
That is correct:
![image](https://user-images.githubusercontent.com/4210624/71726019-b7c88800-2e2d-11ea-996b-49b87952c981.png)

**Comment by SueSmith** [comment]
OK I am guessing that may be intentional to avoid copying sensitive data to various parts of the ui but am seeing what I can find out, will let you know!

**Comment by crowcoder** [comment]
OK, that makes sense. It is just inconsistent with the other auth types where there is a Preview Request button. Once the online documentation gets updated it won't be confusing.
