### ISSUE TITLE
Duplicated Tabs are binded Twins!

### ISSUE THREAD

**Issue by YoullNeverSee** [postmanlabs/postman-docs#2075]
Hi Postman Team,

I got an issue with duplicated tabs.

What I expect is if I duplicate a Tab is a new tab with same params.
But what happen is that both tabs binded together like twins!
Means, if I made changes on one or the other tab both been changed at the same time.
That is way the most critcal issue I found and hope you can do a bugfix soon as possible because that is a hard bug in workflow an unusable.

It is known since:
https://github.com/postmanlabs/postman-app-support/issues/4463

I'm running Postman v7.14.0 - is there is no hope ?

Danke schonmal im Voraus
Gruß

**Comment by cyrielle-hada** [comment]
@YoullNeverSee the issue is filed on the wrong directory. Instead, I have filed the issue as a Feature Request here: https://github.com/postmanlabs/postman-app-support/issues/7867.
