### ISSUE TITLE
Provide ability to use postman theme in visualizer templates

### ISSUE THREAD

**Issue by rsquarev** [postmanlabs/postman-docs#2084]
It would be nice and seamless if I could use postman theme for my visualizer template. Right now, I could do this by creating styles same as postman theme. But when I change theme, I have to update styles in theme. So, if I could get the theme information using something like pm.theme object, this could be used in styles. This way my visualizer dynamically change its styles according to postman current theme. 

I know visualizer feature is in beta. It may change or you may have this ask already in pipeline.

**Comment by SueSmith** [comment]
Hi @rsquarev! I'm not sure this is the right place for your request as this is the documentation repo, perhaps the [app support repo](https://github.com/postmanlabs/postman-app-support/issues)?

**Comment by rsquarev** [comment]
sorry, I will close here and open in app support.
