### ISSUE TITLE
Update collection runs section 

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2085]
Related to [#7883](https://github.com/postmanlabs/postman-app-support/issues/7883).

1) When the ability to reorder requests within a collection run was released, access to the historical collection run results was changed. This page should be updated to clarify how to access historical collection run results and also the results of the most recent collection run. 

https://learning.getpostman.com/docs/postman/collection-runs/sharing-a-collection-run/

2) Screenshot on this page displays an interim UI. Also should add how to access the collection runner via collection details flyout. 

https://learning.getpostman.com/docs/postman/collection-runs/intro-to-collection-runs/

3) Also inconsistent usage of "Collection Runner" vs "Runner" vs "collection runner" throughout.

**Comment by jkonrath-postman** [comment]
The first page is actually gone now, and the second has been extensively rewritten in the last 18 months, so I'm not sure this is relevant anymore.
