### ISSUE TITLE
Missing variables in Dynamic Variables List

### ISSUE THREAD

**Issue by aliasgarlabs** [postmanlabs/postman-docs#2100]
Before faker, we used to have these dynamic variables available:
- {{$guid}}
- {{$timestamp}}
- {{$randomInt}}

These variables can be found in [using variables doc](https://learning.getpostman.com/docs/postman/variables-and-environments/variables/#using-dynamic-variables) which also sports a link to a complete list.

However, this [complete dynamic variables doc](https://learning.getpostman.com/docs/postman/variables-and-environments/variables-list/) does not include these old variables mentioned above which causes a bit of confusion and misleads the user.
<img width="1680" alt="Screenshot 2020-01-13 at 3 51 52 PM" src="https://user-images.githubusercontent.com/5235231/72248602-95005580-361d-11ea-8b91-913abd0e0a6d.png">

**Comment by arlemi** [comment]
Closing this since PR has been merged, thanks again!
