### ISSUE TITLE
Add Transport Layer Security (TLS) to documentation

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2102]
The most popular term missing from our search results (and docs) is "tls". This keeps cropping up. It is documented in our Support channel, but not here.

Proposing we add this to our docs to help those looking for this information in LC.

See Support doc: https://support.getpostman.com/hc/en-us/articles/360041392573-Deprecating-TLS-1-0-and-TLS-1-1

<img width="760" alt="Screen Shot 2020-01-13 at 11 02 03 AM" src="https://user-images.githubusercontent.com/4358288/72283900-9a957580-35f4-11ea-8019-75254ff3e0b8.png">

**Comment by arlemi** [comment]
Any specific reason for which you've assigned this to me @tristandenyer ? 🤔

**Comment by arlemi** [comment]
Un-assigning myself since no answer from Tristan.

**Comment by tristandenyer** [comment]
Apologies @arlemi for the delay. The reason was stated in the description above—will elaborate: the Algolia Search appliance keeps coming back, week after week, telling us that the top search term for the site that has 'no results' is `tls`. A quick Google search shows we do have content for `tls` and or `transport layer security` topic.

This ticket is to add the `tls` search term to the front-matter of the pages this relates to, and possibly adding to copy as "(TLS)" to buoy search-ability.
