### ISSUE TITLE
Update Collection recovery limitations on Docs

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2106]
Request to add details around the limitations of recovering collections of size 30 Mb and above. If the collections with larger sizes are deleted then the same cannot be found in Trash and neither can they be recovered.

As per the desired workflow: Users should be receiving a warning message while trying to delete collections of larger size. It would be ideal to include possible workarounds when the user faces these issues or be able to identify the size of collections from the App or Web Dashboard.

It would be relevant if the same can be added in the below section:
https://learning.getpostman.com/docs/postman/collections/managing-collections/#recover-a-collection

**Comment by Raj-postman** [comment]
This is with connection to the issue [#7911](https://github.com/postmanlabs/postman-app-support/issues/7911)

**Comment by jkonrath-postman** [comment]
The delete warning (and the >30MB limitation) needs to also be mentioned in the section above that ("To delete a collection...")
