### ISSUE TITLE
404 URLs

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2110]
404 url on postman /postman-pro/managing-pro/billing.md

<img width="977" alt="Screen Shot 2020-01-15 at 10 53 48 AM" src="https://user-images.githubusercontent.com/36343528/72462260-846aef00-3785-11ea-85bf-67ae4a11200b.png">

**Comment by ch264** [comment]
Investigate, why the link goes to https://learning.getpostman.com/docs/postman-pro/managing-pro/billing/docs/postman-pro/managing-pro/changing-your-plan/

**Comment by SueSmith** [comment]
We'll be updating this page for the new pricing within the next couple weeks and the destination page will also move so suspect this will be fixed along with those changes.

**Comment by ch264** [comment]
It is fixed. I will close the ticket.
