### ISSUE TITLE
Layout bug in Documentation under the tab ''Test examples''

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2126]
Layout issue in the documentation:

Page link: https://learning.getpostman.com/docs/postman/scripts/test-examples/

<img width="1152" alt="Screenshot 2020-01-24 at 5 48 08 PM" src="https://user-images.githubusercontent.com/47771757/73068986-9873c680-3ed2-11ea-9740-85a6abd5519e.png">

**Comment by ch264** [comment]
Thank you for reporting @Raj-postman. I am looking into this

**Comment by Raj-postman** [comment]
@ch264 Similar issue on following pages:

- https://learning.getpostman.com/docs/postman/postman-api/continuous-integration/
- https://learning.getpostman.com/docs/postman-pro/managing-pro/buying/
- https://learning.getpostman.com/docs/postman-pro/integrations/github/
- https://learning.getpostman.com/docs/postman-for-publishers/run-in-postman/creating-run-button/
- https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/

**Comment by ch264** [comment]
Thank you so much @Raj-postman. This seems to be coming from the code blocks. I am fixing them now.

**Comment by ch264** [comment]
@Raj-postman @SueSmith fixes are in production. I am closing this ticket

**Comment by Raj-postman** [comment]
Thank you @ch264 :)
Issue on below pages still persists:

- https://learning.getpostman.com/docs/postman-pro/managing-pro/buying/
- https://learning.getpostman.com/docs/postman-pro/integrations/github/
- https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/

**Comment by SueSmith** [comment]
@Raj-postman thanks for this, should be addressed in #2130 👍
