### ISSUE TITLE
cookieJar.unset results in an error

### ISSUE THREAD

**Issue by dearhakeemdavis** [postmanlabs/postman-docs#2137]
Postman version 7.16.1
The following code no longer works:

```
const jar = pm.cookies.jar();
jar.unset(pm.request.url, 'name-of-cookie');
```

There is also no longer a "Whitelist Domains" to click in the "Manage Cookies" modal

**Comment by SueSmith** [comment]
Hi there, I'm still seeing the Whitelist Domains link in the Manage Cookies modal (which I believe you'll need in order to use those methods) - could you share a screengrab of what you're seeing with the cookie modal open?

**Comment by arlemi** [comment]
@dearhakeemdavis Are you still seeing the issue?

**Comment by SueSmith** [comment]
Closing for now but please let us know if there's still an issue.
