### ISSUE TITLE
Edit Current Version Name

### ISSUE THREAD

**Issue by ypolishetty** [postmanlabs/postman-docs#2139]
Team,

When I have multiple versions published for documentation, Is there any way I could edit the name of my current version in the published docs? I just want to append a small string to the end like: "Current - SP7".

Thanks,
Yash

**Comment by SueSmith** [comment]
Hi @ypolishetty - this repo is actually for the [Postman Learning Center](https://github.com/postmanlabs/postman-app-support/issues), am assuming your request is for API documentation generated in Postman..? In that case you'll want the [app support repo](https://github.com/postmanlabs/postman-app-support/issues). Hope that helps!

**Comment by ypolishetty** [comment]
Thanks. I've submitted there: https://github.com/postmanlabs/postman-app-support/issues/7979
