### ISSUE TITLE
No Collection backup option available as mentioned in documentation

### ISSUE THREAD

**Issue by sulaimaan26** [postmanlabs/postman-docs#2152]
**Description**
I am unable to sync the collection to github account as there is no option available as mentioned in documentation
 
**Plan-Type**: Trial
**Documentation-Module:** Github Integration
**Documentation URL**: https://learning.getpostman.com/docs/integrations/github/

**Documentation Screenshot**
![image](https://user-images.githubusercontent.com/49139974/73658152-778d3d00-4659-11ea-9e07-bb21cd47d7c3.png)

**Website Screenshot**
![image](https://user-images.githubusercontent.com/49139974/73658339-c4711380-4659-11ea-9d54-44e2694e258b.png)

As show in image above there is no option displayed.Please make a review if anything has to be done i have followed all steps from the documentation

If this feature is not available for a trial user please mention it clearly in documentation

**Comment by SueSmith** [comment]
Hi there, can I ask if you already have other integrations set up and if so how many?

**Comment by SueSmith** [comment]
Am checking in case there's some factor I'm not aware of but I believe you should be able to access three integrations with a free account. I will also add a note to the docs just to clarify.

**Comment by sulaimaan26** [comment]
> Hi there, can I ask if you already have other integrations set up and if so how many?

This is the first integration i am going to create and i don't have any other integrations.

**Comment by SueSmith** [comment]
Hi @sulaimaan26, apologies for the confusion, I just had confirmation that the backup options are only available on Postman Team, Business, and Enterprise plans. We are actually in the process of updating the docs now so should at least avoid this for future readers! 😅

**Comment by sulaimaan26** [comment]
Thank You for your valuable response and also change the CTA "View details" to Upgrade
![image](https://user-images.githubusercontent.com/49139974/73743595-8be24000-4714-11ea-84f4-148d7a0ce7ad.png)
