### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2154]
<img width="608" alt="update-dependencies" src="https://user-images.githubusercontent.com/4358288/73674401-4450ab00-4665-11ea-82d2-1aabb66a204d.png">

When running the build, a notification that we need to update our dependencies comes back with "7 vulnerabilities" (at time of writing.)

Our SLA is zero vulnerabilities (especially the Moderate and High ones).

**Comment by ch264** [comment]
@tristandenyer, I could update the vulnerabilites except for gatsby@2.19.12. 
I will have to take a closer look at that one

**Comment by ch264** [comment]
I fixed vulnerabilities from 2000 down to 12 low. I will keep an eye on them.
