### ISSUE TITLE
Google Fonts - Performance enhancement

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2161]
Performance enhancement: 

download Roboto and Open Sans and run them through https://www.fontsquirrel.com/tools/webfont-generator to optimise font.

Check if Google Fonts are being cached.

**Comment by ch264** [comment]
https://fonts.google.com/

**Comment by ch264** [comment]
@tristandenyer . Gatsby has a prefetch plugin. Could this be an option? 
https://www.gatsbyjs.org/packages/gatsby-plugin-prefetch-google-fonts/

**Comment by tristandenyer** [comment]
@ch264 Yes!
