### ISSUE TITLE
Documentation not Updated for PFX client certs

### ISSUE THREAD

**Issue by urizark1** [postmanlabs/postman-docs#2163]
Postman documentation continues to state that  PFX files are not supported for Client Certs this is obviously incorrect as the latest application does indeed have the option to upload a .pfx file

**Comment by arlemi** [comment]
Hey @urizark1, thanks for spotting this. I think the whole Certificates page on the Learning Center needs some love, I'll try to get to that over the next couple weeks. :)

**Comment by jkonrath-postman** [comment]
Internally assigned as TW-73, I'm taking a look.

**Comment by jkonrath-postman** [comment]
It will get fixed internally with TW-73.

**Comment by mark-anthony-postman** [comment]
Information about PFX certificate files has been added to the "Working with certificates" page
