### ISSUE TITLE
command_line_integration_with_newman shows 404

### ISSUE THREAD

**Issue by jsooter** [postmanlabs/postman-docs#2166]
I google search for "postman newman environment variables" returns the following page as the top result but it shows a 404:

https://learning.postman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman/

**Comment by SueSmith** [comment]
Hi @jsooter! Thanks for reporting. That looks like a link to legacy docs, I'll add a redirect - @ch264 do you know if we're able to add redirects with wildcards at all e.g. so we could redirect everyone landing in /v6 to current docs?
