### ISSUE TITLE
adjust navbar layout in mobile view

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2171]
adjust navbar in mobile view to move hamburger menu to same line as logo and text. 

expected outcome: 

<img width="488" alt="Screen Shot 2020-02-06 at 11 54 15 AM" src="https://user-images.githubusercontent.com/36343528/73973439-694c5480-48d7-11ea-84d1-ea11eb6a32b4.png">

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by ch264** [comment]
awesome @theashraf. Thanks for contributing!

**Comment by adrijshikhar** [comment]
@theashraf are you still working on this and if he is not then, @ch264 can i work on this?

**Comment by ch264** [comment]
hey @adrijshikhar, yes please go ahead.

**Comment by ch264** [comment]
PR is in
