### ISSUE TITLE
adjust landing page video width

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2172]
The landing page video needs to be adjusted in mobile view to be the same width as the cards above.

Current state: 
![Image from iOS](https://user-images.githubusercontent.com/36343528/73973858-3bb3db00-48d8-11ea-8b19-e6c2deb2b154.png)

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by ch264** [comment]
Thank you @theashraf. We look forward to your PR

**Comment by Shivansh2407** [comment]
Please let me know which file to look for ? I would like to help in fixing this issue

**Comment by ch264** [comment]
Hi @Shivansh2407, Thanks for offering to contribute. 
The landing page is in src/pages/index.jsx. 
The video needs to be the same width as as the cards above in mobile view. 

You can feel free to put me as a reviewer when you create your PR.

**Comment by VibhorCodecianGupta** [comment]
@ch264 #2243 attempts a fix
