### ISSUE TITLE
Add the .replaceIn() function to the Sandbox API reference page

### ISSUE THREAD

**Issue by DannyDainton** [postmanlabs/postman-docs#2181]
The `.replaceIn("{{...}}")` function was added a while back (v7.6.0) and we didn't update the learning centre docs to include it. It's a helpful function that folks could use but I fear they are not, due to not seeing it listed anywhere. 😢 

It can be added to this page with all the other variable (collectionVariables, globals, environment, variables, etc.) functions:
https://learning.postman.com/docs/postman/scripts/postman-sandbox-api-reference/

The `.replaceIn("{{var_name}}")` function can be used in `Pre-request Scripts` and `Tests` to resolve the `{{...}}` type syntax, as that previously could not be used in the Sandbox. This becomes useful for creating local variables from the built-in random data variables....as well as more practical things 🤓 

Here's a really poor example:

```
let userName = pm.variables.replaceIn("{{$randomFullName}}");

console.log(userName);
```

**Comment by SueSmith** [comment]
Thanks @DannyDainton added support-reported label so that we prioritise this even though you aren't support, you have tons of interactions with community, so.. 🙂

**Comment by SueSmith** [comment]
Both opened and fixed by yourself @DannyDainton lol - we good to close here?

**Comment by DannyDainton** [comment]
Yep - fine by me 🏆
