### ISSUE TITLE
Feature Request - Set default example language

### ISSUE THREAD

**Issue by zanderwar** [postmanlabs/postman-docs#2184]
It would be a nice feature to be able to specify a default language for sample code. Equally it would be nice to be able to remove some languages from the list.

![image](https://user-images.githubusercontent.com/13566916/74499079-5c121400-4f2e-11ea-856d-04d7ee6bfc38.png)

**Comment by SueSmith** [comment]
Hi @zanderwar! 👋 This is actually the repo for the Postman Learning Center, I believe you want the app support repo: https://github.com/postmanlabs/postman-app-support/issues
