### ISSUE TITLE
Broken link in "Validating Requests Against Schema" page

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2193]
The link to "Generate it from a schema" within: https://learning.postman.com/docs/postman/sending-api-requests/validating-requests-against-schema/#validating-requests is broken.

Screenshot:

<img width="669" alt="Screenshot 2020-02-20 at 10 58 20 PM" src="https://user-images.githubusercontent.com/47771757/74961712-86833600-5434-11ea-880a-f8ec22b2e7d7.png">

**Comment by arlemi** [comment]
@Raj-postman Thanks, will fix that ASAP!
