### ISSUE TITLE
Improvement in footer's UI

### ISSUE THREAD

**Issue by abhisheknaiidu** [postmanlabs/postman-docs#2203]
The Social Links and the Copyright Content should be sticked to bottom of the Index Page, to get the better User Interface and Experience. It needs to improved in both the Desktop and Mobile versions!

In Desktop : 

![p2](https://user-images.githubusercontent.com/55599878/75207548-0c89de80-579f-11ea-8aac-03d7b4630147.png)

In Mobile :

![p3](https://user-images.githubusercontent.com/55599878/75207576-275c5300-579f-11ea-8f26-280eaff8abba.png)

**Comment by ch264** [comment]
Hey @abhisheknaiidu, thank you for opening a ticket. 
I will forward this to our design team and close the ticket on this repo.
