### ISSUE TITLE
ubuntu，input text intorequest body raw

### ISSUE THREAD

**Issue by insight1989** [postmanlabs/postman-docs#2215]

**Comment by insight1989** [comment]
ubuntu，input text intorequest body raw ，mouse offset the focus on text。Incorrect CSS style may be is "fonts family" ,please fix it .

**Comment by arlemi** [comment]
@insight1989 For bug reports please open an issue here https://github.com/postmanlabs/postman-app-support and follow the template for reporting a bug.
