### ISSUE TITLE
Migrate images from GitHub to our S3 bucket

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2231]
I am seeing 133 images in our docs that are being sourced and served from GitHub (`githubusercontent.com`). We have a policy to source images from our S3 bucket, and srve via CDN. This:
— allows us to use our CDN (a +1 for speeding up page load times)
— allows us to use proper and useful file-naming (a +1 for SEO)
— places all of our content in one place (a +1 for DX)
— allows us to migrate our content easily (a +1 for DX)

(Postman Team) If you do not have access to the S3 bucket, please email me.

Tasks:
— migrate all images being served from GitHUb to S3 bucket.
— use `https://assets.postman.com/postman-docs/` URL to ensure it goes through CDN

<img width="716" alt="Screen Shot 2020-03-08 at 8 05 27 PM" src="https://user-images.githubusercontent.com/4358288/76179723-176a4900-6179-11ea-8e80-bd3c12a70505.png">

**Comment by ch264** [comment]
@tristandenyer a lot of these images are from the legacy v5 docs folder. Do you also want us to change those? 

I can get started on this ticket for the current  version.

**Comment by ch264** [comment]
PR is open. I added all images of the recent docs into AWS and linked them up.
