### ISSUE TITLE
A guide describing how admins/users would go about migrating data into another team

### ISSUE THREAD

**Issue by carolin-postman** [postmanlabs/postman-docs#2235]
As a user migrating to another team or an Admin facilitating the process, I'd like to know what are the steps and expectations that come with migrating data from one team into another. What does the Admin on both teams need to know when data is exported and re-imported into the new team?

  | Yes | No
-- | -- | --
Collections | x |  
Environments | x |  
Globals | x |  
Monitors |   | x
Roles/Permissions at collection/workspace level (reassign roles in new Postman instance as needed) |   | x
Workspaces |   | x
Mock servers (Collections and examples requests will be backed up, so just the server instance itself will need to be re-created) |   | x
Published documentation (The new documentation URLs will be generated when Collections are re-published from your team pages) |   | x
API Schemas (re-imported from OAS/Swagger files.) |   | x

notes:

Upon import into a team workspace, the user who imported the collections is automatically the Collection Editor and everyone else on the team is a viewer.

**Comment by jkonrath-postman** [comment]
Was closed by PR #2569
