### ISSUE TITLE
Can I search a URL  in the Collection ?

### ISSUE THREAD

**Issue by luoyexiaohe** [postmanlabs/postman-docs#2240]
for example :
a few URLs in the Collection , one of them is "www.google.com". And Postman would help me to find it when I key "google" in.

**Comment by DannyDainton** [comment]
Hey @luoyexiaohe,

This is the repo for the Postman documentation, would you be able to open up a topic on our community site with your question please?

The more details you provide, the quicker we can help with a solution to that problem. 😁 

community.postman.com

**Comment by luoyexiaohe** [comment]
thank you , I'll try
