### ISSUE TITLE
Add API tab to navigation page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2242]
https://learning.postman.com/docs/postman/launching-postman/navigating-postman/

Sidebar docs currently describe **History** and **Collections** tabs. Should also include **APIs**.

**Comment by DannyDainton** [comment]
@loopDelicious I think we would probably need to do a full sweep through all the details on that page and not just adding the info for the API tab :(

Instantly, I can see that the Console images are slightly outdated after some recent UI changes, we don't have the `cog` option in the bottom right, it's just the checkboxes for the options that were hidden by the cog. Also, the Header toolbar image has a few things added and removed. Lots more too :(

**Comment by SueSmith** [comment]
This doc is probably going to be subsumed by others when we restructure btw, need to move away from describing the ui and onto walking people through tasks.. 😬

**Comment by loopDelicious** [comment]
Also there's a typo in this header: https://learning.postman.com/docs/postman/launching-postman/navigating-postman/#mulitple-rows

**Comment by HarshaVardhan16** [comment]
Hey,
I am interested in working. Guide me, so that I can understand the project better.

**Comment by HeroicHitesh** [comment]
@loopDelicious @SueSmith Is this issue still relevant? If yes, let me know the latest description so, I can work on it, as I am unable to get if the restructuring is done or not.

**Comment by jkonrath-postman** [comment]
This was restructured a bit ago. The top of the https://learning.postman.com/docs/getting-started/navigating-postman/ topic now has a list of items in the left sidebar, which go to the relevant pages within their sections.
