### ISSUE TITLE
Documentation on resources and their monthly reset.

### ISSUE THREAD

**Issue by SabriH10** [postmanlabs/postman-docs#2255]
Currently, the app doesn't explicitly distinguish between resources that are reset monthly( monitor runs, documentation views, API key hits) and resources that are fixed regardless ( number of API's created). 
The only information I was able to find so far is https://blog.postman.com/2020/01/24/what-does-max-of-apis-mean-in-postman/ which doesn't specifically address this. 

An [issue](https://github.com/postmanlabs/postman-app-support/issues/8182) was also opened in #app-support, however, updating the docs would also help.

For context:
<img width="337" alt="Screen Shot 2020-03-16 at 11 37 23 AM" src="https://user-images.githubusercontent.com/62078336/76778897-f14c3680-6780-11ea-90e9-486241a72d44.png">
https://web.postman.co/usage reflect the resources in question.

**Comment by jkonrath-postman** [comment]
The docs at `https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#usage-limit` mention going to `https://postman.postman.co/billing/add-ons/overview` for more details, which is fine.

`https://postman.postman.co/billing/add-ons/overview` now clearly shows when limits are reset.
