### ISSUE TITLE
Add note for on team invite link expirations and limits

### ISSUE THREAD

**Issue by yiantseng** [postmanlabs/postman-docs#2262]
There should be a note on what the team invite link limits and expirations are:
https://learning.postman.com/docs/postman/collaboration/managing-your-team/#inviting-to-a-team

Perhaps also more documentation on where to navigate to see your expired links

**Comment by jkonrath-postman** [comment]
https://learning.postman.com/docs/administration/managing-your-team/managing-your-team/#managing-invitations now describes where to see invite link expiration dates.
