### ISSUE TITLE
Wikipedia like popups in Postman Learning Centre

### ISSUE THREAD

**Issue by ProBeta1** [postmanlabs/postman-docs#2283]
**Is your feature request related to a problem? Please describe.**
The Documentations often have links which redirect to related content about the current explanations. It sometimes become overwhelming to open so many tabs for just knowing a two-line definition. The contents are arranged in a sorted order for sure , but if someone just needs to learn about something specific urgently , then it becomes a trouble to go through each blog.

**Describe the solution you'd like**
A cute popup on hovering the mouse over the urls , describing the content of the page they are directing to.

**Describe alternatives you've considered**
Clicking the links and manually switching to those pages.

**Additional context**
https://en.wikipedia.org/wiki/Wikipedia:Tools/Navigation_popups

**Comment by jkonrath-postman** [comment]
Hi @ProBeta1  - thanks for the input, and sorry for the delay. We're always working to continually updating the design and architecture of the Learning Center. I'll put your suggestion on our design list so we can consider it in the future. Thanks again!
