### ISSUE TITLE
pm object is missing when trying to set the security key for encryption

### ISSUE THREAD

**Issue by dan-vidoni** [postmanlabs/postman-docs#2307]
**How to reproduce**

- right click **Postman Interceptor** chrome extension
- Inspect Pop-up
- Console
- try to run `pm.interceptorBridge.setKey("<your key here>")` as shown in https://learning.postman.com/docs/postman/sending-api-requests/interceptor/#security

``` 
VM1222:1 Uncaught ReferenceError: pm is not defined

**Comment by abhijitkane** [comment]
@dan-vidoni Thanks for catching this. This broke during our latest release, unfortunately. We're working on a hotfix and will get a new version of the Interceptor up by tomorrow. I'll keep you posted!

**Comment by abhijitkane** [comment]
@dan-vidoni Apologies for the delay - the latest Interceptor extension (1.0.2) should support this.

**Comment by dan-vidoni** [comment]
> @dan-vidoni Apologies for the delay - the latest Interceptor extension (1.0.2) should support this. Let me know if you face any issues setting the key.

yep, works 👍 thanks a lot!
