### ISSUE TITLE
Publish Collection with multiple sets of Environment Variables

### ISSUE THREAD

**Issue by deanlyoung** [postmanlabs/postman-docs#2318]
<img width="1046" alt="environment-variables" src="https://user-images.githubusercontent.com/2523456/79293263-1dde9580-7e88-11ea-8c9e-333a1114cd5f.png">

**Comment by SueSmith** [comment]
Hi @deanlyoung! This is the Postman Learning Center repo - if it's a feature request you're looking to make you can do that on the [support repo](https://github.com/postmanlabs/postman-app-support/). Hope that helps!
