### ISSUE TITLE
Search vs Find and Replace

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2330]
Search is a deprecated feature as noted at the top of this page: https://learning.postman.com/docs/postman/team-library/searching/

This page describes the Find and Replace feature: https://learning.postman.com/docs/postman/find-replace/

1. Since Search and Find are similar concepts in a user's mind, these pages could reference each other by mentioning and linking to the different use cases.
1. Also, the Search page includes unique information that would be helpful to include or reference from the Find and Replace page - in the context of "Find".
1. I'm unclear if Find is limited to finding within the selected workspace.
1. If I type "Search", the search page shows up before find as it's a more relevant match by keyword. Consider optimizing search by prioritizing non-deprecated features.

**Comment by jkonrath-postman** [comment]
Both of these pages are gone, and https://learning.postman.com/docs/getting-started/navigating-postman/ describes Universal Search now.
