### ISSUE TITLE
Update docs for single column in publication flow

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#2336]
@JJGothard re this comment

https://github.com/postmanlabs/postman-docs/pull/2316#issuecomment-615240968

There's now an option to choose a default during publication so if we can get that updated too that would be great!

![Screenshot 2020-04-21 at 14 04 11](https://user-images.githubusercontent.com/6666370/79869268-06982e80-83d9-11ea-96c5-023815c7d4a5.jpg)

**Comment by JJGothard** [comment]
You bet! I was looking for that last week, but it wasn't in prod... I'll take care of it today 👍
