### ISSUE TITLE
How is the documentation structured? 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#2344]
**Suggestion** 
Can we better explain in our documentation the way the documentation is automatically created and structured? 

**Support reported**
A user was confused to see the example request on the right side (right column) and thought it was an issue as he expected to see it on the left side (left column). 

<img width="1405" alt="Screenshot 2020-04-23 at 09 52 42" src="https://user-images.githubusercontent.com/47351631/80079692-87296d00-8548-11ea-8c67-b879a5dc7c55.png">

**Location in the Learning Center**
Postman > API Documentation > Documenting your API > [Including detail in your docs](https://learning.postman.com/docs/postman/api-documentation/documenting-your-api/#including-detail-in-your-docs)

**Content suggestion**

The documentation is automatically generated and is structured in two columns. 
The left side includes the detail for each collection/request and indicates
- The verb
- The URL
- The description
- The body and parameter descriptions
- Headers request 

The right side includes 
- The code for the request
- The sample responses from your saved examples

**Comment by SueSmith** [comment]
@cyrielle-hada I would say at least some of this detail is in the [authoring page](https://learning.postman.com/docs/postman/api-documentation/authoring-your-documentation/) which is linked from that section but will pass this onto @JJGothard who is on the docs squad for any potential improvements!

**Comment by SueSmith** [comment]
Hopefully this is fixed by #2419
