### ISSUE TITLE
Request to link "Settings" section to "Variables" page

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2345]
Can we link the "Automatically persist variable values" section from below page - eighth point under section General settings to the variables documentation which is more relevant in terms of users workflow.

From: "https://learning.postman.com/docs/postman/launching-postman/settings"
To: "https://learning.postman.com/docs/postman/variables-and-environments/variables/#sessions-in-postman"

Or since its a small section, add them again here?

**Comment by SueSmith** [comment]
Thanks @Raj-postman - the settings page is badly needing some attention (we'll probably get rid of it when we restructure and move the info into the relevant sections) but can certainly add a more relevant link here for now

**Comment by Raj-postman** [comment]
Yes, Thank you! - that should help :)

**Comment by Raj-postman** [comment]
Sorry totally missed this 😓@SueSmith 

Yes, that is right! 🎉

**Comment by SueSmith** [comment]
@Raj-postman no probs! Thanks for checking. 🙂
