### ISSUE TITLE
Clarify docs edits and explore listings

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#2348]
Since api network / template listing description is initially pulled from collection docs markdown when you publish and enable discovery, I hadn't realised that docs edits will not automatically be reflected in the template / network listing - can we add a note to clarify that you need to update your explore.postman.com details manually? e.g. in here https://learning.postman.com/docs/postman/api-documentation/publishing-your-docs/ please give me a shout if that isn't enough info!

**Comment by JJGothard** [comment]
Hi @SueSmith ! You bet! Thanks!
