### ISSUE TITLE
Typo in Design And Develop APIs > The API Workflow

### ISSUE THREAD

**Issue by louisfisch** [postmanlabs/postman-docs#2349]
In the Next Steps section of the Design And Develop APIs > The API Workflow documentation there is a list of links and the last one reads "Validating elemenst against schema". I believe it should be "Validating elements against schema".

**Comment by SueSmith** [comment]
Thanks for reporting @louisfisch! This might be a good first issue for someone who wants to try opening a pull request to contribute to the docs so have added a label for that. 🙂

**Comment by louisfisch** [comment]
My pleasure. Actually I opened a pull request to fix this issue. But I think GitHub is experiencing some issues and the checks can't run.

**Comment by louisfisch** [comment]
I am closing this issue because the merged pull request #2350 fixed this issue.

**Comment by SueSmith** [comment]
Oops hadn't clicked we weren't closing this one automatically - thanks @louisfisch!
