### ISSUE TITLE
"Run in Postman" docs - Extra steps required on Linux systems

### ISSUE THREAD

**Issue by harryi3t** [postmanlabs/postman-docs#2351]
For "Run in Postman" button to work on Linux systems, there is an extra step required. Users would have to create the desktop file. If the app is installed using `snap`, then it is not required, since snap will add the desktop file.

These instructions were actually present in the blog post when this feature was launched
https://blog.postman.com/run-in-postman-is-now-available-for-linux/
![image](https://user-images.githubusercontent.com/5207331/80129335-875f5200-85b4-11ea-802c-edb2e219616a.png)

I think this should be in the docs as well
https://learning.postman.com/docs/postman-for-publishers/run-in-postman/using-run-button/

**Comment by jkonrath-postman** [comment]
@harryi3t sorry for the long delay - can you confirm if this is still true? I'm not sure if the new Run in Postman button released recently fixes this. Thanks!

**Comment by jkonrath-postman** [comment]
This looks like a stale issue, so I'll close it. Let me know if this is still valid and I can reopen - thanks!
