### ISSUE TITLE
Typo -https://www.postman.com/features/mock-api

### ISSUE THREAD

**Issue by ash007-postman** [postmanlabs/postman-docs#2356]
Compliment' is used incorrectly it should be Complement.
https://www.postman.com/features/mock-api

![Screenshot 2020-04-27 at 3 59 24 PM](https://user-images.githubusercontent.com/41741228/80362809-e79a1080-88a0-11ea-9bab-11315aead782.png)

**Comment by SueSmith** [comment]
Hi @ash007-postman! This page isn't actually part of the docs site - @tristandenyer is there somewhere in particular issues on postman.com should be reported?

**Comment by tristandenyer** [comment]
I'll port this ticket over to Jira. (It's fine it got mentioned here—rather be able to hear about this and have to port over and close it than not know about it at all. Thanks!)
