### ISSUE TITLE
404 image

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2357]
https://assets.postman.com/postman-docs/WS-certificates.gif

should be 

https://assets.postman.com/postman-docs/WS-certificates.png

**Comment by SueSmith** [comment]
Image is used in this page/section https://learning.postman.com/docs/postman/design-and-develop-apis/validating-elements-against-schema/#validating-elements

**Comment by HarshaVardhan16** [comment]
Hey,
I am interested in working. Guide me, so that I can understand the project better.
