### ISSUE TITLE
v6 redirects are not working

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2361]
This is one of our most popular templates, and all links in the description are 404ing: https://explore.postman.com/templates/198/intro-to-writing-tests---with-examples 

Can you please update the old v6 page redirects to existing pages?

**Comment by ch264** [comment]
all but one redirects have been fixed. The one pending is will be fixed in the next release.

**Comment by tristandenyer** [comment]
@ch264 did this get resolved?

**Comment by ch264** [comment]
@tristandenyer yes, all links do not 404 anymore
