### ISSUE TITLE
Support for permalinks / pretty URLs

### ISSUE THREAD

**Issue by kepikoi** [postmanlabs/postman-docs#2365]
Right now hot-linking to different sections of a documentation is handled via non-descriptive URL hashes (e.g. https://docs.tangany.com/?version=9bc7df56-b03b-4b25-9697-59aea9774174#0d926cca-e0bd-4045-864d-18845425adfe) It would be great to use pretty and persistent  URLs when pointing to different sections based on the available directory structure in a collection (e.g. https://docs.tangany.com/latest/ethereum/wallet/get-balance or https://docs.tangany.com/1.4.0/ethereum/wallet/get-balance)

**Comment by SueSmith** [comment]
Hi @kepikoi! This is actually the Postman learning center repo - I believe you want the app support repo: https://github.com/postmanlabs/postman-app-support/ 🙂

**Comment by kepikoi** [comment]
Hi @SueSmith thank you for the heads up. Can you please move the issue there or do I need to open a new one? Thank you

**Comment by SueSmith** [comment]
@kepikoi no probs, I'm not able to move it so if you don't mind opening a new one that would be great - it might also be worth checking first in case there are any relevant exisiting issues in which case you can add your voice there..!

**Comment by kepikoi** [comment]
@SueSmith thanks again. I will close this one.
