### ISSUE TITLE
Docs discoverability clarification

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#2372]
@JJGothard I had a note from Ryan (cust success) re this:

> Unless you use a custom domain, people will not be able to search for or find your documentation online. By default your documentation will only be discoverable to people you explicitly share the URL with, or people browsing the API Network / Postman Templates (if you chose that option during publication).

In https://learning.postman.com/docs/postman/api-documentation/publishing-your-docs/

I can't remember the history but it seems it isn't actually accurate, i.e. you can find docs for example via google search. Think we could either remove it or reframe to just something indicating adding to api network makes your docs more discoverable..?

**Comment by JJGothard** [comment]
I'm on it (like a car bonnet)!

**Comment by JJGothard** [comment]
Just want to give a status update here, @SueSmith , I've tried publishing docs with and without a custom domain, and what I'm finding is that discoverability is a challenge in genera, and I'm not seeing that one works better than the other. I'm going to dig a little deeper with Raja this week to see what the issue is.

**Comment by SueSmith** [comment]
As per guidance from Ryan who originally reported this, you can discover docs e.g. via google (try a search for "meraki postman") without a custom domain so we're good to go ahead and update to clarify - discoverability isn't something you can test quickly because it'll take time and depend on factors outwith your control.. I would say something along the lines of custom domain / api network making your docs _more_ discoverable, but remove the bit about them _not_ being discoverable without these. If we can get this updated fairly quickly that would be ideal because it's misleading the way we have it atm. 🙂

**Comment by JJGothard** [comment]
Got it: will move ahead, then 👌
