### ISSUE TITLE
Add CSV format for data files

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2373]
How to format the data file is very important information for being able to loop through a data file.

1. We used to include a sample of both CSV and JSON. Suggest including samples of both data files (currently just JSON), as well as show an image or code snippet demonstrating the data format (currently just JSON and user must click through to the sample)

2. For the existing JSON example:
> Download the sample data file and select it in the Runner also.

Suggest either posting a link that downloads the file automatically, or add more information telling the user how to download from the link

**Comment by SueSmith** [comment]
@loopDelicious sure, we updated the page in part because the examples weren't actually working, can certainly add these options 👍

**Comment by jkonrath-postman** [comment]
The example collection (https://assets.postman.com/postman-docs/58533790.json) and the JSON file (https://assets.postman.com/postman-docs/58702589.json) did work for me, although maybe we should rework this topic entirely and use a Run in Postman button somehow? 

I added that to TW-78, the inventory for public workspaces that Sowmya's working on.

For CSV, the original sample file is at https://assets.postman.com/postman-docs/test_data_file.csv - looking at v5 docs, I don't think we ever had a collection with a test script to parse CSV. When we do the above, maybe add a second request to the collection to read CSV?

**Comment by sambhavsaxena** [comment]
Can I work on this issue?

**Comment by jkonrath-postman** [comment]
We already added some commentary on how to format CSV files, so I'm closing this.
