### ISSUE TITLE
Add note about chrome blocking pop-up for OAuth2

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/postman-docs#2384]
Trying to use the default browser for generating a OAuth2 token may get blocked by the browser as it's a pop-up, we may want to add a quick note in the docs to let users know about it. Reported here:
See https://github.com/postmanlabs/postman-app-support/issues/7592#issuecomment-628180308

**Comment by jkonrath-postman** [comment]
I'm not sure when this was changed, but the docs at https://learning.postman.com/docs/sending-requests/authorization/ now say "If you opt to authorize using the browser, make sure pop-ups are disabled for the callback URL, otherwise it will not work."
