### ISSUE TITLE
Request to add details into Archiving page

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2401]
Under the section: Recovering collections, adding the below data would help the user get a clear context while importing the details.

> **Note: archive.json is not a collection that is supposed to be imported, it's just an index/directory of other files present in that zip. The collections folder contains all the files that need to be imported**

Document: https://learning.postman.com/docs/postman/collaboration/collaboration-intro/#recovering-your-archived-collections

Video for reference: https://www.youtube.com/watch?v=Bei42qAtdLs

**Comment by jkonrath-postman** [comment]
Added a note - see the linked PR for details.
