### ISSUE TITLE
Add Twitch icon to social icons in LC footer

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2412]
Extend the social icons to include our Twitch profile: https://www.twitch.tv/getpostman

I attached their brand SVG. (Should reuse the SVG from what we use in WWW footer.)

[twitch-brand-assets.zip](https://github.com/postmanlabs/postman-docs/files/4684477/twitch-brand-assets.zip)

**Comment by DannyDainton** [comment]
Hey @tristandenyer / @mclausaudio 

I noticed this _jumpy_ action happening on hover - Are you able to take a look at this when adding the new Twitch Icon?

![Jumpy](https://user-images.githubusercontent.com/17089546/82984275-be78b700-9fe9-11ea-9be2-6e0d1418b7c7.gif)

**Comment by SueSmith** [comment]
I believe this issue was fixed by #2417 👍
