### ISSUE TITLE
add redirects for the following links from blog

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2420]
in /redirects.json add redirects for the following urls: 

https://learning.postman.com/docs/postman_for_publishers/run_button/creating_run_button/
https://learning.postman.com/docs/postman/environments_and_globals/sessions
https://learning.postman.com/docs/postman/collections/version_control/
https://learning.postman.com/docs/postman_for_publishers/run_button/creating_run_button/
https://learning.postman.com/docs/postman/collections/data_formats/

**Comment by uchemukolo** [comment]
Hi @ch264 
This is my first time contributing here, I will like to work on this

**Comment by ch264** [comment]
@uchemukolo awesome! Thanks for contributing

**Comment by uchemukolo** [comment]
@ch264 I need some clarifications,
In the `redirects.json` file i can see objects with keys `from` and `to` in an array like this
```{
    "from": "/docs/postman-for-publishers/run-in-postman/collections-run-button/",
    "to": "/docs/postman-for-publishers/run-in-postman/creating-run-button/"
  }```
For the new URLs to be added, will `from` and `to` have the same values?

**Comment by ch264** [comment]
@uchemukolo yes that is correct. The urls in the ticket have to be added to the array of redirects. 

So for example: for the first url reported: https://learning.postman.com/docs/postman_for_publishers/run_button/creating_run_button/

Would need to be added to the redirects.json file like so: 
{
"from": "/docs/postman_for_publishers/run_button/creating_run_button/",
"to": "/docs/postman-for-publishers/run-in-postman/creating-run-button/"
}

You can use the left nav on `https://learning.postman.com/` to find the new URLs. 

Hope this helps

**Comment by uchemukolo** [comment]
Yes @ch264 
Very helpful
