### ISSUE TITLE
Guidelines section for Internal API Network is misleading

### ISSUE THREAD

**Issue by bhargavkaranam** [postmanlabs/postman-docs#2428]
![image](https://user-images.githubusercontent.com/8963298/83403645-b6c07480-a426-11ea-9e1c-a7d7fcad1b41.png)

The following part, for a user, sounds like everyone in the team needs to be given a Viewer role and that having a Viewer role is enough to add to the Network. I think we can improve the messaging to convey that the user adding to the Network should have Editor role on the API and the Team needs to have a Viewer/Editor role.

`View access is the minimum permission you need to grant your teammates to be able to add to the network. You can choose to give members of your team edit access.`

**Comment by SueSmith** [comment]
cc @JJGothard issue with internal network info ^^

**Comment by SueSmith** [comment]
@JJGothard as per a convo I'm seeing in the api network slack channel can we also clarify that unlike the external network you share apis specifically and not collections (as with the public network) - from the slack channel:
> You need to attach it to an API
> You can't publish individual collections
> Attach a doc to an API in the builder
> then publish the whole API

**Comment by JJGothard** [comment]
@SueSmith , we def can. I started working on this yesterday (plus updating that screenshot for the public network). The update I'm making to the content is: The guidelines changes about editor/viewer roles; that collections can't be used to add to the network, you have to have built the API. I'll look into the attaching a doc -- that wasn't part of the flow I experienced when I published to the network while everything was on beta/stage.

**Comment by SueSmith** [comment]
I don't think you need to worry about the attaching a doc bit, think it was just an example - but you don't need to have _built_ the api (I'd be careful with the language there), it just needs to be in the api builder in postman if that makes sense.

**Comment by JJGothard** [comment]
That does make sense. 👍
