### ISSUE TITLE
FAQ on reasons for seeing invite URL expire or get invalid

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#2429]
**Summary**
Surface reasons why users may see the Invalid URL error message upon accepting the invite or clicking the URL.

**Support reported**
Users write in after seeing the below error when accepting an email invite or clicking on the invite URL.

![image001](https://user-images.githubusercontent.com/47351631/83421958-bfae4780-a420-11ea-8e2d-e392093b740d.png)

**Content suggestion**
Adding a FAQ section in Managing your team > [Invites](https://learning.postman.com/docs/postman/collaboration/managing-your-team/#invites) of the Learning Center. 

Why do I get the error `Sorry! You seem to have an invalid or expired invite code`? 

- The team Admin has canceled the invite

- The invite has already been accepted 

- The Link invite has expired. _Please note that the email invite doesn't have any expiry._

**Comment by jkonrath-postman** [comment]
There's a recent FAQ here: https://support.postman.com/hc/en-us/articles/360019139274-Invite-link-to-team-does-not-work- but it doesn't address the three things listed above. 

Let me find out who wrote that and maybe we can add to that article.

**Comment by jkonrath-postman** [comment]
Not sure when this was fixed in the HC, but the article at the above link is correct now.
