### ISSUE TITLE
Add system requirements for using Postman 

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#2430]
**Suggestions**

- Specify at the beginning of the Learning Center page[ Installation and updates](https://learning.postman.com/docs/postman/launching-postman/installation-and-updates/) that Postman is built on Electron and the system requirements will depend on [what is supported by Electron](https://www.electronjs.org/docs/tutorial/support#linux) for each platform.

- Update the minimum requirements for macOS - the minimum macOS version supported is macOS 10.10 (Yosemite).

- For Linux installation - add a mention that the support of certain Linux distributions depends on whether they're supported by Electron or not. [Their documentation](https://www.electronjs.org/docs/tutorial/support#linux) states that _only Ubuntu 12.04 is guaranteed to work_

**Comment by fakela** [comment]
@SueSmith i would work on this

**Comment by jkonrath-postman** [comment]
This was fixed in commit https://github.com/postmanlabs/postman-docs/commit/6efead5659848803a9550e6ac7ba824541503a18
