### ISSUE TITLE
add redirects to /redirects.json

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2433]
These to urls are going to 404 and require a redirect in /redirects.json

https://learning.postman.com/docs/postman/collections/data_formats/

**Comment by HarshaVardhan16** [comment]
Hey,
I am interested in working. Guide me, so that I can understand the project better. Thanks.

**Comment by ch264** [comment]
Hey @HarshaVardhan16, thank you for contributing.

The url in the ticket has to be added to the array of redirects in /redirects.json.
So for example: https://learning.postman.com/docs/postman/collections/data_formats/

Would need to be added to the redirects.json file like so:
```
{
"from": "/docs/postman/collections/data_formats/",
"to": "<appropriate path>"
}
```

You can use the left nav on https://learning.postman.com/ to find the new URL.

Hope this helps

**Comment by HarshaVardhan16** [comment]
Hey,
I have created a pull request, check it once. Let me know.

**Comment by HarshaVardhan16** [comment]
> Hey @HarshaVardhan16, thank you for contributing.
> 
> The url in the ticket has to be added to the array of redirects in /redirects.json.
> So for example: https://learning.postman.com/docs/postman/collections/data_formats/
> 
> Would need to be added to the redirects.json file like so:
> 
> ```
> {
> "from": "/docs/postman/collections/data_formats/",
> "to": "<appropriate path>"
> }
> ```
> 
> You can use the left nav on https://learning.postman.com/ to find the new URL.
> 
> Hope this helps

Hey,
I have created a pull request, check it once. Let me know.

**Comment by SueSmith** [comment]
@ch264 something weird seems to be going on here, there is a redirect for that url already.. 🤔

**Comment by HarshaVardhan16** [comment]
@SueSmith but why is it showing 404 error then? I knew there was a already a redirect.

**Comment by SueSmith** [comment]
I am not sure 🙃

**Comment by SueSmith** [comment]
So we discovered the problem, redirects hadn't been deployed but are now working 🎉
