### ISSUE TITLE
FAQs Let’s Encrypt SSL certificates

### ISSUE THREAD

**Issue by cyrielle-hada** [postmanlabs/postman-docs#2444]
**Summary**
Surface Let’s Encrypt SSL certificates expiration information.
- When does it expire?
- What will happen once the certificate expires?
- What to do?

**Support reported**
```
We have a couple of published postman collections. I've noticed that the Postman-managed SSLs from Lets Encrypt will both expire next week. 
- Do they auto-renew? 
- When does that happen normally? 
- Is there any action required from our side?
```
**Learning Center location**
https://learning.postman.com/docs/postman/sending-api-requests/certificates/

**Suggestion**
Add an FAQ to the Certificate doc page and address the following questions.

- **Do I need to renew the certificate?** 
Certificates are renewed automatically, no manual steps are required.

- **How long are these SSL Certificates valid for?**
Certificates are generated with a 90-day expiry date.

- **When does Let’s Encrypt renew SSL certificates for published documentation?**
The certificate gets renewed 7 days before it expires.

**Comment by fakela** [comment]
I would love to work on this
