### ISSUE TITLE
Left navbar is missing hover states

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2469]
When a user hovers over the dark gray text links in left nav, the label should turn to orange (`color: #FF6C37;`)

Also, add `display: block;` to the href so that you don't have to only click on the label, but be able to click anywhere along the horizontal axis of that label, making it a lot easier to engage with.

**Comment by junagao** [comment]
Hi @tristandenyer, I'd like to work on this issue.
