### ISSUE TITLE
Feedback -Update Mock documentation to help beginners

### ISSUE THREAD

**Issue by ash007-postman** [postmanlabs/postman-docs#2488]
**Posting on behalf of a user:**

I hope you can improve part of your documentation on this page: https://learning.postman.com/docs/postman/mock-servers/matching-algorithm/, Chapter 4, Wildcards.

This is not a good description. It's written by someone who knows how it works already. So that one doesn't need to read it. But those of us who don't know it (or at least I) get really confused here. Hope you can improve it.

The details:

You make a query to, say, /computers/5, where 5 is the wildcard (you also use the term "path" elsewhere), how can you get a response including that value (5)? In the above mentioned documentation it seems that if you make the request

/computers/{{computer_id}}

then the response example could be

{

  "computer": "5"

}

if your example is defined as

{

  "computer": "{{computer_id}}"

}

But when you send the request "GET /computers/{{computer_id}} (after having saved the environment variable computer_id with value 5) you'll get back the latter, expecting the primer. That's not a surprise because how should the server know that the client has replaced its local computer_id variable with its value (5) before sending it? The only way that could happen would be either if the client sent some hidden out-of-band data to the server but according to the logs it doesn't, or if the mock server was a local process (which it isn't).

So the documentation is quite confusing. Isn't there some way to just refer to a particular part of the request path in the response example? Something like {{$leaf}} or so, to get the last element of the request URL, with a very good description in the documentation!

The description about the colon before the wild card is also confusing, rather sloppy I'd say. According to it, the above request should be /computers/:{{computer_id}}. Is the colon some special notation used by Postman only?

I see these kinds of documentation mistakes too often: The docs are written by people who already knows anything about the product. Documentation should instead be written by confused rookies who don't know anything about it, or at least be reviewed by them as they try to work their way through it.

**Comment by SueSmith** [comment]
Thanks @ash007-postman! The mock docs badly need an overhaul 😬 but I'm hoping to get stuck into them in the next couple of weeks so will make sure I refer to this feedback.. 😅

**Comment by Raj-postman** [comment]
Hi @jkonrath-postman - Could you also help us by updating the screenshots from the latest version of the application? At the moment, older screenshots cause confusion around using them in UI. Example:

![image](https://user-images.githubusercontent.com/47771757/140016688-508e2ffe-4290-41d4-8133-d8b8f459c78c.png)

Reference: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples

**Comment by jkonrath-postman** [comment]
@Raj-postman - Mark's working on this - see the ticket under TW-121
