### ISSUE TITLE
404 url in /docs/administration/sso/microsoft-adfs

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2491]
https://learning.postman.com/docs/administration/sso/microsoft-adfs/ has 2 404 URLs.

<img width="561" alt="Screen Shot 2020-06-29 at 10 34 48 AM" src="https://user-images.githubusercontent.com/36343528/86037386-29a41780-b9f4-11ea-93e7-bc6cbe6f0294.png">

Both these URLs: http://microsoft.identityserver.web/ go to 404

**Comment by TheCaffeineDev** [comment]
Hi @ch264, these URL's should point to https://docs.microsoft.com/en-us/dotnet/api/microsoft.identityserver.web?view=adfs-2019 this site, right? or it should left blank without any hyperlink?

**Comment by ch264** [comment]
Hey @TheCaffeineDev thanks for looking into this 🙌 
@SueSmith Can you please confirm if above is the correct link?

**Comment by TheCaffeineDev** [comment]
@ch264  the link is correct but I don't think it should be pointed at https://docs.microsoft.com/en-us/dotnet/api/microsoft.identityserver.web?view=adfs-2019 this link. It should be left blank without any hyperlinks.

**Comment by SueSmith** [comment]
Yeah I would lose the links - thanks @TheCaffeineDev!

**Comment by TheCaffeineDev** [comment]
Hi, @SueSmith @ch264 I have created a pull request fixing this issue. Please have a look at it. https://github.com/postmanlabs/postman-docs/pull/2500
