### ISSUE TITLE
Wrong double-quote

### ISSUE THREAD

**Issue by jlecordier** [postmanlabs/postman-docs#2492]
* `pm.variables.set(variableName:String, variableValue:String"):function → void`: Set a local variable with the given value.
should be :
* `pm.variables.set(variableName:String, variableValue:String):function → void`: Set a local variable with the given value.
according to an other example :
* `pm.environment.set(variableName:String, variableValue:String):function`: Sets the variable with the given name and value in the currently selected environment.

**Comment by SARVESHKHANDELWAL** [comment]
Please assign me!!
