### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2508]
![Screen Shot 2020-07-08 at 3 03 50 PM](https://user-images.githubusercontent.com/17693714/86975212-ad64af00-c12c-11ea-888b-9ad96dcfabd8.png)

**Comment by ch264** [comment]
@loopDelicious the favicon shows for me on chrome. Can you confirm which browser you are using?

**Comment by ch264** [comment]
<img width="1005" alt="Screen Shot 2020-07-08 at 10 39 34 AM" src="https://user-images.githubusercontent.com/36343528/86977078-b192cb80-c130-11ea-8c02-d8f87a487af5.png">

**Comment by ch264** [comment]
OK found it, it was a plugin. fix is in
