### ISSUE TITLE
Include header text in search index

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2509]
Looks like we might not be indexing headers in search anymore.

Searching for `console`, displays the Postman console as the last result, even though it's our most popular console, and the page includes "console" in a header.

![Screen Shot 2020-07-08 at 2 53 19 PM](https://user-images.githubusercontent.com/17693714/86977612-d8053680-c131-11ea-8818-07c7856772f5.png)

Also, there's max results displayed, so if we add another page with the console, the Postman console won't be displayed as a result.

**Comment by ch264** [comment]
@loopDelicious I just checked and 'titles' are being indexed by Algolia. This has not changed. 
In the legacy documents there used to be a doc with that had the word 'Console' in it. This doc has now been renamed. 

For max results, this is a design choice and the design team will have to provide us with a new design. There is an open ticket in Jira for this. I will send you the link.

I can look into popularity ranking and check out display of hits again. I agree that the most popular post doc should be on top.

**Comment by loopDelicious** [comment]
Also the links in the Contents section of this page have an extra `/` in them so they're not linking to the sections indicated.

https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#contents

**Comment by ch264** [comment]
@loopDelicious I am not sure I understand. Is this related to Algolia search? 
 When I open the links in the content section, they go to the correct section of the page.
<img width="1111" alt="Screen Shot 2020-07-14 at 1 59 39 PM" src="https://user-images.githubusercontent.com/36343528/87475814-463a7500-c5da-11ea-88e2-f1f92d3ac0eb.png">

**Comment by loopDelicious** [comment]
Here's another example - searching `switch accounts` yields limited results, but not a header `Switching between accounts` on [this page](https://learning.postman.com/docs/getting-started/postman-account/#switching-between-accounts).

![Screen Shot 2020-07-15 at 2 09 27 PM](https://user-images.githubusercontent.com/17693714/87596386-dc3ad200-c6a4-11ea-8944-7cc6a27733e0.png)

**Comment by loopDelicious** [comment]
> @loopDelicious I am not sure I understand. Is this related to Algolia search?
> When I open the links in the content section, they go to the correct section of the page.

Not sure if someone fixed it? Here's another example of links in the contents section that have the extra `/`. Not sure if this was human error, or a migration issue.

On [this page](https://learning.postman.com/docs/integrations/available-integrations/github/#configuring-github-integration-for-collections), clicking on `Backup collections to GitHub`, goes to `https://learning.postman.com/docs/integrations/available-integrations/github/#configuring-github-integration-for-collections`, instead of `https://learning.postman.com/docs/integrations/available-integrations/github#configuring-github-integration-for-collections`. The first link doesn't work, but deleting the `/` preceding the `#` works.

**Comment by loopDelicious** [comment]
Typing `fork` and `forking` returns non-fork-related results. And limited results require more keywords to display any relevant results.

Fork does not display until I type `forking and merging`.

<img width="1532" alt="Screen Shot 2020-07-22 at 1 53 08 PM" src="https://user-images.githubusercontent.com/17693714/88227901-31399380-cc23-11ea-9568-3f66ad75809b.png">

<img width="1532" alt="Screen Shot 2020-07-22 at 1 53 16 PM" src="https://user-images.githubusercontent.com/17693714/88227849-1c5d0000-cc23-11ea-908b-ed845d92aecc.png">

**Comment by ch264** [comment]
Summary can be found in Jira WEBSITES-856

**Comment by loopDelicious** [comment]
Can we also index lists? Searching for popular libraries like `moment` and `lodash` result in zero results. These libraries are listed on this page: https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries

**Comment by jkonrath-postman** [comment]
(This should have closed when PR 2561 closed.)
