### ISSUE TITLE
$isoTimestamp does not exist in latest Windows version (7.28)

### ISSUE THREAD

**Issue by IanKemp** [postmanlabs/postman-docs#2527]
It is documented at https://learning.postman.com/docs/writing-scripts/script-references/variables-list/ but the latest Windows version (at least) of the Postman application (7.28 at the time of filing this issue) does not know about this variable. The doc PR's merge #2519 should be rolled back until a version of the application that is aware of this variable is released, at which point the referenced PR should then be re-merged.

**Comment by SueSmith** [comment]
@atulbi any idea on the status here ^^

**Comment by atulbi** [comment]
Code-freeze is done for 7.28. This will be updated in 7.29 (External Release Date: 22 July)

**Comment by SueSmith** [comment]
Ah let me remove it from the docs for the moment then

**Comment by SueSmith** [comment]
Ok have reverted for the moment and will publish on 7.29 release (https://github.com/postmanlabs/postman-docs/pull/2530) thanks for reporting @IanKemp 🙌

**Comment by IanKemp** [comment]
@SueSmith thanks for resolving this, I'd just like to flag for future that there seems to be a bit of a disconnect between the app and docs team - it would be best to address this so issues like these don't happen again.
