### ISSUE TITLE
Add GraphQL video to additional resources links in sidebar

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2551]
GraphQL page in docs: https://learning.postman.com/docs/sending-requests/supported-api-frameworks/graphql/

Link to YT: https://youtu.be/7pUbezVADQs

**Comment by SueSmith** [comment]
@loopDelicious we actually just added it in the body of the page 🎥 (same for codegen)

**Comment by loopDelicious** [comment]
@SueSmith The right sidebar is a bit more scannable IMO, and makes sense to also include there as well. Some pages utilize the `VIDEOS` subheader.

But if we're moving away from listing resources in that sidebar, I can close this issue. Or feel free to close it too.

**Comment by SueSmith** [comment]
@loopDelicious Not at all, we can totally add to sidebar as well 👍

**Comment by HeroicHitesh** [comment]
@loopDelicious To me it seems like this issue is resolved in #2596 so, probably we can close this to avoid confusion. Or is there any work left, that needs to be done?

**Comment by loopDelicious** [comment]
> @loopDelicious To me it seems like this issue is resolved in #2596 so, probably we can close this to avoid confusion. Or is there any work left, that needs to be done?

Yep - thanks for the note. closing.
