### ISSUE TITLE
4xx error when clicking on image

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2554]
https://assets.postman.com/postman-docs/leaving-team-worskpace.jpg throws a 404 in /collaborating-in-postman/using-workspaces/managing-workspaces.md

<img width="765" alt="Screen Shot 2020-07-20 at 11 19 43 AM" src="https://user-images.githubusercontent.com/36343528/87971897-eda42580-ca7a-11ea-91ec-7ab260f21cd8.png">

**Comment by DannyDainton** [comment]
We need to change `worskpace` for `workspace` in the image URL.

`[![Leave workspace](https://assets.postman.com/postman-docs/leaving-team-workspace.jpg)](https://assets.postman.com/postman-docs/leaving-team-**worskpace**.jpg)`
