### ISSUE TITLE
Request to Update Proxy page

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2563]
Proxy is something Postman users use extensively to make their endpoints work. As the proxy settings tab is currently redesigned - the terms aren't relevant when users go through the documentation.

Also screenshots for the same.

Link: https://learning.postman.com/docs/sending-requests/capturing-request-data/proxy

Example: Usage of Global proxy

![image](https://user-images.githubusercontent.com/47771757/88519021-11351600-d00f-11ea-8448-7a3dcc627ae8.png)

Current, Proxy view doesn't mention global anywhere - which might be confusing for the new users.

![image](https://user-images.githubusercontent.com/47771757/88519165-50fbfd80-d00f-11ea-94a7-96df02bcaa49.png)
 
Apologies if this is already being looked into :)

_Filed by: Product Support_

**Comment by kushal-khare-official** [comment]
Hi, I would like to help with this issue. Can someone plz guide me through?

**Comment by jkonrath-postman** [comment]
@sowmyaraj92 this looks like a duplicate (but with much more info) of https://github.com/postmanlabs/postman-docs/issues/3064 - once you have a PR for one, you can link it to both issues and close both.
