### ISSUE TITLE
Clarify API specification import

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2565]
Only some of these are API specification formats: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#importing-api-specifications

Even though we're not very consistent or accurate throughout the product, we could maintain consistency with the Import modal.

**Comment by jkonrath-postman** [comment]
Hi @loopDelicious - check out the linked PR. I'm not sure that's the best place to put them, or if this should be a separate section like the V2 collection conversion bit above that, but let me know what you think.
