### ISSUE TITLE
Consider making Monitoring APIs section Monitoring your APIs

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2572]
The "Monitoring APIs" page title can be interpreted as APIs used for Monitoring: https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/

Consider updating to "Monitoring your APIs" for clarity and consistency with other section. Similar to how `Documenting your APIs` seems clearer than if it was `Documenting APIs`.

**Comment by kushal-khare-official** [comment]
@loopDelicious Can I be assigned this issue?

**Comment by kushal-khare-official** [comment]
@ch264 please tell if this issue is still open?

Also I have asked to be assigned in a few more issues but no one has responded there yet. I am asking you as you are the only person who responded.

I am preparing for GSOC this year and want to contribute as much as possible.

**Comment by ch264** [comment]
@claireriley is this issue still open?

**Comment by claireriley** [comment]
@ch264 yep! 

@kushal-khare-official apologies for the delayed responses. I've assigned this one to you—please feel free to tag me in any you'd like to be assigned and add me as a reviewer when you submit PRs 😄

**Comment by kushal-khare-official** [comment]
@claireriley Thanks for assigning the issue.
