### ISSUE TITLE
Old link in Victorops document + scan codebase for links to old domain

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2580]
At the top of the page content ( https://learning.postman.com/docs/integrations/available-integrations/victorops/ ), we have a link on "Integrations are available on Postman Team, Business, and Enterprise plans." that points to the old domain `getpostman.com`, causing a redirect and dropping key GA data on the floor in doing so.

Update link to point to https://www.postman.com/pricing/ (note trailing slash, otherwise causes another redirect.)

Also, search codebase for any and all `getpostman.com` domains and update to `postman.com` (again, ensure those URLs have trailing slash to fix redirects.)

<img width="1191" alt="Screen Shot 2020-08-10 at 8 56 19 AM" src="https://user-images.githubusercontent.com/4358288/89803607-e99e7d00-dae7-11ea-8abc-0d18d844ebe1.png">

**Comment by AnujSharma141** [comment]
@tristandenyer Can I work on this? I have searched the codebase and only pages in the 'integrations' directory need the fix.

**Comment by tristandenyer** [comment]
Apologies @AnujSharma141, I didn't see your comment until now and it looks like a PR has been made by another contributor.

I appreciate your willingness to help out!
