### ISSUE TITLE
More documentation for private workspaces

### ISSUE THREAD

**Issue by JP-from-Postman** [postmanlabs/postman-docs#2582]
Searching for private workspaces on LC returns no direct search results:
<img width="615" alt="Screen Shot 2020-08-11 at 4 07 33 PM" src="https://user-images.githubusercontent.com/43283131/89957669-dd501800-dbec-11ea-8fa0-88638ac47173.png">

I think there may be a mention or two of private workspaces, but I'm having trouble finding them again.

Would be good to have an easily surfaceable article/section about private workspaces, how they work, and what they can be used for. We get fair number of requests about this, especially around creating multiple teams (which private workspaces handles for now).

**Comment by ch264** [comment]
Hi @JP-from-Postman, 
Thanks for letting us know. We are woking on optimizing search and will include this ticket.

cc. @joyous-joyce

**Comment by loopDelicious** [comment]
@JP-from-Postman as we're optimizing search, you can point folks to these resources. 
- CTRL/CMD + F on this page for `private`, we have some docs: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/ 
- and also this blog post: https://blog.postman.com/announcing-private-workspaces-for-postman-enterprise/

**Comment by loopDelicious** [comment]
@JP-from-Postman this should be fixed with the recent search enhancements. feel free to reopen if you have more to add.
