### ISSUE TITLE
Integrating with Travis CI - Run in Postman - doesn't import collection

### ISSUE THREAD

**Issue by VuNguyen-Postman** [postmanlabs/postman-docs#2617]
https://learning.postman.com/docs/running-collections/using-newman-cli/integration-with-travis/ 

Under 'Getting Started'  when I click "Run in Postman" I cannot import the collection to the app. 
This error message pops up in the app
![image](https://user-images.githubusercontent.com/70542554/91762963-5efeea00-eb8a-11ea-94db-252df160b2e7.png)

**Comment by SueSmith** [comment]
Thanks @VuNguyen-Postman, this content dates back a few years by the look of it and I doubt anyone will have access to the collection or environment anymore 😞 - would you mind trying it from the collection link (which would be https://www.postman.com/collections/b79dc2835758549eed7e if you import by link instead of rip button), it presumably needs environment vars too, if we can cobble together what was in there hopefully we can duplicate and republish at least to make the doc work..

**Comment by VuNguyen-Postman** [comment]
Thanks @SueSmith ! Importing it as URL works

**Comment by SueSmith** [comment]
@VuNguyen-Postman oh cool! Does the whole thing work without having to import an environment? If so we can just replace the run in postman button with one linking to that collection..

**Comment by VuNguyen-Postman** [comment]
@SueSmith it's just 1 endpoint, but it works without an environment!

Response:
`{"time":{"updated":"Sep 2, 2020 17:47:00 UTC","updatedISO":"2020-09-02T17:47:00+00:00","updateduk":"Sep 2, 2020 at 18:47 BST"},"disclaimer":"This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org","chartName":"Bitcoin","bpi":{"USD":{"code":"USD","symbol":"&#36;","rate":"11,366.2257","description":"United States Dollar","rate_float":11366.2257},"GBP":{"code":"GBP","symbol":"&pound;","rate":"8,494.9921","description":"British Pound Sterling","rate_float":8494.9921},"EUR":{"code":"EUR","symbol":"&euro;","rate":"9,545.3791","description":"Euro","rate_float":9545.3791}}}`

**Comment by SueSmith** [comment]
Hey @VuNguyen-Postman I've added you as a collaborator to the docs repo, once you accept the invite I can tag you for a review on this PR #2625 (I've just imported that collection and created an env with the one var I can see in the tests, and generated a new RiP button from that 🤞)

**Comment by loopDelicious** [comment]
That collection is mine. We had some issues w/data migration where a few collections got lost. This collection is used in quite a few areas. Might be worth reporting as a bug (if it is) @VuNguyen-Postman
