### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by sagar-barapatre** [postmanlabs/postman-docs#2628]
Save our eyes. And batteries. Do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by soumy47** [comment]
Hey,  I would like to work on this issue. Would you please guide me?

**Comment by sagar-barapatre** [comment]
Follow these: 
1) DOCS - https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
2) Video Tutorial - https://youtu.be/jmepqJ5UbuM

**Comment by soumy47** [comment]
but where to add this dark theme?

**Comment by sagar-barapatre** [comment]
On the entire website.
You just need to change the background colour with some functionalities in javascript for toggling the light and dark mode.

**Comment by soumy47** [comment]
sorry ,but i only know html and css

**Comment by sagar-barapatre** [comment]
Then in that case i strongly stringly recommend you to learn JavaScript,
 becuase the functionalities(toggle) can be given only using JS.
BTW: I am talking about this website [Click Here](https://learning.postman.com/)

**Comment by soumy47** [comment]
Thanks for your help and suggestion.

**Comment by soumy47** [comment]
Thanks for your help and suggestion.

**Comment by sagar-barapatre** [comment]
No problem, Let me know if you need some more help.

**Comment by tanishq-mishra** [comment]
Is it alright if I take it up?

**Comment by sagar-barapatre** [comment]
Hey buddy, @soumy47 is currently working on that. If she no longer want to work on this, then this will be assigned to you.

**Comment by soumy47** [comment]
@sagar-barapatre   Currently, I am not able to work on this issue due to my exams. Thanks for your consideration.

**Comment by tanishq-mishra** [comment]
Hey @sagar-barapatre, Since @soumy47 is not able to work on this issue, I have kinda implemented the dark mode. If it is alright, should I commit the changes, and you can take a look at it?

**Comment by sagar-barapatre** [comment]
Great ! Go Ahead and make a PR

**Comment by tanishq-mishra** [comment]
#2644 this is my first time trying something like this. Please let me know if I followed the correct steps for a PR

**Comment by sagar-barapatre** [comment]
Yeah !! Absolutely correct 💯

**Comment by sagar-barapatre** [comment]
> #2644 this is my first time trying something like this. Please let me know if I followed the correct steps for a PR

Yeah !! Absolutely correct 💯

**Comment by tanishq-mishra** [comment]
why does it say all checks failed though? It was running for me. 🤔

**Comment by sagar-barapatre** [comment]
@tanishq-mishra Relax relax!! This issue is not related to your code it’s due to some old PRs of Postman Labs is already aware of it.

**Comment by tanishq-mishra** [comment]
ohh lol okay 😆
