### ISSUE TITLE
404 URL on /docs/writing-scripts/script-references/postman-sandbox-api-reference/

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2634]
This link goes to 404:

<img width="1017" alt="Screen Shot 2020-09-08 at 10 27 48 AM" src="https://user-images.githubusercontent.com/36343528/92508729-f3d29a80-f1bd-11ea-9315-4baacbf5a022.png">

Remove the " before and after the link 
<img width="791" alt="Screen Shot 2020-09-08 at 10 28 29 AM" src="https://user-images.githubusercontent.com/36343528/92508782-0b118800-f1be-11ea-9705-fc06ec03a77a.png">

**Comment by soumy47** [comment]
Hey, @ch264 I want to work on this issue. Can we use an absolute link here??

**Comment by soumy47** [comment]
Hey, @ch264 I want to work on this issue.
