### ISSUE TITLE
Add direct link flow to accessing Postman API keys

### ISSUE THREAD

**Issue by SueSmith** [postmanlabs/postman-docs#2635]
In this page https://learning.postman.com/docs/developer/intro-api/ we have how to access your api keys via the ui, but you can also access them using this url: https://go.postman.co/settings/me/api-keys so we should add this to the doc

**Comment by carmelag** [comment]
@SueSmith hi! I would like to take this one. Is anyone else working on this? Please lmk

**Comment by SueSmith** [comment]
Hi @carmelag! If you'd like to work on it that would be great 🙌

**Comment by carmelag** [comment]
Ok @SueSmith! Great! Could you please assign the issue to me? I'll let you know when it's done. Thanks for your quick response 🙌

**Comment by SueSmith** [comment]
Thank you for contributing! 🙂
