### ISSUE TITLE
Create a quick guide

### ISSUE THREAD

**Issue by Rishal92** [postmanlabs/postman-docs#2649]
I think the website learning section is very complex as it is long and has too much screen shots. 

I think a quick guide is needed. 

Try using GIFs in the guide to reduce the number of words and screenshots.

**Comment by jkonrath-postman** [comment]
Hi @Rishal92 - thanks for the input, and sorry for the delay. We're always working to continually updating the design and architecture of the Learning Center. I'll put your suggestion on our design list so we can consider it in the future. Thanks again!
