### ISSUE TITLE
Clarify How to Install Desktop Agent After Closing Web Modal (BETA)

### ISSUE THREAD

**Issue by jerry-li-dev** [postmanlabs/postman-docs#2651]
Current: The Web UI has a web modal to install the Postman Desktop Agent that appears only the first time you launch the beta web client. There are no clear instructions for how to install Postman Desktop Agent after skipping past the modal. The API response states that there is a CORS policy issue, but it does not link to the [blog post explaining the issue](https://blog.postman.com/introducing-the-postman-agent-send-api-requests-from-your-browser-without-limits/).

Enhancements: 

- Link to [blog post](https://blog.postman.com/introducing-the-postman-agent-send-api-requests-from-your-browser-without-limits/) explaining the error.

- Explain that the Postman Desktop Agent is the solution to the error.

- Add tooltip to remind user to install the Postman Desktop Agent.

**Comment by jkonrath-postman** [comment]
This was closed by merging #2691
