### ISSUE TITLE
No "Client Certificates" visible in Console

### ISSUE THREAD

**Issue by ericthomas1** [postmanlabs/postman-docs#2674]
Hello,

I've uploaded a Client Certificate to `Settings/Certificates`:
![image](https://user-images.githubusercontent.com/42788729/96057378-ad67ff80-0e3d-11eb-9e74-8416db4f3a35.png)

But when submitting a request to the host endpoint, there is no "Client Certificate" section showing in the Console:
![image](https://user-images.githubusercontent.com/42788729/96057598-25362a00-0e3e-11eb-8f5e-38c612167f1c.png)

The [docs here](https://learning.postman.com/docs/sending-requests/certificates/) make it look like I should see a "Client Certificate" section:
![image](https://user-images.githubusercontent.com/42788729/96057505-f3bd5e80-0e3d-11eb-9c09-becbc9c87b8a.png)

Should I?

Does the absence of a Client Cert section in the Console mean that Postman is not sending it as part of the request?

**Comment by jkonrath-postman** [comment]
Hi @ericthomas1  - it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at postmanlabs/postman-app-support  Thanks!
