### ISSUE TITLE
Wrong icon on the Learning Center for manage environment

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/postman-docs#2688]
A user noticed the following inconsistency on screenshots: https://twitter.com/RajeevCinema/status/1321185120351621120

**Comment by PeeyushRawat** [comment]
i want to work on this, also please guide me

**Comment by sumit-kushwah** [comment]
i think all images should be replaced where 'gear wheel' is used for **management environments** icon

**Comment by PeeyushRawat** [comment]
.take

**Comment by PeeyushRawat** [comment]
@arlemi I've almost completed my work on this...please assign this to me.
