### ISSUE TITLE
404 url found

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2694]
on https://learning.postman.com/docs/administration/onboarding-checklist/ 

The first link in additional resources goes to 404: 
<img width="1066" alt="Screen Shot 2020-11-02 at 9 53 09 AM" src="https://user-images.githubusercontent.com/36343528/97901572-38c40a80-1cf1-11eb-9166-c55a2f9fd7d6.png">

**Comment by PeeyushRawat** [comment]
assign this to me! also please guide me.

**Comment by sumit-kushwah** [comment]
@ch264 I made a pull request #2697, please review my changes. I hope it solves the issue.
