### ISSUE TITLE
404 url found  in  docs/administration/team-merge.md 

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2705]
in docs/administration/team-merge.md 

1. add a slack to the link: `docs/designing-and-developing-your-api/mocking-data/setting-up-mock/`
<img width="839" alt="Screen Shot 2020-11-19 at 9 49 53 AM" src="https://user-images.githubusercontent.com/36343528/99703948-94f69080-2a4c-11eb-9ece-3c3535004062.png">

2. contact Postman Support needs to be changed to `https://www.postman.com/support/` for both links: 

<img width="1070" alt="Screen Shot 2020-11-19 at 9 55 09 AM" src="https://user-images.githubusercontent.com/36343528/99704486-51505680-2a4d-11eb-8c07-e994845ab14b.png">
 

and 
<img width="1076" alt="Screen Shot 2020-11-19 at 9 55 27 AM" src="https://user-images.githubusercontent.com/36343528/99704524-5b725500-2a4d-11eb-8024-4c90af17e1d5.png">

**Comment by kushal-khare-official** [comment]
@ch264 I want to help with this issue

**Comment by ch264** [comment]
@kushal-khare-official awesome. You can tag me as a reviewer in your PR

**Comment by kushal-khare-official** [comment]
@ch264 Please review this PR.
