### ISSUE TITLE
Request to update screenshots for Integration pages

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2709]
With the newer version of Postman Web, users are slightly confused about how to navigate to the Integrations page.

Add how-to navigate to Integrations from Home page >

![image](https://user-images.githubusercontent.com/47771757/99973192-7fbf9000-2dc5-11eb-9da5-13e75f14631e.png)

The documentations have the older screenshots:
> Ref: https://learning.postman.com/docs/integrations/intro-integrations/#accessing-integrations

![image](https://user-images.githubusercontent.com/47771757/99973028-53a40f00-2dc5-11eb-841f-901b82da3f6a.png)

**Comment by kushal-khare-official** [comment]
Can I help with this issue?

**Comment by kushal-khare-official** [comment]
@Raj-postman  Is this correct info. Please review. If yes, I will make a PR.
`You can access integrations by selecting **Integrations** from the sidebar in the [web dashboard](https://go.postman.co/)`

**Comment by claireriley** [comment]
Hey @kushal-khare-official ! We've got this page covered by our in-house team (cc @jerry-li-dev @Raj-postman ), but please feel free to request others.
