### ISSUE TITLE
Update documentation preview instructions

### ISSUE THREAD

**Issue by chrisdeso** [postmanlabs/postman-docs#2720]
### Overview
Postman's learning center documentation should reflect that the `Preview Documentation` action is no longer available in the web interface during the documentation publishing flow and it should indicate what the best way to preview documentation is.

### Resources

- Current documentation | https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/#configuring-your-public-docs
![image](https://user-images.githubusercontent.com/4734306/100293912-db675600-2f4a-11eb-89e4-45f78e006f60.png)

- Current publishing flow
![image](https://user-images.githubusercontent.com/4734306/100293917-ddc9b000-2f4a-11eb-9230-2c49793fc6cf.png)

**Comment by SueSmith** [comment]
Just a wee note that I asked in api network squad channel about this and it's theoretically coming back..

**Comment by jkonrath-postman** [comment]
I just checked, and this is back.
