### ISSUE TITLE
Request to add additional details to Static IP Integration Doc

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2727]
Article: https://learning.postman.com/docs/integrations/intro-integrations/#static-ip-support

As seen in recent cases, static IP whitelisting for Integration doesn't work even when added - if users DNS points to a private IP (Eg: 192. or 10.). Hence, requesting the team to add these vital details to the Document as well.

> DNS records should use the public IP address for the instance which are behind the firewall or not accessible via the internet.

**Comment by jkonrath-postman** [comment]
Added a note on this in the linked PR.
