### ISSUE TITLE
Mixed Content Error: The request has been blocked because it requested an insecure HTTP resource

### ISSUE THREAD

**Issue by RobyCigar** [postmanlabs/postman-docs#2742]
### I follow along the documentation and got this error

![image](https://user-images.githubusercontent.com/69680330/101712606-7a05c200-3ac8-11eb-80c5-bf5cf595b96f.png)

How can i fix this? 
What should I do for user who using browser instead of desktop?
thank you

**Comment by SueSmith** [comment]
Hi @RobyCigar, this is actually the repo for the Postman Learning Center documentation–Postman support questions are best posted on the [community forum](https://community.postman.com/) where there are more people around to help. 🙂 

For your issue you need to use the desktop agent, if you click the __Use Postman Desktop Agent__ link that should walk you through the required steps.

**Comment by RobyCigar** [comment]
Sorry, I apologize for that
