### ISSUE TITLE
Clicking on integration link should navigate to integrations

### ISSUE THREAD

**Issue by abhinaba-ghosh** [postmanlabs/postman-docs#2748]
Refer: https://learning.postman.com/docs/integrations/available-integrations/slack/

<img width="617" alt="Screenshot 2020-12-14 at 4 16 47 PM" src="https://user-images.githubusercontent.com/23141842/102072346-c6823200-3e27-11eb-9e03-fa7ae9d502e9.png">

**Comment by jkonrath-postman** [comment]
This was closed by #2776
