### ISSUE TITLE
Shortcut for recently edited requests

### ISSUE THREAD

**Issue by Betlista** [postmanlabs/postman-docs#2762]
Hi,

IDEs like Idea or Eclipse have shortcut for recently edited files

**Idea** (CTRL+TAB)

|![screenshot_2020-12-19_193847](https://user-images.githubusercontent.com/1876272/102696872-e9e71b80-4231-11eb-8fa3-5b22b75d0fa9.png)|
|-|

**Eclipse** (CTRL+F6)
|![screenshot_2020-12-19_193902](https://user-images.githubusercontent.com/1876272/102696879-ef446600-4231-11eb-9892-dbbffb5d0dd8.png)|
|-|

It would be nice, to have something similar in Postman.

**Comment by SueSmith** [comment]
Hi there! This is the repo for the Postman Learner Center, I think you probably want the app support repo 🙂 https://github.com/postmanlabs/postman-app-support/
