### ISSUE TITLE
placeholders with tags showing incorrectly in documentation

### ISSUE THREAD

**Issue by raghav19** [postmanlabs/postman-docs#2763]
Following command in documentation :
```shell
wpm create-container-image-flavor -i <container_image_name> -t <tag_name> -e -f <path>/Dockerfile -d <path>
```

shows up as:
```shell
wpm create-container-image-flavor -i ,<,container_image_name,>, -t ,<,tag_name,>, -e -f ,<,path,>,/Dockerfile -d ,<,path,>
```

with wrongly parsed tags in the `View in Web` option of postman Client.

Version Info:
Postman for Windows
Version 7.36.1
win32 10.0.18363 / x64

**Comment by soumy47** [comment]
Hey @raghav19 ! I would like to work on this issue .Could u please guide me?

**Comment by raghav19** [comment]
Hi @soumy47 , as mentioned, i see the tags especially get updated in the "View in Web" option as `<,tag_name,>, `. This wasnt happening in the previous versions when the documention UI was the older one. I suppose this is only in the new documentation UI

**Comment by soumy47** [comment]
Hey @raghav19, I am beginner in open source .Could please tell me where I can find the source file of this document?

**Comment by raghav19** [comment]
@soumy47 , you can create a simple collection in postman, then , add some markdown based shell commands in the collection documentation and , use the "View in Web" option to see how the commands show up for you, in that. Just ensure that your shell commands have tags in them , something like below. You will see the output as mentioned in my case above. The tags wont populate correctly.

```shell
hey there <put name here>
```

**Comment by soumy47** [comment]
Thanks for the help,@raghav19.

**Comment by jkonrath-postman** [comment]
I'm not seeing this anymore in v8.0.10.
