### ISSUE TITLE
broken image on /docs/publishing-your-api/add-templates/

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-docs#2770]
There is a broken image on https://learning.postman.com/docs/publishing-your-api/add-templates/

<img width="1258" alt="Screen Shot 2021-01-04 at 9 56 55 AM" src="https://user-images.githubusercontent.com/36343528/103564339-2ee69100-4e73-11eb-8d24-a310e6b0a718.png">

The file is located here: src/pages/docs/publishing-your-api/add-templates.md

<img width="782" alt="Screen Shot 2021-01-04 at 9 57 42 AM" src="https://user-images.githubusercontent.com/36343528/103564416-4b82c900-4e73-11eb-9063-8dd1a9ce60c5.png">

**Comment by KKVANONYMOUS** [comment]
@ch264 I would like to work on this issue
