### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/postman-docs#2772]
https://learning.postman.com/docs/sending-requests/visualizer/#visualizer-api links to the "Postman API" (https://learning.postman.com/docs/developer/intro-api/), but the sandbox API is unrelated to the API that the docs currently link to. The link should be to https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/ instead

**Comment by Saurabh1901** [comment]
Can I work on this issue?

**Comment by claireriley** [comment]
@Saurabh1901 yes! I've just assigned it to you, please add me as a reviewer on the PR 😄

**Comment by aritrasinha108** [comment]
@claireriley  Since there hasn't been any activity or progress for so many days, please let me know if I can work on this?  I've already made the change. Just need to create a PR

**Comment by claireriley** [comment]
Sure @aritrasinha108 ! Please add me as a reviewer on the PR.
