### ISSUE TITLE
Outdated URL link on pages under /integrations/available-integrations/ 

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#2776]
The individual integrations page under  /integrations/available-integrations/  (such as APImatic) contain outdated URL link to integrations page (https://go.postman.co/workspaces). 

Since integrations page is now accessed from https://go.postman.co, this section of each page should be updated accordingly. 

Related issue: https://github.com/postmanlabs/postman-docs/issues/2748

I made PR here to include suggested changes: https://github.com/postmanlabs/postman-docs/pull/2773

Thanks!

**Comment by taehoshino** [comment]
Another user reports:
https://community.postman.com/t/how-can-i-navigate-to-the-integrations-for-a-workspace-on-the-postman-co-website/17925

**Comment by jkonrath-postman** [comment]
The related PR (https://github.com/postmanlabs/postman-docs/pull/2773) is closed. (It won't let me link to it to auto-close the issue.)
