### ISSUE TITLE
Request to remove these details from Newman page.

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2778]
At the moment, only Exported runs from Postman Collection run can be viewed on Postman via Import. Here is the GitHub thread where we have this request: https://github.com/postmanlabs/postman-app-support/issues/9401

Hence requesting to remove the below section from the [Newman page here](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/#example-collection-with-failing-tests) to avoid any confusion in the future.

![image](https://user-images.githubusercontent.com/47771757/103734106-3e034580-5011-11eb-8f75-41c85c25aee5.png)

**Comment by arnab15** [comment]
hello,
I have knowledge of javascript ,nodejs,reactjs,expressjs, Mongodb but I haven't contributed to any open-source project before so I'm a beginner. I would like to contribute to this project.
how should I start can anyone suggest to me the way should I start contributing.
