### ISSUE TITLE
Use postman agent from own domain, possible?

### ISSUE THREAD

**Issue by jimmywarting** [postmanlabs/postman-docs#2781]
Is the Postman desktop agent only built for the _Postman web interface_? Or can i somehow use it on my own domain to circumvent the same-origin policy?

**Comment by jkonrath-postman** [comment]
Hi @jimmywarting - this is the repo for the Postman docs; we don't handle feature requests or product questions here. You might want to try filing an issue at https://github.com/postmanlabs/postman-app-support
