### ISSUE TITLE
Update Adding from the Dashboard section

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2782]
It looks like the workflow outlined in this section `Adding from the Dashboard` is not up to date. You can no longer `Add to workspace` from this part of the dashboard.

https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#adding-from-the-dashboard

**Comment by sowmyaraj92** [comment]
The PR for Managing workspaces is already in progress (Branch name:**v8-managing-workspaces**). Adding from the dashboard section is removed for this PR and will not be present once the PR gets merged.

**Comment by sowmyaraj92** [comment]
@loopDelicious We have updated the Learning Center page, hence I'm going ahead and closing this ticket. Thank you so much :)
