### ISSUE TITLE
A little confusion around call-to-action on Slack Integration page

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2796]
There is some slight wording confusion around the call-to-action (CTA) to "Click the View Details button...", since there is an image right above it that has that button in it, AND the image is clickable.

Recommending that the image NOT link to itself (since the linked image really does not provide any additional info or even get larger that what is already presented) and instead copy the link above it and take the user to the https://go.postman.co/workspaces, the Integrations tab in the app.

See:
https://learning.postman.com/docs/integrations/available-integrations/slack/

<img width="588" alt="Screen Shot 2021-01-19 at 2 47 17 PM" src="https://user-images.githubusercontent.com/4358288/105103671-cea44180-5a65-11eb-87b5-2dabefae44aa.png">

**Comment by jkonrath-postman** [comment]
See the linked PR - I think some of the text has already changed since this was opened, but I noticed that the link in the place you mentioned was supposed to be just an image, and the ! was missing in front of it. I fixed that and did some other minor copyedits.
