### ISSUE TITLE
Could not send request

### ISSUE THREAD

**Issue by chennakesava89** [postmanlabs/postman-docs#2808]
Error: connect ECONNREFUSED 127.0.0.1:9515

**Comment by jkonrath-postman** [comment]
Hi @chennakesava89 - it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support. Thanks!
