### ISSUE TITLE
The postman-echo template is missing in the Postman "Getting Started" wiki docs.

### ISSUE THREAD

**Issue by hammzj** [postmanlabs/postman-docs#2812]
I've been refreshing up on Postman and I decided to start from the beginning by reading up all of the "Getting Started" docs on the Learning Center site. On the very first document, [Sending the First Request](https://learning.postman.com/docs/getting-started/sending-the-first-request/), there is a link to a template for the [postman-echo](https://www.postman.com/explore/template/1358/postman-echo) API the bottom of the page. However, that link is broken as the next page reads
> This template couldn't be found
It may have been removed from the API Network. Try searching for a different one.

I can't give an answer on how to address this from my end but I see this as something can be misleading for others. Would anyone be able to restore that template?

**Comment by sowmyaraj92** [comment]
@hammzj Apologies for the delayed reply. We had pushed a fix for this. The link to Postman Echo API on the [Sending the First Request](https://learning.postman.com/docs/getting-started/sending-the-first-request/) points to a public workspace - [Published Postman Templates](https://docs.postman-echo.com/). The link should work for you now. :)🤞 
Thank you for your contribution, I'm going ahead and closing this issue. Feel free to reach out to us anytime.
