### ISSUE TITLE
Code generation documentation updates

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/postman-docs#2819]
Starting late 2020, we removed the option to choose the old/new code-generation modes in Postman. References to either 'mode' need to be removed:

https://learning.postman.com/docs/getting-started/settings/#escalation-requests
https://learning.postman.com/docs/sending-requests/generate-code-snippets/ - screenshots to be updated once v8 is rolled out to everyone

**Comment by sowmyaraj92** [comment]
The [Generating code snippets](https://learning.postman.com/docs/sending-requests/generate-code-snippets/) page is updated.
