### ISSUE TITLE
 Use more inclusive nomenclature in branch name, master -> main

### ISSUE THREAD

**Issue by kevinswiber** [postmanlabs/postman-docs#2838]
Hi there.  Let's adopt more inclusive language in the branch names of this repository.

* `master` -> `main` ([how-to](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/))

Thanks for your consideration!

**Comment by jkonrath-postman** [comment]
A few bits of research:

* https://github.com/github/renaming 
* https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch
* There's a few steps folks will have to do to update their local clone: https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes
* No idea how this impacts GH actions or our build process

**Comment by Abhishekvrt** [comment]
Hey there!! Can I solve this issue? 
Can anybody will assign me this one.

**Comment by jkonrath-postman** [comment]
(This was changed a while ago.)
