### ISSUE TITLE
Docs say 50MB is the limit, but postman app for me failed at 32MB and cited a limit

### ISSUE THREAD

**Issue by bean5** [postmanlabs/postman-docs#2846]
https://learning.postman.com/docs/getting-started/settings/#:~:text=If%20the%20limit%20is%20exceeded,responses%20can%20impact%20Postman's%20performance.

I am using Linux. Is this a bug in the app or is documentation incorrect?

**Comment by arlemi** [comment]
Have you tried changing the response size limit in your app settings? 
![Screenshot 2021-02-17 101820](https://user-images.githubusercontent.com/5029719/108190211-8f6f1c00-7109-11eb-8774-bd05d44c2952.png)

**Comment by jkonrath-postman** [comment]
The docs reflect the setting, so they should be correct, but it's possible this is an issue in the product.

Feel free to report a product issue at https://github.com/postmanlabs/postman-app-support - if the docs do need an additional note, let us know. Thanks!
