### ISSUE TITLE
Update Postman API getting started experience

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2877]
This page is out of date: https://learning.postman.com/docs/developer/intro-api/

The Postman API documentation now redirects to this public workspace: https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a

- Users get started by forking the collection (instead of the Run in Postman button import described on this page https://learning.postman.com/docs/developer/intro-api/)
- The web dashboard experience has changed, so getting an API key from the home page can be removed or updated

**Comment by vinayak-gaikwad** [comment]
Hello, I am new to the opensource contribution can you please elaborate on this issue a little bit. Thank you

**Comment by Cronus1007** [comment]
@loopDelicious Shall I implement this issue?
