### ISSUE TITLE
Markdown Documentation Wording

### ISSUE THREAD

**Issue by nrmartell** [postmanlabs/postman-docs#2882]
Hello Team!

It looks like we're using randomly generated text on our Markdown documentation(https://documenter.getpostman.com/view/4630964/S1LsXVJy?_ga=2.123417931.1939325990.1615224750-1731478600.1608056395). One of our users pointed out the language may be considered unprofessional/crude:

Example:

> 'Jamaica Red Ale sanitizes the flatulent Pilsner'
> 'The gratifying keg hesitantly pees on a bud light from a Guiness'
> 'Any Keystone can make a pact with the Mango Beer around a blue moon, but it takes a real PBR to pee on the treacherous Keystone'

These are in the Basic Markdown Elements Section.

**Comment by crew-guy** [comment]
Hi ! I would like to work on this issue. Can you please lead me to some resources where I can learn and fix this ?

**Comment by jkonrath-postman** [comment]
This is in a published collection, not the learning center docs. Let me take a look and see if I can change it.

**Comment by jkonrath-postman** [comment]
I edited the sample text in the published collection to fix this.
