### ISSUE TITLE
Docs about Token Scanner feature is missing

### ISSUE THREAD

**Issue by iprithvitharun** [postmanlabs/postman-docs#2884]
I couldn't find any docs related to the Token Scanner feature under Settings. 

However, I was able to find the following blogs.

https://blog.postman.com/postman-security-scans/
https://blog.postman.com/how-were-protecting-your-postman-api-keys-in-github/

These are all scattered and don't provide the complete picture of how Postman helps its customers secure their Collections.

**Comment by jkonrath-postman** [comment]
This was fixed in https://github.com/postmanlabs/postman-docs/pull/3060 (The issue didn't auto-close because it was linked to the old PR.)
