### ISSUE TITLE
Typo in video link for monitoring

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2888]
Baby typo in the right sidebar of this page: https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/monitoring-apis-websites/

The link to the video says `API mentoring with Postman` instead of `API monitoring`.

**Comment by SanjaySinghRajpoot** [comment]
ok, I got it. I have read the issue. May I work on this issue?

**Comment by ishubham21** [comment]
Can I work on this issue?
