### ISSUE TITLE
Update screenshots on https://learning.postman.com/docs/publishing-your-api/viewing-documentation

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#2889]
The following URL link contains screenshots from the previous UI, so could you please update to the latest UI to avoid confusion?
Also, some of the sentences may need edits accordingly such as commenting feature on documentation. 

![Screen_Shot_2021-03-11_at_11_06_55_am](https://user-images.githubusercontent.com/55820883/110715829-18d1c400-825a-11eb-86fd-8ffc4f05b617.png)
![Screen Shot 2021-03-11 at 11 06 50 am](https://user-images.githubusercontent.com/55820883/110715837-1e2f0e80-825a-11eb-93d2-43396ec8b89c.png)
![Screen Shot 2021-03-11 at 11 07 35 am](https://user-images.githubusercontent.com/55820883/110715850-225b2c00-825a-11eb-85bb-d1710bd7a880.png)
![Screen Shot 2021-03-11 at 11 07 48 am](https://user-images.githubusercontent.com/55820883/110715862-27b87680-825a-11eb-9641-f8ce4d02f6ac.png)

**Comment by crew-guy** [comment]
Hey ! I am new to open source contribution. Can you please allot this issue to me ?

**Comment by jerry-li-dev** [comment]
In progress.

**Comment by jerry-li-dev** [comment]
PR approved and merge. Closing out the issue as resolved.
