### ISSUE TITLE
Index lists in search

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2899]
Can we also index lists? Searching for popular libraries like `moment` and `lodash` result in zero results. These libraries are listed on this page: https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries. Created separate issue from #2509 

Last week, searches related to these libraries were 4 of the top 10 searches with no results.

**Comment by crew-guy** [comment]
Hey ! I like this idea. May I please work on this @loopDelicious

**Comment by loopDelicious** [comment]
@crew-guy unfortunately this one will need to be handled by the Postman team due to search service access restrictions.

**Comment by crew-guy** [comment]
No worries !

**Comment by jkonrath-postman** [comment]
Moving this to an internal JIRA. (PC-49)
