### ISSUE TITLE
Update commenting section

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2905]
https://learning.postman.com/docs/collaborating-in-postman/commenting-on-collections/

The UX for adding a comment to a collection has changed a bit with V8 / context bar.
You can add comments to folders now too.
Might be helpful to clarify when comments are associated with a user (vs private user)

**Comment by sowmyaraj92** [comment]
@loopDelicious Thank you for pointing this out. We have made the changes to the documentation and this should go to production in the next PR merge to master!
