### ISSUE TITLE
Add universal search docs

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2906]
Upgrading to V8 mentions universal search on this page (https://learning.postman.com/docs/administration/upgrading-to-v8/), but I couldn't find anything to link to showing how to use the new search functionality.

**Comment by sowmyaraj92** [comment]
Hey @loopDelicious, Upgrading to v8 mostly covers migrating from different versions to Postman v8. We can add a link for universal search functionality. Thank you for pointing it out. 👍

**Comment by loopDelicious** [comment]
@sowmyaraj92 I could not find any documentation of the universal search functionality.  If there's docs for it, you can close this ticket.

**Comment by sowmyaraj92** [comment]
@loopDelicious We will add the documentation to the learning center for **universal search** and link it up from `Upgrading to v8` page.

**Comment by jkonrath-postman** [comment]
Closed w/linked PR.
