### ISSUE TITLE
Adding Public Profiles Level Up Video 

### ISSUE THREAD

**Issue by hannaheneil** [postmanlabs/postman-docs#2909]
Hello! I have made a Level Up about Public Profiles to be added to Additional Resources > Videos. 

https://user-images.githubusercontent.com/62110940/111553348-6c07b300-8741-11eb-80ed-9157f747d156.mp4

Here's the google drive link! https://drive.google.com/file/d/1xjXAn9IXsAYSelo7ivp4qBicXb2CNf6j/view?usp=sharing

thank you!

**Comment by tristandenyer** [comment]
@hannaheneil FYI: I _just_ made a PR to add this video as an embed on one page #2907 
We should also add this as a link in the right sidebar of contextual pages, too, as you suggested.
