### ISSUE TITLE
Environment Management and export documentation outdated/inaccurate

### ISSUE THREAD

**Issue by Thoe** [postmanlabs/postman-docs#2923]
With the latest UI changes, there does not appear to be an environment export option and the "manage exports" (as well as manage collections) UI is entirely different.  Just as a user for ~two years, I was not able to find away to export an environment like I was able to in the past.

**Comment by jkonrath-postman** [comment]
@Thoe This changed slightly - if you've got an environment open, use the actions menu (...) in the upper right, and there's an Export there.  

I'll get this changed in the docs to make it more clear. Thanks for the input!
