### ISSUE TITLE
Run npm run test:lint and fix errors on files (3)

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#2937]
At time of writing, 3 files come back with linting errors using `npm run test:lint`. Not all errors can be solved with `--fix`
* run `npm run test:lint` to view all errors
* run `npm run test:lint-fix` to fix most of them
* hand fix the remaining errors printed in console
* re-run `npm run test:lint` to validate all errors are fixed
* run `npm run dev` to validate fixes did not change the layout or building of the site

**Comment by seita1996** [comment]
@tristandenyer I want to help with this issue

**Comment by tristandenyer** [comment]
That would be awesome, @seita1996 ! Go for it. 
At-tag me if you have any questions or issues, and we'll be happy to help.

**Comment by tristandenyer** [comment]
Fixes are in Production. Thank you for your contribution @seita1996 !
