### ISSUE TITLE
Add link to video Versioning APIs with Tags

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#2948]
Add a link to this video (https://youtu.be/Kq8Ra0ugqoY) in the right sidebar of this page (https://learning.postman.com/docs/collaborating-in-postman/versioning-an-api/) under `Additional Resources` > `VIDEOS`

**Comment by saiteja310** [comment]
Hi, 
I'd like to work on this issue. 

I actually implemented the changes too and it would look something like this.
![image](https://user-images.githubusercontent.com/20738053/113443856-5f0ce400-9410-11eb-8ba0-809307d0efc8.png)

Will raise a pr if this change looks fine.

**Comment by jkonrath-postman** [comment]
@saiteja310 looks good - go ahead and raise a PR and I can approve. Thanks!

**Comment by saiteja310** [comment]
@jkonrath-postman 
Thanks for letting me take this.
Raised a pr. Can you please review it.
https://github.com/postmanlabs/postman-docs/pull/2950

**Comment by jkonrath-postman** [comment]
Thanks for the help! This PR has been merged.
