### ISSUE TITLE
Update all Pricing page links with trailing slash

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#3004]
1. pull down latest from develop
2. search repo for `pricing"` (note double-quote) looking for the links pointing to postman.com Marketing website without trailing slash
3. update links to use trailing slash i.e. `https://www.postman.com/pricing/`
4. update test spec

<img width="645" alt="Screen Shot 2021-04-19 at 1 32 52 PM" src="https://user-images.githubusercontent.com/4358288/115299758-12195500-a114-11eb-969f-5d265361f58f.png">

**Comment by priyalHedau15** [comment]
Hey , could you assign this issue to me

**Comment by ArpitSharma2800** [comment]
Fixed this in #3016

**Comment by tristandenyer** [comment]
Thx for the contribution @ArpitSharma2800 !
