### ISSUE TITLE
[FR] Documentation on how API validation works

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#3010]
**Is your feature request related to a problem? Please describe.**
Currently, the only public facing information on API validation is the following LC article:
https://learning.postman.com/docs/designing-and-developing-your-api/validating-elements-against-schema/#validating-elements

However, it is not very clear/obvious to users what properties are validated and what is not, so it would be helpful to users if this information is publicly available. 

**Describe the solution you'd like**
Include what properties are being validated in Learning Center article

**Additional context**
Filed by Product Support. 
This has already been internally filed. Filing here for public tracking purpose.

**Comment by jkonrath-postman** [comment]
I'm moving this to internal Jira. @taehoshino I've CCed you on TW-70, let's talk there.
