### ISSUE TITLE
[Workspace visibility] Workspace admin and Community manager

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#3015]
On https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions

For business and enterprise teams, we can have community manager roles to control the workspace visibility. This doc also says workspace admin can control the workspace visibility too.
![Screen Shot 2021-04-22 at 9 34 16 am](https://user-images.githubusercontent.com/55820883/115634926-ebdef980-a34d-11eb-9dc5-e96ee944e2c2.png)

However, if a team does have a community manager, **Workspace admin needs to submit a request to the community manager to make the workspace public.** 
(i.e. if there is no community manager assigned, workspace admin can control the visibility)

This is not clearly described in the above article and can create confusion.

**Comment by jkonrath-postman** [comment]
The actual page is https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/ - was that missing "s" at the end a paste error?

**Comment by taehoshino** [comment]
Hey @jkonrath-postman! Thanks for pointing that out! Yes that's a paste error and it should have "s" at the end!

**Comment by claireriley** [comment]
Fix merged in https://github.com/postmanlabs/postman-docs/pull/3492 (https://github.com/postmanlabs/postman-docs/pull/3624)
