### ISSUE TITLE
Update links for SOAP template

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-docs#3021]
The 2 SOAP Template URLs on

https://learning.postman.com/docs/sending-requests/supported-api-frameworks/making-soap-requests/

are dead since the collection is not available.

Update then to point to https://www.postman.com/cs-demo/workspace/public-soap-apis/overview

Update the link at the top of the page, along with this one

![image (5)](https://user-images.githubusercontent.com/14118422/116140527-4e0c6700-a68c-11eb-8fbb-d46ce4d9c184.png)

**Comment by jkonrath-postman** [comment]
I've merged the changes in the linked pull request. Thanks for your help!
