### ISSUE TITLE
Update all documenter.getpostman.com links to use new domain

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#3023]
The https://documenter.getpostman.com/ domain has moved to https://documenter.postman.com/ (just postman.com now).

- Search for documenter.getpostman.com across codebase
- copy URL into browser, remove `get` from domain, and let resolve
- use that URL (why? not all of these may still be active / published. Double-checking they are.)
- if link / doc is 404, remove link from doc.

<img width="570" alt="Screen Shot 2021-04-26 at 4 27 28 PM" src="https://user-images.githubusercontent.com/4358288/116163275-4d83c880-a6ac-11eb-8658-a844c1d47883.png">
(not a full search results)

**Comment by orama254** [comment]
Greetings @tristandenyer 

I'd be delighted to take up this task

**Comment by jkonrath-postman** [comment]
@orama254 Your changes have been merged. Thanks for your help on this!
