### ISSUE TITLE
Request to include "Update collection" flow in GitHub/Integration page.

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#3026]
At the moment we do have details on how to create **Two-way sync** on the following page below:

- https://learning.postman.com/docs/integrations/available-integrations/github/#syncing-your-api-schemas-on-github 

It would be really helpful if we could add details on. Below is a rough format on what could be added:

- How to update the collection, synced with GitHub?

   >  Collection generated for API synced with GitHub on Postman can be updated as below:
   
        1. Make changes for the API on GitHub. 
        2. These changes are reflected for this API on Postman. 
        3. To make sure these changes reflect on the collection you'll need to use the Validate option as per this doc [here](https://learning.postman.com/docs/collaborating-in-postman/versioning-an-api/#validating-apis)

Or either cross-linking data should help users surface on more information here.

_Filed by Product Support_

**Comment by jkonrath-postman** [comment]
@Raj-postman do you have a ticket on this I can take a look at? (Reply offline if needed...)
