### ISSUE TITLE
Remove "Automatically persist variable values" section - no longer available since v8.0.8

### ISSUE THREAD

**Issue by SabriH10** [postmanlabs/postman-docs#3029]
Hi team, I believe since v8.0.8 https://www.postman.com/downloads/release-notes/ this setting is no longer available in the app however the documentation still seems to instruct that it does:
https://learning.postman.com/docs/getting-started/settings/#request 

>Automatically persist variable values: Enabling this will persist the current value of variables to the initial value at the end of every request execution. This option is by default off for new users. For old users upgrading to the newest versions, this option is turned on. These settings apply only when assigning current values using scripts, for instance pre-request or test scripts. For more detail, refer to Using variables.

**Comment by sowmyaraj92** [comment]
@SabriH10 Hello Sabri, Thank you for bringing this to our notice. I have removed the section and raised a PR which should hopefully fix this!
