### ISSUE TITLE
Multi region monitoring is not available for free plan

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#3057]
https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors/#multi-region-monitoring

The above section of the doc does not mention about plan type, however, multi region monitoring is not available for free plan as the pop-up shows:
![image (1)](https://user-images.githubusercontent.com/55820883/117738310-15998b00-b23f-11eb-8bfb-8f06f3533608.png)

**Comment by taehoshino** [comment]
@sowmyaraj92 Thanks for the PR! For free tier, we also have a limitation on the use of "Minute Timer" as below. Would you think it would be useful to include this information somewhere? 
<img width="656" alt="Screenshot 2021-05-10 at 5 56 39 PM" src="https://user-images.githubusercontent.com/55820883/117895613-0fb8ae00-b302-11eb-9542-e6d75d7e9f2f.png">

**Comment by sowmyaraj92** [comment]
@taehoshino Are we good if we include a note under the Time limits section? 

<img width="1276" alt="2021-05-12_12-47-48" src="https://user-images.githubusercontent.com/45622594/117934567-6cc35c80-b320-11eb-9737-efcef850a6c2.png">

**Comment by taehoshino** [comment]
@sowmyaraj92 
I think it would make more sense to include "(or every hour for free plan)" after "Monitors can be scheduled as frequently as every five minutes" as the ability to run monitors every 5 minutes is only for paid plans.
![Screen Shot 2021-05-13 at 10 24 35 am](https://user-images.githubusercontent.com/55820883/118060162-778bf900-b3d5-11eb-844e-29ae954d1fd7.png)

**Comment by sowmyaraj92** [comment]
Done 🎉

**Comment by charlie-postman** [comment]
@sowmyaraj92 @taehoshino  Appreciate that folks take ownership and quick actions to make the documentation changes for monitoring products. Thank you so much!  May I have a request to keep @claireriley and me (PM) in the loop for the documentation changes for monitoring?  Let us know any monitoring documentation gaps and suggestions so we can handle them holistically, assure the correct documentation, and be aware of what is going on with monitoring documentation.  I hope this sounds like a fair ask to you guys.

**Comment by jkonrath-postman** [comment]
Hi @charlie-postman - definitely. Let me ping you in Slack and we can talk more about the best way to handle this.

**Comment by charlie-postman** [comment]
@claireriley  Can you please help tweak the wording, "Monitors can be scheduled as frequently as every hour for free plans or even every five minutes for paid plans and will run through each request in your collection"?  This is wordy. Also, we need to emphasize the 5-minute frequency run (for paid plans). I suggest we put the caveat for free plans in a bracket.  I am thinking of something like "Monitors can be scheduled as frequently as five minutes for paid plans (every hour for free plans) and will run through each request in your collection"
![image](https://user-images.githubusercontent.com/78068129/118308056-5c39f000-b4a0-11eb-928f-602cdfd825f2.png)

**Comment by charlie-postman** [comment]
For the update of Multi-region monitoring, the font size of the screenshot is too big compared with the normal texts in the documentation. Also, I suggest we provide the explanation in the front. The current statement sounds like a demand to me as a user. Something to consider: "if you are on a Free plan, you are not authorized to manually select specific geographic regions. You may Upgrade your Postman plan "

![image](https://user-images.githubusercontent.com/78068129/118308675-1893b600-b4a1-11eb-86a3-114c3a0eb62d.png)

**Comment by jkonrath-postman** [comment]
@charlie-postman let me reopen this and assign back to @claireriley 

Claire, you might want to start a new PR for this after you make changes. (Not sure if it makes more sense to move this to a new issue, I'll leave it up to you.)

**Comment by charlie-postman** [comment]
Thanks, @jkonrath-postman !

**Comment by claireriley** [comment]
Closing this issue as I've moved the noted improvements to jira [MONITOR-3097](https://postmanlabs.atlassian.net/browse/MONITOR-3097)
