### ISSUE TITLE
Adding summaries and categories to public workspace and collections

### ISSUE THREAD

**Issue by meenakshi-dhanani** [postmanlabs/postman-docs#3065]
Adding summaries and categories is important for discovery in search. At the moment there isn't a mention of how to add summaries and categories to a public workspace/collections. 

This needs some more documenting because it's not very obvious where the edit listing option is. It comes up on navigating to the team page - https://www.postman.com/postman?tab=collections

**Comment by jkonrath-postman** [comment]
I think this might be changing to make this more obvious (see Jira APINET-1702) but either way, it should be documented.
@jerry-li-dev can you take a look?

**Comment by jerry-li-dev** [comment]
The PR is in progress.

**Comment by jerry-li-dev** [comment]
https://github.com/postmanlabs/postman-docs/pull/3204

**Comment by jerry-li-dev** [comment]
PR approved and merged to develop.
