### ISSUE TITLE
Request documentation for error message "Parse Error: Expected dot"

### ISSUE THREAD

**Issue by JMAnderson1982** [postmanlabs/postman-docs#3087]
One of our clients is receiving the error above, "Parse Error:  Expected dot" when attempting to connect to our API.  We have no jumping off point for helping them find this error, and cannot reproduce the error on our end.  Any documentation around this or other errors would be extremely helpful.

**Comment by jkonrath-postman** [comment]
Hi @username - I've opened an internal issue to discuss how we can best address this. I'm not sure if it would be best maintained in an article in our Learning Center, or a KB item in our support site, but we'll discuss the best long-term approach.

In the short term, you might want to report the issue with support at https://github.com/postmanlabs/postman-app-support  and maybe they've seen this specific issue.
