### ISSUE TITLE
Outdated content: request description 

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-docs#3090]
The [Documenting request detail](https://learning.postman.com/docs/publishing-your-api/authoring-your-documentation/#documenting-request-detail) section of the **Authoring your Documentation** article appears to be out of date.

**Outdated (docs)**

It is shown that you can edit the request description from the area near the request name. 

![image](https://user-images.githubusercontent.com/9841162/119861995-e0429d80-becc-11eb-9fa7-5ac5676a7da0.png)

**Actual**

This is no longer true since a Postman UI update has removed the option to edit request descriptions like shown.

![image](https://user-images.githubusercontent.com/9841162/119865294-63192780-bed0-11eb-85f0-93ddadd967c4.png)

Instead it seems the Documentation markdown context is now the preferred way to describe requests

**Comment by jerry-li-dev** [comment]
Resolved in: https://github.com/postmanlabs/postman-docs/pull/3128
