### ISSUE TITLE
# anchor/tag in HTTP Request to the documentation does not work

### ISSUE THREAD

**Issue by ramosmediavalet** [postmanlabs/postman-docs#3117]
Hello,

It's a common practice to link to parts of the API Documentation in other documents, e-mails or customer communications.

The link sometimes needs to be precise and send to the specific FOLDER or REQUEST.

If we try to do it, it does not work, instead all links will ignore the anchor/tag and will open the top of the page.

https://docs.mediavalet.com/#4ea51e9f-bfd3-4f2d-9469-3bec0295ea37
![image](https://user-images.githubusercontent.com/82291124/121432107-1a7d5780-c92f-11eb-93ed-dd449b058f41.png)

https://docs.mediavalet.com/#77dbec30-65fa-4c03-809c-7cd72178b041
![image](https://user-images.githubusercontent.com/82291124/121432066-105b5900-c92f-11eb-8ffb-a9f941a21eb7.png)

How do I link to my specific elements (request/folders etc) externally without being sent back to the top page?

Can you please help with this issue?

Thank you.
Felipe Ramos

**Comment by jkonrath-postman** [comment]
Hi @ramosmediavalet  - this sounds like it might be an issue with the documentation feature in the Postman app. This is the repo for the Learning Center documentation contents. Please feel free to report this issue with the product support team at https://github.com/postmanlabs/postman-app-support  Thanks!
