### ISSUE TITLE
Documentation only shows one Authorization method at the operation level, although OpenAPI allows for defining multiple security types.

### ISSUE THREAD

**Issue by CarrieRaglan** [postmanlabs/postman-docs#3124]
REST APIs support several authentication types, documented within OpenAPI through the security schemes. Security is an array of hashmaps, where each hashmap contains one or more named security schemes.

Postman's documentation only shows one Authorization method, and also does not display the securities name or description.
https://spec.openapis.org/oas/v3.0.3#fixed-fields-22

`
security:
  - basicAuth: []
  - apiKey: []
  - apiKey2: []
`

**Comment by jkonrath-postman** [comment]
Hi @CarrieRaglan, thanks for the comment. Where exactly were you seeing this in the documentation?

**Comment by CarrieRaglan** [comment]
In Postman's Authorization section of the documentation, only one security scheme is displayed. I've attached a sample openAPI json.

![image](https://user-images.githubusercontent.com/63308530/123298501-6acaec80-d4cd-11eb-9d2e-4bdf8ee62297.png)

![image](https://user-images.githubusercontent.com/63308530/123298587-80d8ad00-d4cd-11eb-95ff-f591f3f1e929.png)
[petStoreSecutitySchemes.zip](https://github.com/postmanlabs/postman-docs/files/6710745/petStoreSecutitySchemes.zip)

**Comment by jkonrath-postman** [comment]
Hi @CarrieRaglan  - OK, I see what you mean now. This would be an issue with the Postman app and how it's generating documentation. This is the repo for user docs hosted on our Learning Center. Please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!

**Comment by CarrieRaglan** [comment]
Sorry for the confusion, I saw Documentation for Postman and just assumed this was Postman API Documentation. I'll create a new case.
