### ISSUE TITLE
Update go.postman links

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#3141]
Update all `go.postman.co/build` HREFs to be `go.postman.co/home`.

<img width="553" alt="Screen Shot 2021-06-16 at 3 15 47 PM" src="https://user-images.githubusercontent.com/4358288/122301592-bcfc8400-ceb5-11eb-8db8-6465861293be.png">

**Comment by soham4abc** [comment]
Can I work on this issue?
