### ISSUE TITLE
Add public workspaces to creating workspaces page

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-docs#3158]
Creating workspaces page can mention public workspaces as one of the types of workspaces, or link to the public workspaces page, or have a callout (pulled quote) like private workspaces.

Creating workspaces page: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/
Public workspaces page: https://learning.postman.com/docs/collaborating-in-postman/public-workspaces/

**Comment by soham4abc** [comment]
I am willing to work on this issue if possible pls assign!

**Comment by sayansisodiya** [comment]
@soham4abc , I actually completed this issue but forgot to close it. My apologies.

**Comment by soham4abc** [comment]
> @soham4abc , I actually completed this issue but forgot to close it. My apologies.

No problem!
