### ISSUE TITLE
No mention of relaystate for setting up SAML 

### ISSUE THREAD

**Issue by taehoshino** [postmanlabs/postman-docs#3160]
This request is for GSuite SAML setting (https://learning.postman.com/docs/administration/sso/saml-gsuite/). 

Although it is required to ensure that the relay state is generated and configured in IdP settings, there is no mention about where to set this value for GSuite. 

According to the information in the following links, RelayState value should be pasted in "Start URL" field which is not very intuitive (unlike other IdP settings where "Relay State" field is available)

https://bime.zendesk.com/hc/en-us/community/posts/115000593527/comments/115000877627
https://stackoverflow.com/a/41899432

As this creates confusion and we often see customers facing issues due to relay state being misconfigured/not configured at all, adding this piece of information in LC would help our customers a lot.

**Comment by soham4abc** [comment]
One more problem the table at the end of the page is not at all arranged correctly. If this issue is free I would like to work on it! If possible pls assign I will start working on it right away!

**Comment by claireriley** [comment]
Closing this issue as I've added this request to jira TW-199.
