### ISSUE TITLE
Add Issue Templates in issues section

### ISSUE THREAD

**Issue by Ayush7614** [postmanlabs/postman-docs#3165]
* Like we have to add issue templates in project

**Comment by jkonrath-postman** [comment]
Let me look into this. (Hint: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by Ayush7614** [comment]
@jkonrath-postman Okk sir plss assign me if it looks good

**Comment by jkonrath-postman** [comment]
Hi @Ayush7614 - thanks, but actually our support team does this already in https://github.com/postmanlabs/postman-app-support/issues - I will create the templates based on their verbiage.

**Comment by Ayush7614** [comment]
@jkonrath-postman sir but this is not in the postman-docs so i think that we have also in this one so that`s why i raise this issue

**Comment by Ayush7614** [comment]
if you assign me then i will work on the issue
