### ISSUE TITLE
Add Public Workspaces resource to LC sidebar

### ISSUE THREAD

**Issue by meenakshi-dhanani** [postmanlabs/postman-docs#3347]
**Is your request related to a problem? Please describe.**
There are a lot of good public workspace samples that the sidebar can link to

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/14279061/128329081-d48ae614-2f1c-4458-9e43-69dd86404875.png)

**Curated Public workspaces**
[Postman API](https://www.postman.com/postman/workspace/postman-public-workspace/collection/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?ctx=documentation)
[Postman Public Workspace](https://www.postman.com/postman/workspace/405e0480-49cf-463b-8052-6c0d05a8e8f3)
[30 days of Postman for developers](https://www.postman.com/postman/workspace/30-days-of-postman-for-developers/overview)

[Postman Answers](https://www.postman.com/postman/workspace/aa5fb3b8-0090-4b5e-b3b4-fa5c1f2d080d)
[More Visualizer Examples](https://www.postman.com/postman/workspace/e9bb1adb-2f2e-4ace-a482-38c570d65275)

[Test examples in Postman](https://www.postman.com/postman/workspace/70c7199b-6aee-49a6-a90f-025ad614f294)
[Postman Security Workspace](https://www.postman.com/postman/workspace/62d58d93-7e0c-45bf-9daa-cc8e531fc344)

[Support Workspace](https://www.postman.com/postman/workspace/b10c50ff-e3f3-4647-bae8-47254ffb802b)
[Postman API Monitoring Examples](https://www.postman.com/postman/workspace/e348c5a0-2965-44cc-87ed-7b316516f38d)

[Unbreakable API](https://www.postman.com/postman/workspace/b2d28b8c-70a9-4101-8a39-782ab83fed1b) - negative testing - monitors
[Sample Visualizations](https://www.postman.com/postman/workspace/be88701c-2acc-4e11-8fdf-ac7ee72982a6)
[Postman Loves Slack](https://www.postman.com/postman/workspace/4be86d9c-6576-4369-b74f-43991df7a4bd) - webhooks?
[Postman Collaboration](https://www.postman.com/cs-demo/workspace/0ae8b8bc-6b31-4ede-85a6-53ad0ef6077b)
[Public GraphQL APIs](https://www.postman.com/cs-demo/workspace/9e8c8a19-bb76-46af-9e8d-5747bf8fcce5)
[Public SOAP APIs](https://www.postman.com/cs-demo/workspace/d99d8d90-0d4f-4111-8348-f7e35c41e037)
[Public REST APIs](https://www.postman.com/cs-demo/workspace/2e243885-318c-4b51-bf5c-8bf2241e4acd)
[GraphQL examples](https://www.postman.com/devrel/workspace/f12c0652-9c9d-4813-968b-c8ed0b3f0022)
[Fakerjs example](https://www.postman.com/devrel/workspace/f1981ff7-a7c7-473a-a2d9-190c407c9df4)

**Comment by Samridhi-98** [comment]
@meenakshi-dhanani  Is this issue still active?
I would like to work on it.

**Comment by claireriley** [comment]
Hey @Samridhi-98 ! Happy to let you take a go at this, I've added you as an assignee. 

Please note this one requires a bit of curation as the public workspaces will need to be added to all appropriate pages' sidebars in the docs.

Please create a PR when you're ready and add me as a reviewer, and we can collaborate from there 🥳
