### ISSUE TITLE
Inconsistent terms in Restoring deleted collections

### ISSUE THREAD

**Issue by VinithAnbarasu** [postmanlabs/postman-docs#3402]
**Describe the bug**
* In Postman app it is used “Restore” but it is mentioned “Recovering deleted collections”. It will not be helpful for user when searching.
* Screenshot irrelevant. You could use a restore screenshot.
*Recover a deleted collection that is larger than 30 MB - Can be displayed in the top as it is common to the three points displayed.

**Pages affected**
https://learning.postman.com/docs/sending-requests/intro-to-collections/#recovering-deleted-collections

**Screenshots**
![image](https://user-images.githubusercontent.com/83657336/131216393-d9acd24a-eb5e-4942-9eea-1d2aa86baad6.png)

Let me know if I can solve this. Already I have made some progress.

**Comment by jkonrath-postman** [comment]
Hi @VinithAnbarasu, thanks for the offer to work on this. Feel free to create a PR with your changes and we can take a look. Thanks!

**Comment by soham4abc** [comment]
I would Like to work on this issue!

**Comment by jkonrath-postman** [comment]
I researched further, and our pricing page (https://www.postman.com/pricing/) officially calls this feature "Recover deleted collections" and links to this heading with this name, which means I can't change it. 

I'll look into the naming of this within the product, but I don't control that. Thanks for bringing this up, though.
