### ISSUE TITLE
Discovering templates needs to be deprecated

### ISSUE THREAD

**Issue by meenakshi-dhanani** [postmanlabs/postman-docs#3455]
**Describe the bug**
Templates are no longer part of the public API network. The screenshots and the feature reflect the old UI. This post could be replaced with how to find Discovering workspaces/APIs/Teams on the network instead.

**Pages affected**
https://learning.postman.com/docs/getting-started/importing-templates/

**Comment by jkonrath-postman** [comment]
We're doing this internally - see Jira TW-64
