### ISSUE TITLE
add "State of the API" to the top navigation

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#3661]
- add to top nav in "Resources and support" drawer, under "Case studies"
- label is "State of the API"
- link is /state-of-api/
<img width="538" alt="Screen Shot 2021-11-01 at 9 43 32 AM" src="https://user-images.githubusercontent.com/4358288/139708396-56a1510d-71e4-40ac-9bc5-4b106f36312c.png">

**Comment by KushGabani** [comment]
Can you assign me to this? Thanks!

**Comment by KushGabani** [comment]
Thank you!! I've already created a pill request. You can review it.
