### ISSUE TITLE
FAQs or Auth token for logging in to the desktop app to be included in the LC Docs

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [postmanlabs/postman-docs#3790]
Here is the flow we follow to log in - https://www.youtube.com/watch?v=tCzeCpRZhuY

**Comment by jkonrath-postman** [comment]
@claireriley can you look if this would be in the work you're doing on auth now?

**Comment by claireriley** [comment]
Thanks for noting this @VaishnaviChallaPostman , I'm moving this request internally to TW-319.
