### ISSUE TITLE
Disabling SSL certificate does not work

### ISSUE THREAD

**Issue by mathureshruti** [postmanlabs/postman-docs#3820]
Hello,

I am trying to create Documentation API on postman. I am getting the error 

Warning: Unable to verify the first certificate

I had googled about this error and disable my SSL certificate . Still i am getting this error.

How can i solve it? can anyone help me out?

![image](https://user-images.githubusercontent.com/57104828/149509904-6abc222e-40ab-4734-9d7d-dce22538a86e.png)

![image](https://user-images.githubusercontent.com/57104828/149509966-f429d627-3ec7-44fc-8cc5-4ba7930d01ac.png)

![image](https://user-images.githubusercontent.com/57104828/149510016-16292ef8-9844-48d2-abe1-321ae0f21d9c.png)

![image](https://user-images.githubusercontent.com/57104828/149510064-5a905d25-cfb1-4d59-a12a-b208fe4c0a0f.png)

**Comment by jkonrath-postman** [comment]
Hi @mathureshruti - sorry, this repo is for the learning center doc site for Postman. For issues with the documentation feature in Postman, try opening a ticket in product support's issue repo here: https://github.com/postmanlabs/postman-app-support
