### ISSUE TITLE
gRPC SSL With SANs

### ISSUE THREAD

**Issue by trevatk** [postmanlabs/postman-docs#3857]
I'm rather new to developing web apps so bare with me... 

I've been working with Golang and recently came across the new gRPC testing capabilities within the Postman app. I've been attempting to test a gRPC call through a ngrok tcp tunnel. However, the SSL certificate I'm using is required to be generated with SANs. Postman is unable to send the request with a .crt generated with SANs to a Golang gRPC service. 

When I generate the SSL certificate without SANs everything works great. Unfortunately Golang prevents a client connection when the .crt  is a legacy file. The only error message I am able to see is "14 UNAVAILABLE" next to "Status". 

Postman works great the Golang gRPC service when a legacy SSL file is generated, however, that will break my Golang client code. 

Is there anyway I can look at logs to provide a better error message?

**Comment by jkonrath-postman** [comment]
Hi @trevatk - this repo is for the Postman documentation, not the app itself. You might try raising this issue on the Postman support repo over here: https://github.com/postmanlabs/postman-app-support
