### ISSUE TITLE
import from URL doesn't work anymore

### ISSUE THREAD

**Issue by mzatko** [postmanlabs/postman-docs#3870]
collection and API json import from URL stopped working in postman version 9.13 (maybe little earlier version)
with message: "error while fetching data from link"
Now I need to download from URL (using postman e.g.) into a file and import it from the file afterwards

It definitely worked directly from URL few weeks ago

**Comment by jkonrath-postman** [comment]
Hi @mzatko - this is the repo for Postman documentation. You might want to raise this issue over at support's repo instead: https://github.com/postmanlabs/postman-app-support

(Also I tried this in 9.12.2 using the API schema at `https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml` and it worked, but maybe there is a different edge case causing an issue. Make sure to let them know which link you're using, so they can verify.)
