### ISSUE TITLE
GraphQL schema auto-fetch does not use collection authorization settings

### ISSUE THREAD

**Issue by moon-sam** [postmanlabs/postman-docs#4013]
**Describe the bug**
Auto-fetch requests are missing the `x-api-key` header that is set in collection Auth settings.

- I have a collection A with an x-api-key header set in the authorization settings.
- When I make a post request from within the collection, the request succeeds.
- Calls dispatched from auto-fetch fail with 403
- Inspecting the console shows the `x-api-key` header is not included in the auto-fetch

If I turn off API key auth on my api the auto fetch calls succeed.

**Pages affected**
https://learning.postman.com/docs/sending-requests/supported-api-frameworks/graphql/

**Screenshots**
Postman console output from successful API request from request within collection that specifies authz header:

```

POST https://api.hellomoon.io/graphql
200
185 ms
Network
Request Headers
x-api-key: [REDACTED BY moon-sam]
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Postman-Token: d82006f8-3797-4b0e-82df-592d9935f4a9
Host: api.hellomoon.io
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 222
```

Postman console output when refresh arrow is clicked next to auto-fetch.

```
POST https://api.hellomoon.io/graphql
403
32 ms
Network
Request Headers
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Postman-Token: d3d1aa92-63a3-46cd-ad50-6968bcbaed1c
Host: api.hellomoon.io
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 1728
```

**Additional context**

**Comment by jkonrath-postman** [comment]
Hi @moon-sam - this sounds like it's a bug. This repo is where we store the Learning Center docs - you might want to try raising an issue on product support's repo at https://github.com/postmanlabs/postman-app-support.
