### ISSUE TITLE
Remove double icon from sm and md breakpoint search bar

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-docs#4036]
**Describe the bug**
When in small and medium breakpoints, the dropdown for top nav shows a search bar with two icons.

**Pages affected**
All

**Screenshots**
<img width="353" alt="Screen Shot 2022-05-06 at 10 11 46" src="https://user-images.githubusercontent.com/4358288/167180426-5edbd10c-01a6-43e8-9335-1b14f8099670.png">

**Acceptance criteria**
Show only one magnifying glass icon
While in there, see about shifting the search box to better align with above text on left.

**Comment by ch264** [comment]
This was fixed back when
