### ISSUE TITLE
Dynamic variable: `$randomAvatarImage` return unusable links

### ISSUE THREAD

**Issue by pbaranski** [postmanlabs/postman-docs#4047]
**Describe the bug**
Dynamic variable: `$randomAvatarImage` not working correctly since provider fakercloud.com does not exist.
Returned links when using `$randomAvatarImage` looks like:
https://cdn.fakercloud.com/avatars/mohanrohith_128.jpg
using link gives response:
Error: connect ECONNREFUSED 67.227.226.240:443

**Pages affected**
[Dynamic variables / Images](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/#images)

**Additional context**
Can be problem with faker library

**Comment by jkonrath-postman** [comment]
This is a faker problem. Postman still uses v5.5.3 and this was fixed in a later version. Here's a feature request on fixing this, but I don't have any information beyond that: https://github.com/postmanlabs/postman-app-support/issues/11435
