### ISSUE TITLE
[Question] Wrap existing REST endpoint into GraphQL

### ISSUE THREAD

**Issue by scheung38** [postmanlabs/postman-docs#4066]
**Is your request related to a problem? Please describe.**
Saw this article
https://www.prisma.io/blog/how-to-wrap-a-rest-api-with-graphql-8bf3fb17547d

**Describe the solution you'd like**
Is it possible to convert an existing external REST API into GraphQL?

**Comment by jkonrath-postman** [comment]
Hi @scheung38 - that sounds like it might be a question for support. This is the repo for Postman's documentation. You might try asking over at https://github.com/postmanlabs/postman-app-support.
