### ISSUE TITLE
Postman version mismatch (version 1.19.0 -vs- 1.19.3)

### ISSUE THREAD

**Issue by pjwelsh** [postmanlabs/postman-docs#4082]
Postman website (https://www.postman.com/downloads/) shows Linux version 1.19.3 is the current release
However, both release notes (https://www.postman.com/downloads/release-notes/) and actual included app/resources/app/package.json have version 1.19.0

Please correct the inconsistency.

![image](https://user-images.githubusercontent.com/7603888/171418513-a0904977-06dd-4c76-be14-9632e865d890.png)
![image](https://user-images.githubusercontent.com/7603888/171419024-4715509c-a193-406b-b3d6-557265186c04.png)

**Comment by jkonrath-postman** [comment]
Hi @pjwelsh, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
