### ISSUE TITLE
OAuth 1.0 Signature Generation

### ISSUE THREAD

**Issue by gainesyeild** [postmanlabs/postman-docs#4218]
How is oauth_signature generated when using OAuth 1.0. I am trying to recreate the request but all I see is generated signature. I am using HMAC-SHA1 signature method. Is it some combination of Consumer Key, timestamp, Consumer Secret, Access Token, and Token Secret?

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
