### ISSUE TITLE
Documentation Feedback: Cookie Manipulation

### ISSUE THREAD

**Issue by Postmanaut-Adrian** [postmanlabs/postman-docs#4312]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

Hi

I’ve started using postman.

I’m having some issues with manipulating cookies through scripting and I’m sure I’m not the only one.

I think that in the documentation of the following url [here, ](https://learning.postman.com/docs/sending-requests/cookies/ )It might need to be mentioned that not all calls are executed in sync.

Ex.

When first calling cookies clear and then setting the cookies and including some console.log inside the callbacks I’ve noticed that the clear is executed after the set which has  some strange side effects

```
let jar = pm.cookies.jar();
jar.clear(‘site’);
jar.set(‘site’, { name: 'cookie', value: '1', httpOnly: true });
```

A way for fixing this was to create the cookies inside the callback of the clear method.

```
let jar = pm.cookies.jar();
jar.clear(‘site’, (error) => {
    jar.set(‘site’, { name: 'cookie', value: '1', httpOnly: true });
});
```
I could only realize this through the use of console logs to determine the order in which things are executed, but maybe I’ve missed this.

I hope this helps other users by being more specific in the documentation

- Stefan

### Pages affected

https://learning.postman.com/docs/sending-requests/cookies/

**Comment by Postmanaut-Adrian** [comment]
Ticket from user: https://postman.zendesk.com/agent/tickets/119793

**Comment by jkonrath-postman** [comment]
Hi @Postmanaut-Adrian thanks for sending this over - I've moved it to an internal Jira (TW-721) and we'll fix it there. Thanks!
