### ISSUE TITLE
Is it possible to pass path variables in pm.sendrequest() method ??

### ISSUE THREAD

**Issue by FidaUrRahman** [postmanlabs/postman-docs#4344]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have end point similar to this 
{{baseUrl}}/api/v1/test-case/project-id/:id?page=0&pageSize=20

i wanted to use pm.sendrequest() method in prerequest script 
and got stucked at passing this path variable (id)

### Describe the solution you'd like

a complete documentation of pm.sendrequest() would be quite helpful like

passing
Body,
query params
path params
all types of authentication
etc.,

**Comment by jkonrath-postman** [comment]
@FidaUrRahman I've added an internal issue to add more information to this page in the future: https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/
