### ISSUE TITLE
Learning Center bug report

### ISSUE THREAD

**Issue by akinard-postman** [postmanlabs/postman-docs#4387]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

In the [**Generating a GitHub personal access token**](https://learning.postman.com/docs/integrations/available-integrations/github/#generating-a-github-personal-access-token) section of the [**GitHub**](https://learning.postman.com/docs/integrations/available-integrations/github/) documentation it describes how to create a PAT. However, there are two options for token generation (screenshot attached). Step 2 in the section doesn't specifically mention that users need to create/use the "classic" version of the token. It could be useful to clarify you should create a **Token (classic)** token, not the **Fine-grained token (Beta)** token.

### Pages affected

https://learning.postman.com/docs/integrations/available-integrations/github/

### Screenshots

<img width="297" alt="Screen Shot 2022-11-02 at 11 42 30 AM" src="https://user-images.githubusercontent.com/113702138/199550626-f56b7d44-a00b-4e90-a95b-0ff89327bc1d.png">

### Additional context

When I was testing how to link a collection to a GitHub account I was having issues because I was trying to use the fine-grained beta token. Turns out that I needed to use the original (classic) token.

**Comment by jkonrath-postman** [comment]
This section of the doc was changed about 8 months ago and now supersedes this.
