### ISSUE TITLE
Possibility to create a fragment of documentation and reuse it in whatever documentation

### ISSUE THREAD

**Issue by mtwinux** [postmanlabs/postman-docs#4420]
**Is your request related to a problem? Please describe.**
No it's a feature request :)

**Describe the solution you'd like**
Hi, we have documentation for many api and we have slightly the same documentation base each time : 
 - versioning on url
 - authentication
 - errors handling
 - etc.

It would be great to create those doc like 'fragments' then reuse it when we need it, so if something changes, we only apply those changes on the fragment, you see ?

Maybe it's already possible but i didn't find the way :)

**Comment by jkonrath-postman** [comment]
Hi @mtwinux - this repo is for Postman's end-user documentation site. For feature requests on the product itself, head over to https://github.com/postmanlabs/postman-app-support and raise an issue there. Thanks!
