### ISSUE TITLE
Flows: FQL: How to select top-level array?

### ISSUE THREAD

**Issue by clairefro** [postmanlabs/postman-docs#4433]
**Is your request related to a problem? Please describe.**
Current Flows FQL docs outline how to select data in JSON objects that have keys, but no mention of how to select data from a top-level array (ex: the API response is `[1,2,3,4]`)

**Describe the solution you'd like**
Describe how to select value(s) from a top level array in FQL (if this is possible)

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/postmanlabs/postman-docs/blob/develop/src/pages/docs/postman-flows/flows-query-language/introduction-to-fql.md

**Comment by jkonrath-postman** [comment]
Moving this internally to TW-784.
