### ISSUE TITLE
Request to add information about Collection Key access in LC doc

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#4441]
**Is your request related to a problem? Please describe.**
We now have a way to share collections with other users based on "Collection Access Key" but steps on how to generate, update or delete is missing from our documentation

**Describe the solution you'd like**
Include this on our API keys section or collections page to provide more information to users on the same.
- https://learning.postman.com/docs/developer/intro-api/#generating-a-postman-api-key
- https://learning.postman.com/docs/collaborating-in-postman/sharing/#sharing-postman-elements

**Describe alternatives you've considered**
- At the moment, we share this context with users using screen-record

**Additional context**
Collection access keys :
<img width="801" alt="image" src="https://user-images.githubusercontent.com/47771757/204724597-d7fe7395-625a-4fe4-9c4d-05067356dc13.png">

**Comment by jkonrath-postman** [comment]
@Raj-postman Heather's working on this over in this PR: https://github.com/postmanlabs/postman-docs/pull/4438 - feel free to review when she's done - thanks!
