### ISSUE TITLE
Test Scripts inclusion thread

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#4488]
**Is your request related to a problem? Please describe.**
There are few missing test scripts on the [learning centre page](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#contents), either for a particular operation or specific action from the app. Hence creating this thread in order to collect those suggestions to have them reviewed before including them in the documentation.

**Describe the solution you'd like**
Adding one case as an example:
- How to Append collection variable to the URL 

> pm.sendRequest({
'method': 'GET',
'url': 'https://postman-echo.com/' + pm.collectionVariables.get("method"),
'header': {
'token': 'A113'
}
})

**Additional context**
_Filed by Product Support Team through feedback_

**Comment by Raj-postman** [comment]
Not sure if present but we saw users using scripts to access Postman elements.

> pm.environment.id
> pm.variables.id

Are they valid? How do we use them?

**Comment by jkonrath-postman** [comment]
Moving this internally to Jira TW-862.
