### ISSUE TITLE
problem to set metadata in grpc post

### ISSUE THREAD

**Issue by MNouroozi** [postmanlabs/postman-docs#4539]
hi
Does Postman support grpc+web method?
I send a parameter in the metadata section, but it applies the default metadata
![Screenshot 1401-11-04 at 14 21 25](https://user-images.githubusercontent.com/37396752/214273561-89ae687e-1112-43c8-892b-82e0b7740415.jpg)
kreya is supported and send request get response 
![Screenshot 1401-11-04 at 14 23 19](https://user-images.githubusercontent.com/37396752/214273752-259939b4-995b-47e0-8deb-23d466324ff7.jpg)
But I want to use postman, I don't know if it has such a feature or not. Thank you for your guidance

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
