### ISSUE TITLE
Published documenter page gets unpublished after few seconds

### ISSUE THREAD

**Issue by karaburmication** [postmanlabs/postman-docs#4569]
**Is your request related to a problem? Please describe.**
When I update styling (highlight color) for my public documentation and then publish it, it gets unpublished after a few seconds.

**Describe the solution you'd like**
The public page should remain published.

**Additional context**
![postman issue](https://user-images.githubusercontent.com/17314795/218275256-b235471c-90c4-4787-b4ce-cb13b775e52b.gif)

**Comment by karaburmication** [comment]
Wrong tag

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
