### ISSUE TITLE
Auto save the documentation

### ISSUE THREAD

**Issue by Vamshi2702** [postmanlabs/postman-docs#4756]
While working on documentation, when we need to pass through other collections, the current documentation dialog closes. And when I reopen it, it shows nothing. All the content worked on documentation gets vanishing. I think like google docs, auto save option should be there that would be helpful.

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you have a potential feature request for the Postman app. This is the repo for the Learning Center documentation. If you would like to make a feature request for the Postman app, please feel free to add an issue for the product at https://github.com/postmanlabs/postman-app-support  Thanks!
