### ISSUE TITLE
Ability to copy links in documentation

### ISSUE THREAD

**Issue by Vamshi2702** [postmanlabs/postman-docs#4757]
When we hover over the links in the documentation, currently, only edit and delink options show up. I think having other option to copy the link would be more flexible.

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you have a potential feature request for the Postman app. This is the repo for the Learning Center documentation. If you would like to make a feature request for the Postman app, please feel free to add an issue for the product at https://github.com/postmanlabs/postman-app-support  Thanks!
