### ISSUE TITLE
Ability to import templates in the documentation

### ISSUE THREAD

**Issue by Vamshi2702** [postmanlabs/postman-docs#4758]
I need to create each and the same type of document every time, which is repetitive and takes more time. While creating new docs, if there is any option that we can import templates from any sample doc, that would save a lot of time, since copy pasting the tables from any documents not showing up in the doc, I think having these templates can be better to direct import and work upon.

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you have a potential feature request for the Postman app. This is the repo for the Learning Center documentation. If you would like to make a feature request for the Postman app, please feel free to add an issue for the product at https://github.com/postmanlabs/postman-app-support  Thanks!
