### ISSUE TITLE
Lightweight API Client features - Support to Grapqhql

### ISSUE THREAD

**Issue by rsrinivasanhome** [postmanlabs/postman-docs#4821]
**Is your request related to a problem? Please describe.**
"After reviewing the docs, referring [link ](https://learning.postman.com/docs/getting-started/using-api-client/)
I understand the following
1)" If you choose to skip creating or signing in to an account, you will enter the lightweight API Client."
2) lightweight API Client. supports graphql requests refer screen shot

**Describe the solution you'd like**
I am not able to create graphql requests without sign in.  Please advise on how I can create grapqhl requests without postman "signin" using the  lightweight API Client.

**Comment by rsrinivasanhome** [comment]
Yes it working.  Thank you for the helpful information

**Comment by mark-anthony-postman** [comment]
That's great news! I'll go ahead and close this issue.
