### ISSUE TITLE
Request Not Found

### ISSUE THREAD

**Issue by rosepauline** [postmanlabs/postman-docs#4841]
### Is this an issue with the Learning Center documentation?

- [ ] This is an issue with Learning Center documentation.

### Describe the issue

Getting "Request Not Found" error after moving requests from one collection to other.
![ReqNotFound](https://github.com/postmanlabs/postman-docs/assets/46514057/35b60a93-ee23-4d08-bf4e-258d3cff7f26)

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
