### ISSUE TITLE
Installation instructions for Linux are incorrect

### ISSUE THREAD

**Issue by dan-arnold** [postmanlabs/postman-docs#4882]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

OS: Ubuntu 22.04.2 LTS running on WSL2:
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1702

1. [Installing Postman on Linux](https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux) suggests installing Postman with snap, however, per [this issue](https://github.com/microsoft/wslg/issues/856), Postman currently does not work on WSL2 when running through snap.
2. The Linux binary has no file extension. The x64 one is simply called "linux_64". This does not obviously tell me the format of the file.
3. The instructions say to "unzip it". But it's not a zip file, and I can't unzip it. It's not an executable file either.
4. In actuality, it's a **_gzipped tar archive_**, and should have the extension `.tar.gz`.
5. To actually extract it, I ran `tar zxf linux_64` and that worked.

Requested changes:
1. The documentation should be updated at least to specify that it's a gzipped tar and not a zip file - but also, adding a file extension to the filename would certainly be useful.
2. You should add a note about installing with snap not working on WSL2, because it took me about 3 hours of research to determine this and it's definitely not obvious. Also - this is unrelated to the documentation change, but maybe it should be fixed to work when running from snap. Many other apps work fine on WSL2 when installed with snap.

### Pages affected

https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux

### Screenshots

![image](https://github.com/postmanlabs/postman-docs/assets/1354164/4b2408ec-878e-42fb-b7ec-0d51a2b04ac4)

**Comment by byronkenoly** [comment]
manual installation instructions is also incorrect.
the exec and icon path files are wrong

**Comment by ShatilKhan** [comment]
Hi, is this Issue resolved? I don't see a PR.
If possible can you assign this issue to me please?

**Comment by vivekreddy049** [comment]
can you assign it to me @dan-arnold

**Comment by jkonrath-postman** [comment]
We'll fix this in https://github.com/postmanlabs/postman-docs/pull/4835 - I have some updates to make over there. (I finally got a Linux machine going, so I can see the problem first-hand...)

**Comment by vivekreddy049** [comment]
@jkonrath-postman i want to contribute for your organisation 
can you tell me what's the procedure

**Comment by jkonrath-postman** [comment]
@dan-arnold - https://github.com/postmanlabs/postman-docs/pull/5250 will fix the untar/unzip thing. What's odd is that depending on your browser, you might get a tar or a tar.gz, with or without an extension. 

The WSL2 thing - I opened a ticket internally, because I can't verify if that can be fixed, or we should simply say it's not supported.
