### ISSUE TITLE
Learning Center bug report

### ISSUE THREAD

**Issue by StingyJack** [postmanlabs/postman-docs#5037]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

I'm not sure if this is a problem with the docs or with the program, but [here](https://learning.postman.com/docs/getting-started/installation/postman-account/#:~:text=Signing%20up%20for%20a%20Postman,for%20a%20Postman%20account%20section.) it says that signing up is optional yet the program demands that I sign up for an account to use a feature.
![image](https://github.com/postmanlabs/postman-docs/assets/15381181/323380ed-65c4-43f4-9bfd-535b51b355c0)

### Pages affected

https://learning.postman.com/docs/getting-started/installation/postman-account/#

**Comment by jkonrath-postman** [comment]
Hi @StingyJack - the docs are technically correct here, but I could see how they might be misleading.

You don't need an account to use Postman, but the features available without an account would be limited to what's supported with the lightweight API client (https://learning.postman.com/docs/getting-started/basics/using-api-client/). I can't see what you did to get to this state, but it's likely a feature that does require an account.

I have changes scheduled to go out next week that will clarify this a bit more on the postman-account.md page.

As far as the limitation in the product itself, feel free to raise this at https://github.com/postmanlabs/postman-app-support

**Comment by StingyJack** [comment]
> the docs are technically correct here, but I could see how they might be misleading.

> You don't need an account to use Postman, 

OK.  

> ...it's likely a feature that does require an account

These are conflicting statements. Both cannot be true - the program either does or does not require an account?

If the above screenshot is not a bug then the docs are incorrectly stating that an account is optional.

**Comment by jkonrath-postman** [comment]
The sentence that was [here](https://learning.postman.com/docs/getting-started/installation/postman-account/#:~:text=Signing%20up%20for%20a%20Postman,for%20a%20Postman%20account%20section.) was removed in today's release.
