### ISSUE TITLE
Learning Center bug report

### ISSUE THREAD

**Issue by doggy8088** [postmanlabs/postman-docs#5057]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

The [Images](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/#images) section in the **Dynamic variables** page of the **Postman Learning Center** seems not working anymore. 

The docs said it's `http://lorempixel.com`, but in reality it's `http://placeimg.com`.

The important thing is these two site are all CLOSED. It could be Postman's bug.

### Pages affected

https://learning.postman.com/docs/writing-scripts/script-references/variables-list/#images

### Screenshots

![image](https://github.com/postmanlabs/postman-docs/assets/88981/70056148-2eca-4480-92cf-4ae84b09dc3b)

**Comment by jkonrath-postman** [comment]
This isn't a doc issue; it's a Faker issue. More specifically, Postman still uses Faker v5.5.3. I think v6 changed from lorempixel to either loremflickr or picsum.

I'm closing this here, but feel free to open an issue at https://github.com/postmanlabs/postman-app-support to ask about supporting a newer version of Faker.
