### ISSUE TITLE
An error occurred importing curl of type graphql.

### ISSUE THREAD

**Issue by yueguilin** [postmanlabs/postman-docs#5071]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

Importing a curl of type graphql will add an extra operationName: "" parameter to the RequestBody. The added operationName will cause an error on the request.

### Screenshots

![image](https://github.com/postmanlabs/postman-docs/assets/35106218/09e4d747-02b0-4092-8b69-dd12a4cd1a4f)
![image](https://github.com/postmanlabs/postman-docs/assets/35106218/ed68ea79-82dd-4471-b27d-f8e23cbf7827)

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
