### ISSUE TITLE
Document Reporting Options for Newman CLI

### ISSUE THREAD

**Issue by busches** [postmanlabs/postman-docs#5092]
**Is your request related to a problem? Please describe.**
I was viewing the documentation for the Newman CLI, https://learning.postman.com/docs/collections/using-newman-cli/newman-options/, and I do not see anything for the `-r` or `--reporters` options. Yet they exist according to `newman run -h` and because I can use them.

I do see documentation on Custom Reporters, which makes it sound like there are no built-in reporters, https://learning.postman.com/docs/collections/using-newman-cli/newman-custom-reporters/.

**Describe the solution you'd like**
For the `-r`/`--reporters` option to be documented, along with the built-in available options. `cli` and `junit` exist and `cli` appears to be the default. There are potentially others per the next link.

**Describe alternatives you've considered**
Googling and finding this page that told me of the `junit` reporter existed, which is what I wanted. https://issuu.com/danzzersdev/docs/api-testing-development-postman/s/13149183

**Additional context**
Nope.

**Comment by jkonrath-postman** [comment]
Hi @busches thanks for reporting this. 

The docs in the GitHub repo for Newman mention some things not in the Learning Center yet. You might want to check that out at https://github.com/postmanlabs/newman (Specifically https://github.com/postmanlabs/newman#using-reporters-with-newman)

I'll add an internal Jira so we can go over the Learning Center doc and get it updated with this. Thanks!

**Comment by busches** [comment]
Thanks for the link. Googling "Newman cli" the first hit are the docs I linked, never imagined other official docs would exist.

**Comment by jkonrath-postman** [comment]
This will be addressed when https://github.com/postmanlabs/postman-docs/pull/5114 is merged.
