### ISSUE TITLE
KONCHENY POSTMAN!

### ISSUE THREAD

**Issue by dimkinthepro** [postmanlabs/postman-docs#5126]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

 i am lost all my collections AGAIN!
it was happens after stupid login in postman
what are you thinking about youreself when just deleting peoples collections? 

### Pages affected

collections

### Screenshots

no

### Additional context

pice of shit

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!

Note: for Scratch Pad migration issues, see https://support.postman.com/hc/en-us/articles/17678699744151
