### ISSUE TITLE
Error during Lunch the Application on my local machine

### ISSUE THREAD

**Issue by SoumyaSubhrajit** [postmanlabs/postman-docs#5132]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

Hi postman team,
I would like to extend my gratitude to you for taking the time to review this issue. I am eager to contribute to your codebase and have diligently followed the prescribed procedures. However, I have encountered a series of challenges during the installation process.

While I have successfully resolved most of these issues, there is one particular problem that has proven to be more complex. The issue arises when attempting to install the necessary dependencies. Specifically, an error occurs in the **"gatsby-node.js"** file during the execution of the `onCreateNode` lifecycle.

The error message reports a failed command related to the execution of a **"git log"** command, with the following details:
`Command failed: git log -1 --pretty='%ad' --date=format:'%Y/%m/%d' E:/My Open Souce Work/postman-docs/src/pages/docs/getting-started/first-steps/overview.md
fatal: invalid object name 'E'.
`
I have diligently explored various approaches to resolve this issue but have yet to find a solution. Your guidance and assistance in resolving this matter would be greatly appreciated.

I have also attached a screenshot for your reference. Your support in resolving this matter would be invaluable.

### Screenshots

![gatsby-node js - postman-docs - Visual Studio Code 10-10-2023 23_01_14](https://github.com/postmanlabs/postman-docs/assets/112542453/eb4927e9-2eb4-40dd-93a7-b2f9f44fa7ec)
![MINGW64__e_My Open Souce Work_postman-docs 11-10-2023 00_03_09](https://github.com/postmanlabs/postman-docs/assets/112542453/f444b3f1-d325-468a-b613-a602da51121d)

**Comment by jkonrath-postman** [comment]
Hi @SoumyaSubhrajit - I don't have a Windows machine to test this, but it looks like you don't have a command-line installation of Git. By default, Windows doesn't come with git installed. VSC has a built-in client, but I don't think it installs the CLI one.

Head over to https://git-scm.com/downloads and install git from there, and check out their documentation. After it's installed and in your path, you should be able to do a `git -v` to see that it's working.

**Comment by SoumyaSubhrajit** [comment]
@jkonrath-postman Sir, the error that happened due to the `git log -1 --pretty='%ad' --date=format:"%Y/%m/%d" ${node.fileAbsolutePath}` in this line,  because file paths that contain spaces or special characters. They are used to ensure that the file path is treated as a single, complete string by the underlying system or command so we have to contain the `${node.fileAbsolutePath}` in double-quotes `"${node.fileAbsolutePath}"`, this tiny change makes my code run perfectly.
I made this correction on the code base can I have the pull request on this?
Please let me know what your thoughts on this issue.
