### ISSUE TITLE
Typo in the "Intro to the API Platform" documentation page.

### ISSUE THREAD

**Issue by Saad-Samba** [postmanlabs/postman-docs#5185]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

**Typo** in the section of "Governance and security" in the [Intro to API Platforms](https://www.postman.com/api-platform/), I think the second subheading was meant to be "_What is API security_"  instead of "_What is API design_". 

### Pages affected

https://www.postman.com/api-platform/

### Screenshots

![image](https://github.com/postmanlabs/postman-docs/assets/89049334/128931dd-e5d8-4c7f-b50b-7052b3eaa727)

### Additional context

Fantastic documentation content!

**Comment by jkonrath-postman** [comment]
Hi @Saad-Samba thanks for catching this. This page isn't actually part of the Learning Center, but is owned by our marketing team. I've reached out and opened an issue for them to fix it. Thanks again for finding this!

**Comment by Saad-Samba** [comment]
With pleasure!
