### ISSUE TITLE
Postman Performance Issue - Slowness

### ISSUE THREAD

**Issue by lahiru-rajapakshe** [postmanlabs/postman-docs#5328]
### Is this an issue with the Learning Center documentation?

- [X] This is an issue with Learning Center documentation.

### Describe the issue

I would like to report a significant performance issue with Postman, specifically related to its speed and responsiveness during the transition between requests. The overall loading time of Postman is excessively slow, hindering the efficiency of users who need to swiftly move from one request to another.

Expected Behavior:
The transition between requests should be seamless and quick, allowing users to navigate efficiently.

Actual Behavior:
There is a considerable delay during the transition between requests, resulting in an unacceptably slow user experience.

**Comment by jkonrath-postman** [comment]
Hi, it sounds like you may have been experiencing an issue with the Postman app. This is the repo for the Learning Center documentation. If you are still seeing this issue, please feel free to report an issue with the product at https://github.com/postmanlabs/postman-app-support  Thanks!
