### ISSUE TITLE
How can I set integer as value of the key/value pair in the POST mode in postman?

### ISSUE THREAD

**Issue by AniOSDeveloper** [postmanlabs/postman-docs#7]
As described on the title, there is a web API whose value of the parameter is Integer, how can I set it?
![snip20160721_2](https://cloud.githubusercontent.com/assets/14243790/17014517/8bb23c56-4f57-11e6-8a57-75204fc1e160.png)

**Comment by a85** [comment]
Whatever Postman or any other HTTP clients in an HTTP request is a string. There is no need for setting a value as an integer.
