### ISSUE TITLE
Testing with Postman

### ISSUE THREAD

**Issue by maphongba008** [postmanlabs/postman-docs#8]
I want to test my API, that 1 function has many test cases, how can I do this in Postman. Have I write many requests for 1 function?
Ex: I want to test login function, and I write 2 requests, 1 for correct email/password, and 1 for wrong email/password?

**Comment by godfrzero** [comment]
@maphongba008 Our Slack community would be the best place to ask questions like this. You can join by clicking [here](https://www.getpostman.com/slack-invite), or [go to the community directly](https://postmancommunity.slack.com) if you're already a member
